use sea_orm_migration::prelude::*;

use crate::{MigrationSpec, audit, migration_spec};

use super::support::v1;

const NAME: &str = "m20260716_000002_relational_invariants";
const SOURCE: &[u8] = include_bytes!("m20260716_000002_relational_invariants.rs");

#[derive(Debug, Clone, Copy)]
enum ReferentialAction {
    NoAction,
    Restrict,
    Cascade,
    SetNull,
}

impl ReferentialAction {
    const fn sea_query(self) -> ForeignKeyAction {
        match self {
            Self::NoAction => ForeignKeyAction::NoAction,
            Self::Restrict => ForeignKeyAction::Restrict,
            Self::Cascade => ForeignKeyAction::Cascade,
            Self::SetNull => ForeignKeyAction::SetNull,
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct ForeignKeySpec {
    name: &'static str,
    table: &'static str,
    columns: &'static [&'static str],
    target_table: &'static str,
    target_columns: &'static [&'static str],
    on_delete: ReferentialAction,
    on_update: ReferentialAction,
}

const FOREIGN_KEYS: &[ForeignKeySpec] = &[
    ForeignKeySpec {
        name: "fk_catalog_event_change_batch",
        table: "catalog_event_change",
        columns: &["catalog_sync_batch_id"],
        target_table: "catalog_sync_batch",
        target_columns: &["catalog_sync_batch_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_catalog_event_change_object",
        table: "catalog_event_change",
        columns: &["event_object_id"],
        target_table: "catalog_event_object",
        target_columns: &["event_object_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_catalog_market_change_batch",
        table: "catalog_market_change",
        columns: &["catalog_sync_batch_id"],
        target_table: "catalog_sync_batch",
        target_columns: &["catalog_sync_batch_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_catalog_market_change_event_change",
        table: "catalog_market_change",
        columns: &["event_change_id"],
        target_table: "catalog_event_change",
        target_columns: &["event_change_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_catalog_market_change_object",
        table: "catalog_market_change",
        columns: &["market_object_id"],
        target_table: "catalog_market_object",
        target_columns: &["market_object_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_catalog_sync_rejection_batch",
        table: "catalog_sync_rejection",
        columns: &["catalog_sync_batch_id"],
        target_table: "catalog_sync_batch",
        target_columns: &["catalog_sync_batch_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_clob_market_info_version_market",
        table: "clob_market_info_version",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_market_event",
        table: "market",
        columns: &["event_id"],
        target_table: "event",
        target_columns: &["event_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_backtest_path_set_model_run",
        table: "quant_backtest_path_set",
        columns: &["model_run_id"],
        target_table: "quant_model_run",
        target_columns: &["model_run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_backtest_path_set_model_version",
        table: "quant_backtest_path_set",
        columns: &["model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_backtest_path_set_runtime_config",
        table: "quant_backtest_path_set",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_backtest_path_set_training_dataset",
        table: "quant_backtest_path_set",
        columns: &["training_dataset_id"],
        target_table: "quant_training_dataset",
        target_columns: &["training_dataset_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_backtest_report_model_run",
        table: "quant_backtest_report",
        columns: &["model_run_id"],
        target_table: "quant_model_run",
        target_columns: &["model_run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_backtest_report_model_version",
        table: "quant_backtest_report",
        columns: &["model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_backtest_report_runtime_config",
        table: "quant_backtest_report",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_basis_alert_market",
        table: "quant_basis_alert",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_calibration_publication_artifact",
        table: "quant_calibration_artifact_publication",
        columns: &["artifact_id"],
        target_table: "quant_calibration_artifact",
        target_columns: &["artifact_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::Restrict,
    },
    ForeignKeySpec {
        name: "fk_quant_capital_allocation_intent",
        table: "quant_capital_allocation",
        columns: &["order_intent_id"],
        target_table: "quant_order_intent",
        target_columns: &["order_intent_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_capital_allocation_recommendation",
        table: "quant_capital_allocation",
        columns: &["recommendation_id"],
        target_table: "quant_recommendation",
        target_columns: &["recommendation_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_entry_condition_audit_instance",
        table: "quant_entry_condition_audit",
        columns: &["condition_instance_id"],
        target_table: "quant_entry_condition_instance",
        target_columns: &["condition_instance_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_entry_condition_instance_artifact",
        table: "quant_entry_condition_instance",
        columns: &["artifact_id"],
        target_table: "quant_entry_condition_artifact",
        target_columns: &["artifact_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_entry_condition_instance_recommendation",
        table: "quant_entry_condition_instance",
        columns: &["recommendation_id"],
        target_table: "quant_recommendation",
        target_columns: &["recommendation_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_equity_snapshot_account_snapshot",
        table: "quant_equity_snapshot",
        columns: &["account_snapshot_ref"],
        target_table: "quant_account_snapshot",
        target_columns: &["account_snapshot_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_execution_order_intent",
        table: "quant_execution_order",
        columns: &["order_intent_id"],
        target_table: "quant_order_intent",
        target_columns: &["order_intent_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_execution_order_market",
        table: "quant_execution_order",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_factor_value_definition",
        table: "quant_factor_value",
        columns: &["factor_definition_id"],
        target_table: "quant_factor_definition",
        target_columns: &["factor_definition_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_factor_value_feature_vector",
        table: "quant_factor_value",
        columns: &["feature_vector_id"],
        target_table: "quant_feature_vector",
        target_columns: &["feature_vector_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_factor_value_market",
        table: "quant_factor_value",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_factor_value_model_run",
        table: "quant_factor_value",
        columns: &["model_run_id"],
        target_table: "quant_model_run",
        target_columns: &["model_run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_candidate_subject",
        table: "quant_feature_parity_candidate",
        columns: &["parity_subject_id"],
        target_table: "quant_feature_parity_subject",
        target_columns: &["parity_subject_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_run_dataset",
        table: "quant_feature_parity_run",
        columns: &["training_dataset_id"],
        target_table: "quant_training_dataset",
        target_columns: &["training_dataset_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_run_model",
        table: "quant_feature_parity_run",
        columns: &["model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_run_report",
        table: "quant_feature_parity_run",
        columns: &["report_id"],
        target_table: "quant_recommendation_report",
        target_columns: &["recommendation_report_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_state_cause_run",
        table: "quant_feature_parity_state",
        columns: &["cause_run_id"],
        target_table: "quant_feature_parity_run",
        target_columns: &["run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_state_previous",
        table: "quant_feature_parity_state",
        columns: &["previous_state_id"],
        target_table: "quant_feature_parity_state",
        target_columns: &["state_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_state_recovery_run",
        table: "quant_feature_parity_state",
        columns: &["recovery_run_id"],
        target_table: "quant_feature_parity_run",
        target_columns: &["run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_subject_model_run",
        table: "quant_feature_parity_subject",
        columns: &["model_run_id"],
        target_table: "quant_model_run",
        target_columns: &["model_run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_subject_model_version",
        table: "quant_feature_parity_subject",
        columns: &["model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_subject_report",
        table: "quant_feature_parity_subject",
        columns: &["recommendation_report_id"],
        target_table: "quant_recommendation_report",
        target_columns: &["recommendation_report_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_subject_run",
        table: "quant_feature_parity_subject",
        columns: &["run_id"],
        target_table: "quant_feature_parity_run",
        target_columns: &["run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_subject_selection",
        table: "quant_feature_parity_subject",
        columns: &["market_selection_id"],
        target_table: "quant_market_selection",
        target_columns: &["market_selection_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_parity_subject_training_dataset",
        table: "quant_feature_parity_subject",
        columns: &["training_dataset_id"],
        target_table: "quant_training_dataset",
        target_columns: &["training_dataset_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_feature_vector_market",
        table: "quant_feature_vector",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_market_linkage_market",
        table: "quant_market_linkage",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_market_linkage_source_linkage",
        table: "quant_market_linkage_source",
        columns: &["linkage_id"],
        target_table: "quant_market_linkage",
        target_columns: &["linkage_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_market_selection_member_event",
        table: "quant_market_selection_member",
        columns: &["event_id"],
        target_table: "event",
        target_columns: &["event_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_market_selection_member_market",
        table: "quant_market_selection_member",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_market_selection_member_snapshot",
        table: "quant_market_selection_member",
        columns: &["market_selection_id"],
        target_table: "quant_market_selection",
        target_columns: &["market_selection_id"],
        on_delete: ReferentialAction::Cascade,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_comparison_report_baseline_report",
        table: "quant_model_comparison_report",
        columns: &["baseline_report_id"],
        target_table: "quant_backtest_report",
        target_columns: &["backtest_report_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_comparison_report_baseline_version",
        table: "quant_model_comparison_report",
        columns: &["baseline_model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_comparison_report_candidate_report",
        table: "quant_model_comparison_report",
        columns: &["candidate_report_id"],
        target_table: "quant_backtest_report",
        target_columns: &["backtest_report_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_comparison_report_candidate_version",
        table: "quant_model_comparison_report",
        columns: &["candidate_model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_comparison_report_model_run",
        table: "quant_model_comparison_report",
        columns: &["model_run_id"],
        target_table: "quant_model_run",
        target_columns: &["model_run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_governance_audit_model_version",
        table: "quant_model_governance_audit",
        columns: &["model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_governance_audit_training_dataset",
        table: "quant_model_governance_audit",
        columns: &["training_dataset_id"],
        target_table: "quant_training_dataset",
        target_columns: &["training_dataset_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_run_model_version",
        table: "quant_model_run",
        columns: &["model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_run_selection_snapshot",
        table: "quant_model_run",
        columns: &["market_selection_id"],
        target_table: "quant_market_selection",
        target_columns: &["market_selection_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_version_spec",
        table: "quant_model_version",
        columns: &["model_spec_id"],
        target_table: "quant_model_spec",
        target_columns: &["model_spec_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_version_trade_policy",
        table: "quant_model_version",
        columns: &["trade_policy_artifact_id"],
        target_table: "quant_trade_policy_artifact",
        target_columns: &["artifact_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_model_version_training_dataset",
        table: "quant_model_version",
        columns: &["training_dataset_id"],
        target_table: "quant_training_dataset",
        target_columns: &["training_dataset_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_order_intent_condition_instance",
        table: "quant_order_intent",
        columns: &["condition_instance_id"],
        target_table: "quant_entry_condition_instance",
        target_columns: &["condition_instance_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_order_intent_model_version",
        table: "quant_order_intent",
        columns: &["model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_order_intent_recommendation",
        table: "quant_order_intent",
        columns: &["recommendation_id"],
        target_table: "quant_recommendation",
        target_columns: &["recommendation_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_order_intent_runtime_config_version",
        table: "quant_order_intent",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_portfolio_plan_model_run",
        table: "quant_portfolio_plan",
        columns: &["model_run_id"],
        target_table: "quant_model_run",
        target_columns: &["model_run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_portfolio_plan_selection",
        table: "quant_portfolio_plan",
        columns: &["market_selection_id"],
        target_table: "quant_market_selection",
        target_columns: &["market_selection_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_position_event",
        table: "quant_position",
        columns: &["event_id"],
        target_table: "event",
        target_columns: &["event_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_position_intent",
        table: "quant_position",
        columns: &["order_intent_id"],
        target_table: "quant_order_intent",
        target_columns: &["order_intent_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_position_market",
        table: "quant_position",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_event",
        table: "quant_recommendation",
        columns: &["event_id"],
        target_table: "event",
        target_columns: &["event_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_market",
        table: "quant_recommendation",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_report",
        table: "quant_recommendation",
        columns: &["recommendation_report_id"],
        target_table: "quant_recommendation_report",
        target_columns: &["recommendation_report_id"],
        on_delete: ReferentialAction::Cascade,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_attribution",
        table: "quant_recommendation_attribution",
        columns: &["recommendation_id"],
        target_table: "quant_recommendation",
        target_columns: &["recommendation_id"],
        on_delete: ReferentialAction::Cascade,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_report_account_snapshot",
        table: "quant_recommendation_report",
        columns: &["account_snapshot_ref"],
        target_table: "quant_account_snapshot",
        target_columns: &["account_snapshot_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_report_dq_snapshot",
        table: "quant_recommendation_report",
        columns: &["data_quality_snapshot_ref"],
        target_table: "quant_report_data_quality_snapshot",
        target_columns: &["report_data_quality_snapshot_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_report_equity_snapshot",
        table: "quant_recommendation_report",
        columns: &["equity_snapshot_ref"],
        target_table: "quant_equity_snapshot",
        target_columns: &["equity_snapshot_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_report_model_run",
        table: "quant_recommendation_report",
        columns: &["model_run_id"],
        target_table: "quant_model_run",
        target_columns: &["model_run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_report_model_version",
        table: "quant_recommendation_report",
        columns: &["model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_report_portfolio",
        table: "quant_recommendation_report",
        columns: &["portfolio_plan_id"],
        target_table: "quant_portfolio_plan",
        target_columns: &["portfolio_plan_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_report_selection",
        table: "quant_recommendation_report",
        columns: &["market_selection_id"],
        target_table: "quant_market_selection",
        target_columns: &["market_selection_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_recommendation_report_successor",
        table: "quant_recommendation_report",
        columns: &["successor_report_id"],
        target_table: "quant_recommendation_report",
        target_columns: &["recommendation_report_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_reconciliation_execution_order",
        table: "quant_reconciliation",
        columns: &["execution_order_id"],
        target_table: "quant_execution_order",
        target_columns: &["execution_order_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_reconciliation_order_intent",
        table: "quant_reconciliation",
        columns: &["order_intent_id"],
        target_table: "quant_order_intent",
        target_columns: &["order_intent_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_report_dq_snapshot_runtime_config",
        table: "quant_report_data_quality_snapshot",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_report_fact_delivery_report",
        table: "quant_report_fact_delivery",
        columns: &["recommendation_report_id"],
        target_table: "quant_recommendation_report",
        target_columns: &["recommendation_report_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_report_run_output_report",
        table: "quant_report_run",
        columns: &["output_report_id"],
        target_table: "quant_recommendation_report",
        target_columns: &["recommendation_report_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_report_run_retry_of",
        table: "quant_report_run",
        columns: &["retry_of_run_id"],
        target_table: "quant_report_run",
        target_columns: &["report_run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_report_run_runtime_config",
        table: "quant_report_run",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_report_schedule_gap_runtime_config",
        table: "quant_report_schedule_gap",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_report_schedule_state_runtime_config",
        table: "quant_report_schedule_state",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_research_job_model_spec",
        table: "quant_research_job",
        columns: &["model_spec_id"],
        target_table: "quant_model_spec",
        target_columns: &["model_spec_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_research_job_runtime_config",
        table: "quant_research_job",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_settlement_redeem_market",
        table: "quant_settlement_redeem",
        columns: &["market_id"],
        target_table: "market",
        target_columns: &["market_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_settlement_redeem_lot_intent",
        table: "quant_settlement_redeem_lot",
        columns: &["order_intent_id"],
        target_table: "quant_order_intent",
        target_columns: &["order_intent_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_settlement_redeem_lot_position",
        table: "quant_settlement_redeem_lot",
        columns: &["position_id"],
        target_table: "quant_position",
        target_columns: &["position_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_settlement_redeem_lot_redeem",
        table: "quant_settlement_redeem_lot",
        columns: &["settlement_redeem_id"],
        target_table: "quant_settlement_redeem",
        target_columns: &["settlement_redeem_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_shadow_comparison_active_version",
        table: "quant_shadow_comparison",
        columns: &["active_model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_shadow_comparison_shadow_version",
        table: "quant_shadow_comparison",
        columns: &["shadow_model_version_id"],
        target_table: "quant_model_version",
        target_columns: &["model_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_source_slice_runtime_config",
        table: "quant_source_slice",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_trade_policy_trial_attempt_job",
        table: "quant_trade_policy_trial_attempt",
        columns: &["fit_job_id"],
        target_table: "quant_research_job",
        target_columns: &["job_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_trade_policy_validation_artifact",
        table: "quant_trade_policy_validation",
        columns: &["artifact_id"],
        target_table: "quant_trade_policy_artifact",
        target_columns: &["artifact_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_trade_policy_validation_dataset",
        table: "quant_trade_policy_validation",
        columns: &["source_dataset_id"],
        target_table: "quant_training_dataset",
        target_columns: &["training_dataset_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_trade_policy_validation_row_run",
        table: "quant_trade_policy_validation_row",
        columns: &["validation_run_id"],
        target_table: "quant_trade_policy_validation",
        target_columns: &["validation_run_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_training_dataset_model_spec",
        table: "quant_training_dataset",
        columns: &["model_spec_id"],
        target_table: "quant_model_spec",
        target_columns: &["model_spec_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_quant_training_dataset_runtime_config",
        table: "quant_training_dataset",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_role_menu_menu",
        table: "role_menu",
        columns: &["menu_id"],
        target_table: "menu",
        target_columns: &["id"],
        on_delete: ReferentialAction::Cascade,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_role_menu_role",
        table: "role_menu",
        columns: &["role_id"],
        target_table: "role",
        target_columns: &["id"],
        on_delete: ReferentialAction::Cascade,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_runtime_config_activation_approval",
        table: "runtime_config_activation",
        columns: &["runtime_config_approval_id"],
        target_table: "runtime_config_approval",
        target_columns: &["runtime_config_approval_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_runtime_config_activation_previous_version",
        table: "runtime_config_activation",
        columns: &["previous_runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::SetNull,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_runtime_config_activation_rollback_target",
        table: "runtime_config_activation",
        columns: &["rollback_target_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::SetNull,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_runtime_config_activation_version",
        table: "runtime_config_activation",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_runtime_config_approval_version",
        table: "runtime_config_approval",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_system_bootstrap_transition_approval",
        table: "system_bootstrap_transition",
        columns: &["runtime_config_approval_id"],
        target_table: "runtime_config_approval",
        target_columns: &["runtime_config_approval_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_system_bootstrap_transition_runtime_config",
        table: "system_bootstrap_transition",
        columns: &["runtime_config_version_id"],
        target_table: "runtime_config_version",
        target_columns: &["runtime_config_version_id"],
        on_delete: ReferentialAction::Restrict,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_user_role_role",
        table: "user_role",
        columns: &["role_id"],
        target_table: "role",
        target_columns: &["id"],
        on_delete: ReferentialAction::Cascade,
        on_update: ReferentialAction::NoAction,
    },
    ForeignKeySpec {
        name: "fk_user_role_user",
        table: "user_role",
        columns: &["user_id"],
        target_table: "user",
        target_columns: &["id"],
        on_delete: ReferentialAction::Cascade,
        on_update: ReferentialAction::NoAction,
    },
];

const CONSTRAINTS: &[v1::ConstraintSpec] = &[
    v1::ConstraintSpec {
        name: "catalog_event_object_schema_version_check",
        table: "catalog_event_object",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((schema_version > 0))",
    },
    v1::ConstraintSpec {
        name: "catalog_market_object_schema_version_check",
        table: "catalog_market_object",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((schema_version > 0))",
    },
    v1::ConstraintSpec {
        name: "catalog_sync_batch_check",
        table: "catalog_sync_batch",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((event_count >= 0) AND (market_count >= 0) AND (rejected_count >= 0) AND (((status = 'committed'::qp_catalog_sync_status) AND (fetched_at IS NOT NULL) AND (committed_at IS NOT NULL) AND (batch_hash IS NOT NULL) AND (failure_stage IS NULL) AND (failure_detail IS NULL)) OR ((status = 'failed'::qp_catalog_sync_status) AND (committed_at IS NULL) AND (failure_stage IS NOT NULL) AND (failure_detail IS NOT NULL) AND ((length(failure_detail) >= 1) AND (length(failure_detail) <= 2048))))))",
    },
    v1::ConstraintSpec {
        name: "catalog_sync_rejection_detail_check",
        table: "catalog_sync_rejection",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((char_length(detail) >= 1) AND (char_length(detail) <= 2048)))",
    },
    v1::ConstraintSpec {
        name: "market_check",
        table: "market",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((status <> 'active'::qp_market_status) OR (cardinality(filter_reasons) = 0)))",
    },
    v1::ConstraintSpec {
        name: "market_check1",
        table: "market",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((status <> 'filtered'::qp_market_status) OR (cardinality(filter_reasons) > 0)))",
    },
    v1::ConstraintSpec {
        name: "quant_factor_definition_definition_hash_check",
        table: "quant_factor_definition",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((definition_hash ~ '^blake3:[0-9a-f]{64}$'::text))",
    },
    v1::ConstraintSpec {
        name: "quant_factor_definition_feature_contract_hash_check",
        table: "quant_factor_definition",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((feature_contract_hash ~ '^blake3:[0-9a-f]{64}$'::text))",
    },
    v1::ConstraintSpec {
        name: "ck_quant_feature_parity_candidate_ordinal",
        table: "quant_feature_parity_candidate",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((ordinal >= 0))",
    },
    v1::ConstraintSpec {
        name: "uq_quant_feature_parity_candidate_subject_market",
        table: "quant_feature_parity_candidate",
        kind: v1::ConstraintKind::Unique,
        definition: "UNIQUE (parity_subject_id, market_id)",
    },
    v1::ConstraintSpec {
        name: "ck_quant_feature_parity_subject_identity",
        table: "quant_feature_parity_subject",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((subject_kind = 'model_run'::qp_parity_subject_kind) AND (model_run_id IS NOT NULL) AND (recommendation_report_id IS NULL) AND (model_version_id IS NULL) AND (training_dataset_id IS NULL) AND (market_selection_id IS NOT NULL) AND (decision_at IS NOT NULL) AND (selection_hash IS NOT NULL)) OR ((subject_kind = 'recommendation_report'::qp_parity_subject_kind) AND (model_run_id IS NULL) AND (recommendation_report_id IS NOT NULL) AND (model_version_id IS NULL) AND (training_dataset_id IS NULL) AND (market_selection_id IS NOT NULL) AND (decision_at IS NOT NULL) AND (selection_hash IS NOT NULL)) OR ((subject_kind = 'model_version'::qp_parity_subject_kind) AND (model_run_id IS NULL) AND (recommendation_report_id IS NULL) AND (model_version_id IS NOT NULL) AND (training_dataset_id IS NOT NULL) AND (market_selection_id IS NULL) AND (decision_at IS NULL) AND (selection_hash IS NULL))))",
    },
    v1::ConstraintSpec {
        name: "quant_feature_vector_check",
        table: "quant_feature_vector",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((decision_capture IS NULL) = (decision_capture_hash IS NULL)))",
    },
    v1::ConstraintSpec {
        name: "quant_model_spec_check",
        table: "quant_model_spec",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((status = 'retired'::qp_publication_status) OR ((jsonb_typeof(input_contract) = 'object'::text) AND (jsonb_typeof((input_contract -> 'inputs'::text)) = 'array'::text) AND (jsonb_array_length((input_contract -> 'inputs'::text)) > 0) AND (jsonb_typeof(training_contract) = 'object'::text) AND (jsonb_typeof((training_contract -> 'target_label_name'::text)) = 'string'::text) AND ((length((training_contract ->> 'target_label_name'::text)) >= 1) AND (length((training_contract ->> 'target_label_name'::text)) <= 128)) AND ((((training_contract ->> 'validation_folds'::text))::integer >= 2) AND (((training_contract ->> 'validation_folds'::text))::integer <= 20)))))",
    },
    v1::ConstraintSpec {
        name: "quant_model_spec_name_key",
        table: "quant_model_spec",
        kind: v1::ConstraintKind::Unique,
        definition: "UNIQUE (name)",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_capital_base_usd_check",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((capital_base_usd >= (0)::numeric))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((profile_id = (profile_ref ->> 'id'::text)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check1",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((valid_until IS NULL) OR (valid_until > decision_at)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check10",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((published_at IS NULL) OR (published_at >= decision_at)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check11",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((superseded_at IS NULL) OR (superseded_at >= published_at)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check12",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((obsoleted_at IS NULL) OR (obsoleted_at >= decision_at)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check13",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((expired_at IS NULL) OR (expired_at >= published_at)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check14",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((revoked_at IS NULL) OR (revoked_at >= decision_at)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check2",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((successor_report_id IS NULL) OR (successor_report_id <> recommendation_report_id)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check3",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = ANY (ARRAY['prepared'::qp_recommendation_report_status, 'published'::qp_recommendation_report_status])) AND (status_reason IS NULL)) OR ((status <> ALL (ARRAY['prepared'::qp_recommendation_report_status, 'published'::qp_recommendation_report_status])) AND (status_reason IS NOT NULL))))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check4",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'prepared'::qp_recommendation_report_status) AND (published_at IS NULL) AND (successor_report_id IS NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NULL) AND (expired_at IS NULL)) OR (status <> 'prepared'::qp_recommendation_report_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check5",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'published'::qp_recommendation_report_status) AND (published_at IS NOT NULL) AND (successor_report_id IS NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NULL) AND (expired_at IS NULL)) OR (status <> 'published'::qp_recommendation_report_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check6",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'superseded'::qp_recommendation_report_status) AND (published_at IS NOT NULL) AND (successor_report_id IS NOT NULL) AND (superseded_at IS NOT NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NULL) AND (expired_at IS NULL)) OR (status <> 'superseded'::qp_recommendation_report_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check7",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'obsolete'::qp_recommendation_report_status) AND (published_at IS NULL) AND (successor_report_id IS NOT NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NOT NULL) AND (revoked_at IS NULL) AND (expired_at IS NULL)) OR (status <> 'obsolete'::qp_recommendation_report_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check8",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'revoked'::qp_recommendation_report_status) AND (successor_report_id IS NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NOT NULL) AND (expired_at IS NULL)) OR (status <> 'revoked'::qp_recommendation_report_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_check9",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'expired'::qp_recommendation_report_status) AND (published_at IS NOT NULL) AND (successor_report_id IS NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NULL) AND (expired_at IS NOT NULL)) OR (status <> 'expired'::qp_recommendation_report_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_horizon_secs_check",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((horizon_secs > 0))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_profile_id_check",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((char_length(profile_id) >= 1) AND (char_length(profile_id) <= 128)))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_status_reason_check",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((status_reason IS NULL) OR ((char_length(status_reason) >= 1) AND (char_length(status_reason) <= 4096))))",
    },
    v1::ConstraintSpec {
        name: "quant_recommendation_report_top_n_check",
        table: "quant_recommendation_report",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((top_n > 0))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_check",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((bundle_bytes > 0) AND (recommendation_row_count >= 0) AND (funnel_row_count >= 0) AND (attempt_count >= 0)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_check1",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((claim_owner IS NULL) = (lease_expires_at IS NULL)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_check2",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'pending'::qp_report_fact_delivery_status) AND (attempt_count = 0) AND (claim_owner IS NULL) AND (next_attempt_at IS NULL) AND (last_error IS NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'pending'::qp_report_fact_delivery_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_check3",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'delivering'::qp_report_fact_delivery_status) AND (attempt_count > 0) AND (claim_owner IS NOT NULL) AND (next_attempt_at IS NULL) AND (last_error IS NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'delivering'::qp_report_fact_delivery_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_check4",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'retrying'::qp_report_fact_delivery_status) AND (attempt_count > 0) AND (claim_owner IS NULL) AND (next_attempt_at IS NOT NULL) AND (last_error IS NOT NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'retrying'::qp_report_fact_delivery_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_check5",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'failed'::qp_report_fact_delivery_status) AND (attempt_count > 0) AND (claim_owner IS NULL) AND (next_attempt_at IS NULL) AND (last_error IS NOT NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'failed'::qp_report_fact_delivery_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_check6",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'verified'::qp_report_fact_delivery_status) AND (attempt_count > 0) AND (next_attempt_at IS NULL) AND (last_error IS NULL) AND (verified_at IS NOT NULL)) OR (status <> 'verified'::qp_report_fact_delivery_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_check7",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'cancelled'::qp_report_fact_delivery_status) AND (claim_owner IS NULL) AND (next_attempt_at IS NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'cancelled'::qp_report_fact_delivery_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_check8",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((announced_at IS NULL) OR ((status = 'verified'::qp_report_fact_delivery_status) AND (claim_owner IS NULL) AND (announced_at >= verified_at))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_fact_delivery_last_error_check",
        table: "quant_report_fact_delivery",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((last_error IS NULL) OR ((char_length(last_error) >= 1) AND (char_length(last_error) <= 4096))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((trigger_kind = 'scheduled'::qp_report_trigger_kind) AND (schedule_id IS NOT NULL) AND (request_id IS NULL) AND (scheduled_for IS NOT NULL)) OR ((trigger_kind = 'ad_hoc'::qp_report_trigger_kind) AND (schedule_id IS NULL) AND (request_id IS NOT NULL) AND (scheduled_for IS NULL))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check1",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((status <> 'queued'::qp_report_run_status) OR (trigger_kind = 'ad_hoc'::qp_report_trigger_kind) OR ((top_n IS NULL) AND (knowledge_lag_secs IS NULL))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check10",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'succeeded'::qp_report_run_status) AND (started_at IS NOT NULL) AND (decision_at IS NOT NULL) AND (heartbeat_at IS NOT NULL) AND (runtime_config_version_id IS NOT NULL) AND (top_n IS NOT NULL) AND (knowledge_lag_secs IS NOT NULL) AND (terminal_reason IS NULL) AND (error_code IS NULL) AND (error_summary IS NULL)) OR (status <> 'succeeded'::qp_report_run_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check11",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'failed'::qp_report_run_status) AND (started_at IS NOT NULL) AND (decision_at IS NOT NULL) AND (heartbeat_at IS NOT NULL) AND (runtime_config_version_id IS NOT NULL) AND (top_n IS NOT NULL) AND (knowledge_lag_secs IS NOT NULL) AND (terminal_reason = 'build_failed'::qp_report_run_terminal_reason) AND (error_code IS NOT NULL) AND (error_summary IS NOT NULL)) OR (status <> 'failed'::qp_report_run_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check12",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'abandoned'::qp_report_run_status) AND (started_at IS NOT NULL) AND (decision_at IS NOT NULL) AND (heartbeat_at IS NOT NULL) AND (runtime_config_version_id IS NOT NULL) AND (top_n IS NOT NULL) AND (knowledge_lag_secs IS NOT NULL) AND (terminal_reason = 'lease_expired'::qp_report_run_terminal_reason) AND (error_code IS NULL) AND (error_summary IS NULL)) OR (status <> 'abandoned'::qp_report_run_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check13",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((terminal_reason <> 'queue_expired'::qp_report_run_terminal_reason) OR (trigger_kind = 'ad_hoc'::qp_report_trigger_kind)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check14",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((terminal_reason <> ALL (ARRAY['coalesced_by_newer_occurrence'::qp_report_run_terminal_reason, 'schedule_reconfigured'::qp_report_run_terminal_reason])) OR (trigger_kind = 'scheduled'::qp_report_trigger_kind)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check15",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((started_at IS NULL) OR ((decision_at = started_at) AND (requested_at <= started_at))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check16",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((finished_at IS NULL) OR (started_at IS NULL) OR (finished_at >= started_at)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check17",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((lease_expires_at IS NULL) OR (lease_expires_at > heartbeat_at)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check2",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((char_length(trigger_key) >= 1) AND (char_length(trigger_key) <= 512) AND ((schedule_id IS NULL) OR ((char_length(schedule_id) >= 1) AND (char_length(schedule_id) <= 128))) AND ((request_id IS NULL) OR ((char_length(request_id) >= 1) AND (char_length(request_id) <= 256)))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check3",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((retry_of_run_id IS NULL) OR (trigger_kind = 'ad_hoc'::qp_report_trigger_kind)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check4",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((scheduled_for IS NULL) OR (scheduled_for <= requested_at)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check5",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'succeeded'::qp_report_run_status) AND (output_report_id IS NOT NULL)) OR ((status <> 'succeeded'::qp_report_run_status) AND (output_report_id IS NULL))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check6",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'running'::qp_report_run_status) AND (lease_owner IS NOT NULL) AND (started_at IS NOT NULL) AND (decision_at IS NOT NULL) AND (heartbeat_at IS NOT NULL) AND (lease_expires_at IS NOT NULL) AND (runtime_config_version_id IS NOT NULL) AND (top_n IS NOT NULL) AND (knowledge_lag_secs IS NOT NULL) AND (finished_at IS NULL) AND (terminal_reason IS NULL)) OR ((status <> 'running'::qp_report_run_status) AND (lease_owner IS NULL) AND (lease_expires_at IS NULL))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check7",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((status = ANY (ARRAY['succeeded'::qp_report_run_status, 'failed'::qp_report_run_status, 'skipped'::qp_report_run_status, 'abandoned'::qp_report_run_status])) = (finished_at IS NOT NULL)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check8",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'queued'::qp_report_run_status) AND (started_at IS NULL) AND (decision_at IS NULL) AND (heartbeat_at IS NULL) AND (finished_at IS NULL) AND (runtime_config_version_id IS NULL) AND (output_report_id IS NULL) AND (terminal_reason IS NULL) AND (error_code IS NULL) AND (error_summary IS NULL)) OR (status <> 'queued'::qp_report_run_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_check9",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'skipped'::qp_report_run_status) AND (started_at IS NULL) AND (decision_at IS NULL) AND (heartbeat_at IS NULL) AND (runtime_config_version_id IS NULL) AND (output_report_id IS NULL) AND (terminal_reason = ANY (ARRAY['coalesced_by_newer_occurrence'::qp_report_run_terminal_reason, 'schedule_reconfigured'::qp_report_run_terminal_reason, 'queue_expired'::qp_report_run_terminal_reason])) AND (error_code IS NULL) AND (error_summary IS NULL)) OR (status <> 'skipped'::qp_report_run_status)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_error_code_check",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((error_code IS NULL) OR ((char_length(error_code) >= 1) AND (char_length(error_code) <= 128))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_error_summary_check",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((error_summary IS NULL) OR ((char_length(error_summary) >= 1) AND (char_length(error_summary) <= 4096))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_knowledge_lag_secs_check",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((knowledge_lag_secs IS NULL) OR (knowledge_lag_secs >= 0)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_run_top_n_check",
        table: "quant_report_run",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((top_n IS NULL) OR (top_n > 0)))",
    },
    v1::ConstraintSpec {
        name: "quant_report_schedule_gap_check",
        table: "quant_report_schedule_gap",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((first_scheduled_for <= last_scheduled_for))",
    },
    v1::ConstraintSpec {
        name: "quant_report_schedule_gap_detail_check",
        table: "quant_report_schedule_gap",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((detail IS NULL) OR ((char_length(detail) >= 1) AND (char_length(detail) <= 4096))))",
    },
    v1::ConstraintSpec {
        name: "quant_report_schedule_gap_missed_count_check",
        table: "quant_report_schedule_gap",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((missed_count > 0))",
    },
    v1::ConstraintSpec {
        name: "quant_research_readiness_evidence_check",
        table: "quant_research_readiness_evidence",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((window_start < window_end) AND (window_end <= observed_at) AND (observed_at < expires_at) AND (artifact_version <> ''::text) AND (attestation_key_id <> ''::text)))",
    },
    v1::ConstraintSpec {
        name: "quant_source_slice_check",
        table: "quant_source_slice",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((window_start < window_end) AND (window_end <= pit_cutoff) AND (evaluation_track = ANY (ARRAY['research_only'::text, 'semi_auto_candidate'::text])) AND (((status = 'materializing'::qp_source_slice_status) AND (manifest_uri IS NULL) AND (manifest_hash IS NULL) AND (manifest_json IS NULL) AND (failure_detail IS NULL) AND (completed_at IS NULL)) OR ((status = 'ready'::qp_source_slice_status) AND (manifest_uri IS NOT NULL) AND (manifest_hash IS NOT NULL) AND (manifest_json IS NOT NULL) AND (failure_detail IS NULL) AND (completed_at IS NOT NULL)) OR ((status = 'failed'::qp_source_slice_status) AND (manifest_uri IS NULL) AND (manifest_hash IS NULL) AND (manifest_json IS NULL) AND (failure_detail IS NOT NULL) AND (completed_at IS NOT NULL)))))",
    },
    v1::ConstraintSpec {
        name: "quant_trade_policy_trial_attempt_check",
        table: "quant_trade_policy_trial_attempt",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((attempt_ordinal >= 0) AND ((length(btrim((candidate_id)::text)) >= 1) AND (length(btrim((candidate_id)::text)) <= 128)) AND ((fold_index IS NULL) OR (fold_index >= 0)) AND ((path_index IS NULL) OR (path_index >= 0)) AND ((evidence_row_count IS NULL) OR (evidence_row_count >= 0))))",
    },
    v1::ConstraintSpec {
        name: "quant_trade_policy_trial_attempt_check1",
        table: "quant_trade_policy_trial_attempt",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((scope = ANY (ARRAY['candidate'::qp_trade_policy_trial_scope, 'latency_stress'::qp_trade_policy_trial_scope])) AND (fold_index IS NULL) AND (path_index IS NULL)) OR ((scope = 'fold'::qp_trade_policy_trial_scope) AND (fold_index IS NOT NULL) AND (path_index IS NULL)) OR ((scope = 'path'::qp_trade_policy_trial_scope) AND (fold_index IS NULL) AND (path_index IS NOT NULL))))",
    },
    v1::ConstraintSpec {
        name: "quant_trade_policy_trial_attempt_check2",
        table: "quant_trade_policy_trial_attempt",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status = 'succeeded'::qp_trade_policy_trial_status) AND (metrics_json IS NOT NULL) AND (failure_detail IS NULL) AND (evidence_uri IS NOT NULL) AND (evidence_hash IS NOT NULL) AND (evidence_row_count IS NOT NULL)) OR ((status = ANY (ARRAY['failed'::qp_trade_policy_trial_status, 'cancelled'::qp_trade_policy_trial_status])) AND (metrics_json IS NULL) AND ((length(btrim(failure_detail)) >= 1) AND (length(btrim(failure_detail)) <= 8192)))))",
    },
    v1::ConstraintSpec {
        name: "quant_trade_policy_trial_attempt_check3",
        table: "quant_trade_policy_trial_attempt",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((evidence_uri IS NULL) AND (evidence_hash IS NULL) AND (evidence_row_count IS NULL)) OR ((evidence_uri IS NOT NULL) AND (evidence_hash IS NOT NULL) AND (evidence_row_count IS NOT NULL))))",
    },
    v1::ConstraintSpec {
        name: "quant_trade_policy_validation_check",
        table: "quant_trade_policy_validation",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((total_rows >= 0) AND (passed_rows >= 0) AND (failed_rows >= 0) AND ((passed_rows + failed_rows) <= total_rows) AND ((length(btrim(reason)) >= 1) AND (length(btrim(reason)) <= 512)) AND (((status = 'running'::qp_trade_policy_validation_status) AND (validation_hash IS NULL) AND (failure_detail IS NULL) AND (completed_at IS NULL)) OR ((status = 'succeeded'::qp_trade_policy_validation_status) AND (validation_hash IS NOT NULL) AND (failure_detail IS NULL) AND (completed_at IS NOT NULL) AND (failed_rows = 0) AND (passed_rows = total_rows) AND (total_rows > 0)) OR ((status = ANY (ARRAY['failed'::qp_trade_policy_validation_status, 'cancelled'::qp_trade_policy_validation_status])) AND (validation_hash IS NOT NULL) AND (failure_detail IS NOT NULL) AND (completed_at IS NOT NULL)))))",
    },
    v1::ConstraintSpec {
        name: "quant_trade_policy_validation_row_check",
        table: "quant_trade_policy_validation_row",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((row_ordinal >= 0) AND (record_key <> ''::text) AND ((evidence_kind)::text = ANY (ARRAY[('observation_eligibility'::character varying)::text, ('fills'::character varying)::text, ('candidate_trials'::character varying)::text, ('cohort_trials'::character varying)::text, ('cpcv_paths'::character varying)::text, ('coverage_gaps'::character varying)::text, ('statistical_summaries'::character varying)::text])) AND ((expected_row_hash IS NOT NULL) OR (actual_row_hash IS NOT NULL)) AND ((passed AND (expected_row_hash = actual_row_hash) AND (diagnostic_kind IS NULL) AND (detail IS NULL)) OR ((NOT passed) AND (diagnostic_kind IS NOT NULL) AND (detail IS NOT NULL)))))",
    },
    v1::ConstraintSpec {
        name: "quant_training_dataset_check",
        table: "quant_training_dataset",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((((status <> ALL (ARRAY['planned'::qp_training_dataset_status, 'building'::qp_training_dataset_status])) OR ((feature_schema_version IS NOT NULL) AND (sample_sources IS NOT NULL) AND (feature_schema_hash IS NULL) AND (factor_schema_hash IS NULL) AND (label_schema_hash IS NULL) AND (dataset_hash IS NULL) AND (manifest_hash IS NULL) AND (manifest_json IS NULL) AND (artifact_bytes_hash IS NULL) AND (parquet_uri IS NULL) AND (sample_count IS NULL) AND (coverage_json IS NULL) AND (completed_at IS NULL))) AND ((status <> ALL (ARRAY['ready'::qp_training_dataset_status, 'insufficient_labels'::qp_training_dataset_status])) OR ((feature_schema_version IS NOT NULL) AND (sample_sources IS NOT NULL) AND (feature_schema_hash IS NOT NULL) AND (factor_schema_hash IS NOT NULL) AND (label_schema_hash IS NOT NULL) AND (dataset_hash IS NOT NULL) AND (manifest_hash IS NOT NULL) AND (manifest_json IS NOT NULL) AND (artifact_bytes_hash IS NOT NULL) AND (parquet_uri IS NOT NULL) AND (sample_count IS NOT NULL) AND (sample_count >= 0) AND (coverage_json IS NOT NULL) AND (completed_at IS NOT NULL))) AND ((status <> 'failed'::qp_training_dataset_status) OR (completed_at IS NOT NULL))))",
    },
    v1::ConstraintSpec {
        name: "ck_runtime_config_approval_expiry",
        table: "runtime_config_approval",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((expires_at IS NULL) OR (expires_at > decided_at)))",
    },
    v1::ConstraintSpec {
        name: "ck_runtime_config_approval_reason",
        table: "runtime_config_approval",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((length(reason) >= 1) AND (length(reason) <= 2048)))",
    },
    v1::ConstraintSpec {
        name: "runtime_config_version_config_hash_key",
        table: "runtime_config_version",
        kind: v1::ConstraintKind::Unique,
        definition: "UNIQUE (config_hash)",
    },
    v1::ConstraintSpec {
        name: "ck_schema_migration_audit_algorithm",
        table: "schema_migration_audit",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK (((checksum_algorithm)::text = 'blake3-256'::text))",
    },
    v1::ConstraintSpec {
        name: "ck_schema_migration_audit_artifact_length",
        table: "schema_migration_audit",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((artifact_length > 0))",
    },
    v1::ConstraintSpec {
        name: "ck_schema_migration_audit_checksum",
        table: "schema_migration_audit",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((checksum ~ '^[0-9a-f]{64}$'::text))",
    },
    v1::ConstraintSpec {
        name: "ck_system_bootstrap_transition_contract_version",
        table: "system_bootstrap_transition",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((bootstrap_contract_version = 1))",
    },
    v1::ConstraintSpec {
        name: "ck_system_bootstrap_transition_revision",
        table: "system_bootstrap_transition",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((state_revision > 0))",
    },
    v1::ConstraintSpec {
        name: "ck_system_runtime_state_contract_version",
        table: "system_runtime_state",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((bootstrap_contract_version = 1))",
    },
    v1::ConstraintSpec {
        name: "ck_system_runtime_state_revision",
        table: "system_runtime_state",
        kind: v1::ConstraintKind::Check,
        definition: "CHECK ((state_revision >= 0))",
    },
];

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        NAME
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        for spec in CONSTRAINTS {
            v1::create_constraint(manager, *spec).await?;
        }
        for spec in FOREIGN_KEYS {
            let mut statement = ForeignKey::create();
            statement
                .name(spec.name)
                .from_tbl((Alias::new("public"), Alias::new(spec.table)))
                .to_tbl((Alias::new("public"), Alias::new(spec.target_table)))
                .on_delete(spec.on_delete.sea_query())
                .on_update(spec.on_update.sea_query());
            for column in spec.columns {
                statement.from_col(Alias::new(*column));
            }
            for column in spec.target_columns {
                statement.to_col(Alias::new(*column));
            }
            manager.create_foreign_key(statement.clone()).await?;
        }
        audit::record(manager, spec()).await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        audit::remove(manager, NAME).await?;
        for spec in FOREIGN_KEYS.iter().rev() {
            manager
                .drop_foreign_key(
                    ForeignKey::drop()
                        .name(spec.name)
                        .table((Alias::new("public"), Alias::new(spec.table)))
                        .to_owned(),
                )
                .await?;
        }
        for spec in CONSTRAINTS.iter().rev() {
            v1::drop_constraint(manager, *spec).await?;
        }
        Ok(())
    }
}

pub fn spec() -> MigrationSpec {
    migration_spec(NAME, &[SOURCE, v1::SOURCE])
}
