[package]
name = "oxide-arb-models"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
oxide-arb-error = { workspace = true }
oxide-arb-macros = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
sea-orm = { workspace = true }
strum = { workspace = true }
validator = { workspace = true }
bitcode = { workspace = true }
tracing = { workspace = true }
config = { workspace = true }
polymarket_client_sdk_v2 = { workspace = true, features = ["clob"] }

[lints]
workspace = true
