[package]
name = "quant-pivot-xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "quant-pivot-xtask"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
quant-pivot-models = { workspace = true }
quant-pivot-storage = { workspace = true }
rustls = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
