//! Shared Postgres repositories wired once at boot from a single pool handle.
//!
//! Every `Pg*Repository` owns a [`DatabaseConnection`] (pool handle clone).
//! [`PgRepositories::wire`] constructs each repository exactly once; downstream
//! bundles and services [`Arc::clone`] the shared instances.

use std::sync::Arc;

use quant_pivot_repository::postgres::{
    PgAccountSnapshotRepository, PgBacktestPathSetRepository, PgBacktestReportRepository,
    PgBasisAlertRepository, PgCalibrationArtifactRepository, PgCapitalAllocationRepository,
    PgCatalogLedgerRepository, PgClobMarketInfoRepository, PgDomainProjectionRepository,
    PgDomainSourceCursorRepository, PgDomainSourceExpectationRepository,
    PgEntryConditionRepository, PgEquitySnapshotRepository, PgEventRepository,
    PgExecutionAccountRepository, PgExecutionOrderRepository, PgExecutionSubmissionRepository,
    PgFactorRepository, PgFeatureParityRepository, PgFeatureRepository, PgMarketLinkageRepository,
    PgMarketRepository, PgMarketSelectionRepository, PgMenuRepository,
    PgModelComparisonReportRepository, PgModelGovernanceAuditRepository, PgModelRegistryRepository,
    PgModelRunRepository, PgOperationLogRepository, PgOrderIntentRepository, PgPolicyRepository,
    PgPositionRepository, PgRecommendationExecutionOutcomeRepository,
    PgRecommendationReportRepository, PgRecommendationRepository,
    PgRecommendationResolutionOutcomeRepository, PgReconciliationRepository, PgReportRunRepository,
    PgResearchJobRepository, PgResearchReadinessEvidenceRepository, PgReservedCapitalRepository,
    PgRoleMenuRepository, PgRolePermissionRepository, PgRoleRepository, PgRuntimeControlRepository,
    PgShadowComparisonRepository, PgSourceSliceRepository, PgTradePolicyRepository,
    PgTradeTapeBlockCursorRepository, PgTrainingDatasetRepository, PgUserRepository,
    PgUserRoleRepository,
    quant::{
        settlement_governance::PgSettlementGovernanceRepository,
        settlement_redeem::PgSettlementRedeemRepository,
    },
};
use quant_pivot_storage::postgres::PostgresPool;

/// All Postgres OLTP repositories shared across runtime bundles.
pub struct PgRepositories {
    pub runtime_config: Arc<PgPolicyRepository>,
    pub runtime_control: Arc<PgRuntimeControlRepository>,
    pub operation_log: Arc<PgOperationLogRepository>,
    pub market: Arc<PgMarketRepository>,
    pub event: Arc<PgEventRepository>,
    pub catalog_ledger: Arc<PgCatalogLedgerRepository>,
    pub clob_market_info: Arc<PgClobMarketInfoRepository>,
    pub order_intent: Arc<PgOrderIntentRepository>,
    pub entry_condition: Arc<PgEntryConditionRepository>,
    pub execution_account: Arc<PgExecutionAccountRepository>,
    pub execution_submission: Arc<PgExecutionSubmissionRepository>,
    pub execution_order: Arc<PgExecutionOrderRepository>,
    pub reconciliation: Arc<PgReconciliationRepository>,
    pub position: Arc<PgPositionRepository>,
    pub capital_allocation: Arc<PgCapitalAllocationRepository>,
    pub settlement_redeem: Arc<PgSettlementRedeemRepository>,
    pub settlement_governance: Arc<PgSettlementGovernanceRepository>,
    pub recommendation: Arc<PgRecommendationRepository>,
    pub recommendation_resolution_outcome: Arc<PgRecommendationResolutionOutcomeRepository>,
    pub recommendation_execution_outcome: Arc<PgRecommendationExecutionOutcomeRepository>,
    pub recommendation_report: Arc<PgRecommendationReportRepository>,
    pub report_run: Arc<PgReportRunRepository>,
    pub equity_snapshot: Arc<PgEquitySnapshotRepository>,
    pub market_selection: Arc<PgMarketSelectionRepository>,
    pub feature: Arc<PgFeatureRepository>,
    pub feature_parity: Arc<PgFeatureParityRepository>,
    pub factor: Arc<PgFactorRepository>,
    pub calibration_artifact: Arc<PgCalibrationArtifactRepository>,
    pub trade_policy: Arc<PgTradePolicyRepository>,
    pub model_run: Arc<PgModelRunRepository>,
    pub model_registry: Arc<PgModelRegistryRepository>,
    pub shadow_comparison: Arc<PgShadowComparisonRepository>,
    pub training_dataset: Arc<PgTrainingDatasetRepository>,
    pub source_slice: Arc<PgSourceSliceRepository>,
    pub backtest_report: Arc<PgBacktestReportRepository>,
    pub backtest_path_set: Arc<PgBacktestPathSetRepository>,
    pub comparison_report: Arc<PgModelComparisonReportRepository>,
    pub governance_audit: Arc<PgModelGovernanceAuditRepository>,
    pub research_job: Arc<PgResearchJobRepository>,
    pub research_readiness: Arc<PgResearchReadinessEvidenceRepository>,
    pub reserved_capital: Arc<PgReservedCapitalRepository>,
    pub user: Arc<PgUserRepository>,
    pub role: Arc<PgRoleRepository>,
    pub menu: Arc<PgMenuRepository>,
    pub user_role: Arc<PgUserRoleRepository>,
    pub role_menu: Arc<PgRoleMenuRepository>,
    pub role_permission: Arc<PgRolePermissionRepository>,
    pub account_snapshot: Arc<PgAccountSnapshotRepository>,
    pub trade_tape_block_cursor: Arc<PgTradeTapeBlockCursorRepository>,
    pub market_linkage: Arc<PgMarketLinkageRepository>,
    pub domain_source_cursor: Arc<PgDomainSourceCursorRepository>,
    pub domain_source_expectation: Arc<PgDomainSourceExpectationRepository>,
    pub domain_projection: Arc<PgDomainProjectionRepository>,
    pub basis_alert: Arc<PgBasisAlertRepository>,
}

impl PgRepositories {
    /// Construct every shared repository from the connected pool (boot-only).
    #[must_use]
    pub fn wire(pg: &PostgresPool) -> Self {
        let db = pg.connection().clone();
        Self {
            runtime_config: Arc::new(PgPolicyRepository::new(db.clone())),
            runtime_control: Arc::new(PgRuntimeControlRepository::new(db.clone())),
            operation_log: Arc::new(PgOperationLogRepository::new(db.clone())),
            market: Arc::new(PgMarketRepository::new(db.clone())),
            event: Arc::new(PgEventRepository::new(db.clone())),
            catalog_ledger: Arc::new(PgCatalogLedgerRepository::new(db.clone())),
            clob_market_info: Arc::new(PgClobMarketInfoRepository::new(db.clone())),
            order_intent: Arc::new(PgOrderIntentRepository::new(db.clone())),
            entry_condition: Arc::new(PgEntryConditionRepository::new(db.clone())),
            execution_account: Arc::new(PgExecutionAccountRepository::new(db.clone())),
            execution_submission: Arc::new(PgExecutionSubmissionRepository::new(db.clone())),
            execution_order: Arc::new(PgExecutionOrderRepository::new(db.clone())),
            reconciliation: Arc::new(PgReconciliationRepository::new(db.clone())),
            position: Arc::new(PgPositionRepository::new(db.clone())),
            capital_allocation: Arc::new(PgCapitalAllocationRepository::new(db.clone())),
            settlement_redeem: Arc::new(PgSettlementRedeemRepository::new(db.clone())),
            settlement_governance: Arc::new(PgSettlementGovernanceRepository::new(db.clone())),
            recommendation: Arc::new(PgRecommendationRepository::new(db.clone())),
            recommendation_resolution_outcome: Arc::new(
                PgRecommendationResolutionOutcomeRepository::new(db.clone()),
            ),
            recommendation_execution_outcome: Arc::new(
                PgRecommendationExecutionOutcomeRepository::new(db.clone()),
            ),
            recommendation_report: Arc::new(PgRecommendationReportRepository::new(db.clone())),
            report_run: Arc::new(PgReportRunRepository::new(db.clone())),
            equity_snapshot: Arc::new(PgEquitySnapshotRepository::new(db.clone())),
            market_selection: Arc::new(PgMarketSelectionRepository::new(db.clone())),
            feature: Arc::new(PgFeatureRepository::new(db.clone())),
            feature_parity: Arc::new(PgFeatureParityRepository::new(db.clone())),
            factor: Arc::new(PgFactorRepository::new(db.clone())),
            calibration_artifact: Arc::new(PgCalibrationArtifactRepository::new(db.clone())),
            trade_policy: Arc::new(PgTradePolicyRepository::new(db.clone())),
            model_run: Arc::new(PgModelRunRepository::new(db.clone())),
            model_registry: Arc::new(PgModelRegistryRepository::new(db.clone())),
            shadow_comparison: Arc::new(PgShadowComparisonRepository::new(db.clone())),
            training_dataset: Arc::new(PgTrainingDatasetRepository::new(db.clone())),
            source_slice: Arc::new(PgSourceSliceRepository::new(db.clone())),
            backtest_report: Arc::new(PgBacktestReportRepository::new(db.clone())),
            backtest_path_set: Arc::new(PgBacktestPathSetRepository::new(db.clone())),
            comparison_report: Arc::new(PgModelComparisonReportRepository::new(db.clone())),
            governance_audit: Arc::new(PgModelGovernanceAuditRepository::new(db.clone())),
            research_job: Arc::new(PgResearchJobRepository::new(db.clone())),
            research_readiness: Arc::new(PgResearchReadinessEvidenceRepository::new(db.clone())),
            reserved_capital: Arc::new(PgReservedCapitalRepository::new(db.clone())),
            user: Arc::new(PgUserRepository::new(db.clone())),
            role: Arc::new(PgRoleRepository::new(db.clone())),
            menu: Arc::new(PgMenuRepository::new(db.clone())),
            user_role: Arc::new(PgUserRoleRepository::new(db.clone())),
            role_menu: Arc::new(PgRoleMenuRepository::new(db.clone())),
            role_permission: Arc::new(PgRolePermissionRepository::new(db.clone())),
            account_snapshot: Arc::new(PgAccountSnapshotRepository::new(db.clone())),
            trade_tape_block_cursor: Arc::new(PgTradeTapeBlockCursorRepository::new(db.clone())),
            market_linkage: Arc::new(PgMarketLinkageRepository::new(db.clone())),
            domain_source_cursor: Arc::new(PgDomainSourceCursorRepository::new(db.clone())),
            domain_source_expectation: Arc::new(PgDomainSourceExpectationRepository::new(
                db.clone(),
            )),
            domain_projection: Arc::new(PgDomainProjectionRepository::new(db.clone())),
            basis_alert: Arc::new(PgBasisAlertRepository::new(db)),
        }
    }
}
