CREATE TABLE IF NOT EXISTS opportunity_audit (
    opportunity_id  String,
    execution_id    String,
    trade_id        Nullable(String),
    market_id       String,
    event_id        String,
    token_id        String,
    side            Enum8('Buy' = 1, 'Sell' = 2),
    entry_price     Nullable(Decimal64(8)),
    fill_price      Nullable(Decimal64(8)),
    requested_shares Nullable(Decimal128(18)),
    filled_shares   Nullable(Decimal128(18)),
    total_cost_usd  Nullable(Decimal128(18)),
    fees_usd        Nullable(Decimal128(18)),
    net_profit_usd  Nullable(Decimal128(18)),
    expected_profit_usd Nullable(Decimal128(18)),
    edge_bps        Nullable(Decimal64(4)),
    resolution_prob Nullable(Decimal64(8)),
    confidence      Nullable(Decimal64(8)),
    fill_probability Nullable(Decimal64(8)),
    convergence_secs Nullable(UInt32),
    price_zone      Nullable(Enum8('Z95' = 1, 'Z96' = 2, 'Z97' = 3, 'Z98' = 4, 'Z99' = 5)),
    duration_bucket Nullable(Enum8('Short' = 1, 'Medium' = 2, 'Long' = 3, 'VeryLong' = 4)),
    depth_used_pct  Nullable(Decimal64(8)),
    staleness       Nullable(Enum8('Fresh' = 1, 'Acceptable' = 2, 'Stale' = 3, 'Expired' = 4)),
    category        Nullable(Enum8('Geopolitics' = 1, 'Sports' = 2, 'Politics' = 3, 'Finance' = 4, 'Tech' = 5, 'Culture' = 6, 'Weather' = 7, 'Economics' = 8, 'Crypto' = 9, 'Other' = 10)),
    stage           Enum8('Detected' = 1, 'ValidationRejected' = 2, 'RiskRejected' = 3, 'SizingRejected' = 4, 'Filled' = 5, 'Missed' = 6, 'Failed' = 7, 'Settled' = 8, 'FactorValidationRejected' = 9),
    stage_order     UInt8,
    stage_at        DateTime64(3, 'UTC'),
    payout_usd      Nullable(Decimal128(18)),
    realized_pnl_usd Nullable(Decimal128(18)),
    settlement_status Nullable(Enum8('Won' = 1, 'Lost' = 2)),
    settlement_trigger Nullable(Enum8('Ws' = 1, 'PeriodicRetry' = 2, 'Manual' = 3)),
    winning_token_id Nullable(String),
    accounting_status Nullable(Enum8('Pending' = 1, 'Redeemed' = 2, 'Accounted' = 3, 'Failed' = 4)),
    fee_source      Nullable(String),
    outcome         Nullable(Enum8('Rejected' = 1, 'Settled' = 2, 'Success' = 3, 'Miss' = 4, 'Failed' = 5)),
    rejection_stage Nullable(Enum8('Validation' = 1, 'Risk' = 2, 'Sizing' = 3, 'SubmitPersist' = 4, 'FactorValidation' = 5, 'Other' = 127)),
    rejection_reason Nullable(String),
    scored_snapshot_json Nullable(String) CODEC(ZSTD(3)),
    book_context_json Nullable(String) CODEC(ZSTD(3)),
    applied_factor_ids_json Nullable(String) CODEC(ZSTD(3)),
    missing_fields_json Nullable(String) CODEC(ZSTD(3)),
    detected_at     DateTime64(3, 'UTC'),
    ingestion_time  DateTime64(3, 'UTC'),
    sequence        UInt64,
    schema_version  UInt32,
    updated_at      DateTime64(3, 'UTC'),
    audit_date      Date MATERIALIZED toDate(detected_at)
)
ENGINE = ReplacingMergeTree(updated_at)
PARTITION BY toYYYYMM(audit_date)
ORDER BY (opportunity_id, stage_order, execution_id, stage_at, ingestion_time, sequence)
TTL audit_date + INTERVAL 365 DAY DELETE
SETTINGS index_granularity = 8192
