CREATE TABLE IF NOT EXISTS opportunity_detection (
    opportunity_id   String,
    market_id        String,
    event_id         String,
    token_id         String,
    token_yes        Nullable(String),
    token_no         Nullable(String),
    side             Enum8('Buy' = 1, 'Sell' = 2),
    entry_price      Decimal64(8),
    edge_bps         Decimal64(4),
    expected_net_profit_usd Decimal128(18),
    net_profit_if_correct_usd Decimal128(18),
    shares           Decimal128(18),
    total_cost_usd   Decimal128(18),
    total_fees_usd   Decimal128(18),
    resolution_prob  Decimal64(8),
    confidence       Decimal64(8),
    fill_probability Nullable(Decimal64(8)),
    score            Nullable(Int64),
    urgency_factor   Nullable(Decimal64(8)),
    category_weight  Nullable(Decimal64(8)),
    staleness_discount Nullable(Decimal64(8)),
    depth_used_pct   Decimal64(8),
    convergence_secs UInt32,
    category         Enum8('Geopolitics' = 1, 'Sports' = 2, 'Politics' = 3, 'Finance' = 4, 'Tech' = 5, 'Culture' = 6, 'Weather' = 7, 'Economics' = 8, 'Crypto' = 9, 'Other' = 10),
    price_zone       Enum8('Z95' = 1, 'Z96' = 2, 'Z97' = 3, 'Z98' = 4, 'Z99' = 5),
    duration_bucket  Enum8('Short' = 1, 'Medium' = 2, 'Long' = 3, 'VeryLong' = 4),
    calibration_sample_size UInt32,
    calibration_fallback_tier UInt8,
    calibration_alpha Decimal64(8),
    calibration_beta Decimal64(8),
    calibration_posterior_mean Decimal64(8),
    calibration_snapshot_hash Nullable(String),
    book_age_ms      Nullable(UInt64),
    yes_book_version Nullable(UInt64),
    no_book_version  Nullable(UInt64),
    control_publication_id Nullable(String),
    score_components_json String CODEC(ZSTD(3)),
    calibration_snapshot_json String CODEC(ZSTD(3)),
    book_context_json Nullable(String) CODEC(ZSTD(3)),
    applied_factors_json Nullable(String) CODEC(ZSTD(3)),
    applied_factor_ids_json Nullable(String) CODEC(ZSTD(3)),
    latency_trace_json Nullable(String) CODEC(ZSTD(3)),
    missing_fields_json Nullable(String) CODEC(ZSTD(3)),
    detected_at      DateTime64(3, 'UTC'),
    ingestion_time   DateTime64(3, 'UTC'),
    sequence         UInt64,
    schema_version   UInt32,
    detection_date   Date MATERIALIZED toDate(detected_at)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(detection_date)
ORDER BY (market_id, detected_at, ingestion_time, sequence)
TTL detection_date + INTERVAL 90 DAY DELETE
SETTINGS index_granularity = 8192
