//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "casbin_rule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub ptype: String,
    #[sea_orm(column_type = "Text")]
    pub v0: String,
    #[sea_orm(column_type = "Text")]
    pub v1: String,
    #[sea_orm(column_type = "Text")]
    pub v2: String,
    #[sea_orm(column_type = "Text")]
    pub v3: String,
    #[sea_orm(column_type = "Text")]
    pub v4: String,
    #[sea_orm(column_type = "Text")]
    pub v5: String,
}

impl ActiveModelBehavior for ActiveModel {}
