//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpCatalogSyncFailureStage, QpCatalogSyncKind, QpCatalogSyncStatus,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "catalog_sync_batch")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub catalog_sync_batch_id: Uuid,
    pub sync_kind: QpCatalogSyncKind,
    pub status: QpCatalogSyncStatus,
    pub started_at: DateTimeWithTimeZone,
    pub fetched_at: Option<DateTimeWithTimeZone>,
    pub committed_at: Option<DateTimeWithTimeZone>,
    pub event_count: i64,
    pub market_count: i64,
    pub rejected_count: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub batch_hash: Option<String>,
    pub failure_stage: Option<QpCatalogSyncFailureStage>,
    pub failure_detail: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub catalog_event_changes: HasMany<super::catalog_event_change::Entity>,
    #[sea_orm(has_many)]
    pub catalog_market_changes: HasMany<super::catalog_market_change::Entity>,
    #[sea_orm(has_many)]
    pub catalog_sync_rejections: HasMany<super::catalog_sync_rejection::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
