//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::{QpCatalogChangeType, QpCatalogTimestampQuality};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "catalog_market_change")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub market_change_id: Uuid,
    pub catalog_sync_batch_id: Uuid,
    pub event_change_id: Uuid,
    pub market_object_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub event_id: String,
    pub source_effective_at: DateTimeWithTimeZone,
    pub source_timestamp_quality: QpCatalogTimestampQuality,
    pub source_created_at: Option<DateTimeWithTimeZone>,
    pub change_type: QpCatalogChangeType,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "event_change_id",
        to = "event_change_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub catalog_event_change: BelongsTo<super::catalog_event_change::Entity>,
    #[sea_orm(
        belongs_to,
        from = "market_object_id",
        to = "market_object_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub catalog_market_object: BelongsTo<super::catalog_market_object::Entity>,
    #[sea_orm(
        belongs_to,
        from = "catalog_sync_batch_id",
        to = "catalog_sync_batch_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub catalog_sync_batch: BelongsTo<super::catalog_sync_batch::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
