//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpCatalogEntityKind, QpCatalogRejectionReason};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "catalog_sync_rejection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub catalog_sync_rejection_id: Uuid,
    pub catalog_sync_batch_id: Uuid,
    pub entity_kind: QpCatalogEntityKind,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_id: Option<String>,
    pub reason_code: QpCatalogRejectionReason,
    #[sea_orm(column_type = "Text")]
    pub detail: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub raw_payload: Option<Json>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
