//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{
    QpCatalogSyncFailureStage, QpCatalogSyncKind, QpCatalogSyncStatus,
};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "catalog_sync_batch")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub catalog_sync_batch_id: Uuid,
    pub sync_kind: QpCatalogSyncKind,
    pub status: QpCatalogSyncStatus,
    pub started_at: DateTimeWithTimeZone,
    pub fetched_at: Option<DateTimeWithTimeZone>,
    pub committed_at: Option<DateTimeWithTimeZone>,
    pub event_count: i64,
    pub market_count: i64,
    pub rejected_count: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub batch_hash: Option<String>,
    pub failure_stage: Option<QpCatalogSyncFailureStage>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_detail: Option<String>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
