//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "catalog_market_object")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub market_object_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub schema_version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub catalog_market_changes: HasMany<super::catalog_market_change::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
