//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpCatalogChangeType, QpCatalogTimestampQuality};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "catalog_event_change")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_change_id: Uuid,
    pub catalog_sync_batch_id: Uuid,
    pub event_object_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub event_id: String,
    pub source_effective_at: DateTimeWithTimeZone,
    pub source_timestamp_quality: QpCatalogTimestampQuality,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    pub change_type: QpCatalogChangeType,
}

impl ActiveModelBehavior for ActiveModel {}
