//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpDecisionPolicySnapshotSource, QpPolicyActorKind};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "decision_policy_snapshot")]
pub struct Model {
    #[sea_orm(unique)]
    pub bundle_generation: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub decision_policy_snapshot_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub snapshot_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub snapshot: Json,
    pub recommendation_policy_revision_id: Uuid,
    pub execution_risk_policy_revision_id: Uuid,
    pub model_routing_revision_id: Uuid,
    pub report_schedule_revision_id: Uuid,
    pub operational_control_revision_id: Uuid,
    pub execution_authorization_revision_id: Uuid,
    pub source: QpDecisionPolicySnapshotSource,
    pub created_by_kind: QpPolicyActorKind,
    pub created_by_user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub created_by_label: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub policy_activations: HasMany<super::policy_activation::Entity>,
    #[sea_orm(has_many)]
    pub quant_backtest_path_sets: HasMany<super::quant_backtest_path_set::Entity>,
    #[sea_orm(has_many)]
    pub quant_backtest_reports: HasMany<super::quant_backtest_report::Entity>,
    #[sea_orm(has_many)]
    pub quant_order_intents: HasMany<super::quant_order_intent::Entity>,
    #[sea_orm(has_many)]
    pub quant_report_data_quality_snapshots:
        HasMany<super::quant_report_data_quality_snapshot::Entity>,
    #[sea_orm(has_many)]
    pub quant_report_runs: HasMany<super::quant_report_run::Entity>,
    #[sea_orm(has_many)]
    pub quant_report_schedule_gaps: HasMany<super::quant_report_schedule_gap::Entity>,
    #[sea_orm(has_many)]
    pub quant_report_schedule_states: HasMany<super::quant_report_schedule_state::Entity>,
    #[sea_orm(has_many)]
    pub quant_research_jobs: HasMany<super::quant_research_job::Entity>,
    #[sea_orm(has_many)]
    pub quant_source_slices: HasMany<super::quant_source_slice::Entity>,
    #[sea_orm(has_many)]
    pub quant_training_datasets: HasMany<super::quant_training_dataset::Entity>,
    #[sea_orm(
        belongs_to,
        from = "created_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
