//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpEventStatus;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub series_slug: Option<String>,
    pub status: QpEventStatus,
    pub tags: Vec<String>,
    pub neg_risk: bool,
    pub catalog_market_ids: Vec<String>,
    pub end_date: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub markets: HasMany<super::market::Entity>,
    #[sea_orm(has_many)]
    pub quant_market_selection_members: HasMany<super::quant_market_selection_member::Entity>,
    #[sea_orm(has_many)]
    pub quant_positions: HasMany<super::quant_position::Entity>,
    #[sea_orm(has_many)]
    pub quant_recommendations: HasMany<super::quant_recommendation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
