//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpEventStatus;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub series_slug: Option<String>,
    #[sea_orm(default_expr = "Expr::cust(\"'active'::qp_event_status\")")]
    pub status: QpEventStatus,
    #[sea_orm(
        default_expr = "Expr::cust(\"'{}'::text[]\")",
        column_type = "Array(RcOrArc::new(ColumnType::Text))"
    )]
    pub tags: Vec<String>,
    #[sea_orm(default_expr = "Expr::cust(\"false\")")]
    pub neg_risk: bool,
    #[sea_orm(
        default_expr = "Expr::cust(\"'{}'::text[]\")",
        column_type = "Array(RcOrArc::new(ColumnType::Text))"
    )]
    pub catalog_market_ids: Vec<String>,
    pub end_date: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
