//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::{
    QpCatalogFilterReason, QpMarketCategory, QpMarketStatus, QpTickSize,
};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "market")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Text")]
    pub question: String,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = r#"custom("qp_market_category[]")"#)]
    pub categories: Vec<QpMarketCategory>,
    pub status: QpMarketStatus,
    #[sea_orm(column_type = r#"custom("qp_catalog_filter_reason[]")"#)]
    pub filter_reasons: Vec<QpCatalogFilterReason>,
    #[sea_orm(column_type = "Text", nullable)]
    pub outcome: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub yes_token_id: String,
    #[sea_orm(column_type = "Text")]
    pub no_token_id: String,
    pub tick_size: QpTickSize,
    pub neg_risk: bool,
    pub start_date: Option<DateTimeWithTimeZone>,
    pub end_date: Option<DateTimeWithTimeZone>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub clob_market_info_versions: HasMany<super::clob_market_info_version::Entity>,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "event_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub event: BelongsTo<super::event::Entity>,
    #[sea_orm(has_many)]
    pub quant_basis_alerts: HasMany<super::quant_basis_alert::Entity>,
    #[sea_orm(has_many)]
    pub quant_execution_orders: HasMany<super::quant_execution_order::Entity>,
    #[sea_orm(has_many)]
    pub quant_factor_values: HasMany<super::quant_factor_value::Entity>,
    #[sea_orm(has_many)]
    pub quant_feature_vectors: HasMany<super::quant_feature_vector::Entity>,
    #[sea_orm(has_many)]
    pub quant_market_linkages: HasMany<super::quant_market_linkage::Entity>,
    #[sea_orm(has_many)]
    pub quant_market_selection_members: HasMany<super::quant_market_selection_member::Entity>,
    #[sea_orm(has_many)]
    pub quant_positions: HasMany<super::quant_position::Entity>,
    #[sea_orm(has_many)]
    pub quant_recommendations: HasMany<super::quant_recommendation::Entity>,
    #[sea_orm(has_many)]
    pub quant_settlement_redeems: HasMany<super::quant_settlement_redeem::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
