//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{
    QpCatalogFilterReason, QpMarketCategory, QpMarketStatus, QpTickSize,
};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "market")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "String(StringLen::N(66))"
    )]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Text")]
    pub question: String,
    #[sea_orm(column_type = "Text")]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(default_expr = "Expr::cust(\"'{}'::qp_market_category[]\")")]
    pub categories: Vec<QpMarketCategory>,
    #[sea_orm(default_expr = "Expr::cust(\"'active'::qp_market_status\")")]
    pub status: QpMarketStatus,
    #[sea_orm(default_expr = "Expr::cust(\"'{}'::qp_catalog_filter_reason[]\")")]
    pub filter_reasons: Vec<QpCatalogFilterReason>,
    #[sea_orm(column_type = "Text", nullable)]
    pub outcome: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub yes_token_id: String,
    #[sea_orm(column_type = "Text")]
    pub no_token_id: String,
    #[sea_orm(default_expr = "Expr::cust(\"'0.01'::qp_tick_size\")")]
    pub tick_size: QpTickSize,
    #[sea_orm(default_expr = "Expr::cust(\"false\")")]
    pub neg_risk: bool,
    pub start_date: Option<DateTimeWithTimeZone>,
    pub end_date: Option<DateTimeWithTimeZone>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
