//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpMenuKind, QpRoleStatus};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "menu")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub parent_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub kind: QpMenuKind,
    #[sea_orm(column_type = "Text", nullable)]
    pub path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub component: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub permission_code: Option<String>,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub sort: i32,
    #[sea_orm(default_expr = "Expr::cust(\"false\")")]
    pub keep_alive: bool,
    #[sea_orm(default_expr = "Expr::cust(\"false\")")]
    pub hide_in_menu: bool,
    #[sea_orm(default_expr = "Expr::cust(\"false\")")]
    pub affix_tab: bool,
    #[sea_orm(default_expr = "Expr::cust(\"'enabled'::qp_role_status\")")]
    pub status: QpRoleStatus,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
