//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpOperationCategory, QpOperationHttpMethod, QpOperationOutcome, QpResourceType,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "operation_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub occurred_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub request_id: String,
    pub actor_user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub actor_username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub acting_role: Option<String>,
    pub category: QpOperationCategory,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    pub resource_type: Option<QpResourceType>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resource_id: Option<String>,
    pub http_method: QpOperationHttpMethod,
    #[sea_orm(column_type = "Text")]
    pub http_path: String,
    pub http_status: i16,
    pub outcome: QpOperationOutcome,
    pub client_ip: Option<IpNetwork>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_agent: Option<String>,
    pub latency_ms: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub detail: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub before_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub after_hash: Option<String>,
    pub governance_audit_event_id: Option<Uuid>,
    pub governance_audit_sequence: Option<i64>,
}

impl ActiveModelBehavior for ActiveModel {}
