//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{
    QpConfigResourceKind, QpPolicyActorKind, QpPolicyApprovalDecision,
};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "policy_approval")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub policy_approval_id: Uuid,
    pub policy_revision_id: Uuid,
    pub resource_kind: QpConfigResourceKind,
    #[sea_orm(column_type = "Text")]
    pub revision_hash: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub validation_subject: Option<Json>,
    pub decision: QpPolicyApprovalDecision,
    pub decided_by_kind: QpPolicyActorKind,
    pub decided_by_user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub decided_by_label: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub decided_at: DateTimeWithTimeZone,
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub policy_activations: HasMany<super::policy_activation::Entity>,
    #[sea_orm(
        belongs_to,
        from = "policy_revision_id",
        to = "policy_revision_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub policy_revision: BelongsTo<super::policy_revision::Entity>,
    #[sea_orm(
        belongs_to,
        from = "decided_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
