//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpConfigResourceKind, QpPolicyActorKind};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "policy_activation_audit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub audit_event_id: Uuid,
    #[sea_orm(unique)]
    pub policy_activation_id: Uuid,
    pub bundle_generation: i64,
    pub resource_kind: QpConfigResourceKind,
    pub policy_revision_id: Uuid,
    pub decision_policy_snapshot_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub snapshot_hash: String,
    #[sea_orm(column_type = "Text")]
    pub activation_request_hash: String,
    pub actor_kind: QpPolicyActorKind,
    pub actor_user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub actor_label: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub occurred_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "policy_activation_id",
        to = "policy_activation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub policy_activation: BelongsTo<super::policy_activation::Entity>,
    #[sea_orm(
        belongs_to,
        from = "decision_policy_snapshot_id",
        to = "decision_policy_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub decision_policy_snapshot: BelongsTo<super::decision_policy_snapshot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "actor_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
