//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{
    QpConfigResourceKind, QpPolicyActivationKind, QpPolicyActorKind,
};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "policy_activation")]
pub struct Model {
    pub bundle_generation: i64,
    pub expected_bundle_generation: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub policy_activation_id: Uuid,
    pub resource_kind: QpConfigResourceKind,
    pub policy_revision_id: Uuid,
    pub decision_policy_snapshot_id: Uuid,
    #[sea_orm(unique)]
    pub policy_approval_id: Uuid,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub activated_at: DateTimeWithTimeZone,
    pub activated_by_kind: QpPolicyActorKind,
    pub activated_by_user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub activated_by_label: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub activation_kind: QpPolicyActivationKind,
    pub expected_active_revision_id: Option<Uuid>,
    pub previous_policy_revision_id: Option<Uuid>,
    pub rollback_target_revision_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub preflight_token_hash: String,
    #[sea_orm(column_type = "Text", unique)]
    pub idempotency_key: String,
    #[sea_orm(column_type = "Text")]
    pub activation_request_hash: String,
    pub audit_event_id: Uuid,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "decision_policy_snapshot_id",
        to = "decision_policy_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub decision_policy_snapshot: BelongsTo<super::decision_policy_snapshot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "policy_approval_id",
        to = "policy_approval_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub policy_approval: BelongsTo<super::policy_approval::Entity>,
    #[sea_orm(
        belongs_to,
        from = "policy_revision_id",
        to = "policy_revision_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub policy_revision: BelongsTo<super::policy_revision::Entity>,
    #[sea_orm(
        belongs_to,
        from = "activated_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
