//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpConfigResourceKind, QpPolicyActorKind, QpPolicyRevisionStatus,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "policy_revision")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub policy_revision_id: Uuid,
    pub resource_kind: QpConfigResourceKind,
    pub schema_version: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub revision_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub document: Json,
    pub status: QpPolicyRevisionStatus,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub validation_evidence: Option<Json>,
    pub validated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub preflight_token_hash: Option<String>,
    pub preflight_expires_at: Option<DateTimeWithTimeZone>,
    pub created_by_kind: QpPolicyActorKind,
    pub created_by_user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub created_by_label: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub policy_activations: HasMany<super::policy_activation::Entity>,
    #[sea_orm(has_many)]
    pub policy_approvals: HasMany<super::policy_approval::Entity>,
    #[sea_orm(
        belongs_to,
        from = "created_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
