//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::{QpPolicyActorKind, QpProfileArtifactKind};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "policy_profile_artifact")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub profile_artifact_id: Uuid,
    pub kind: QpProfileArtifactKind,
    pub schema_version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub document: Json,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub created_by_kind: QpPolicyActorKind,
    pub created_by_user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub created_by_label: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "created_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
