//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpDataQualityStatus;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_feature_vector")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub feature_vector_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub token_id: Option<String>,
    pub decision_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary")]
    pub decision_boundary: Json,
    pub feature_schema_version: i32,
    #[sea_orm(column_type = "Text")]
    pub feature_hash: String,
    pub data_quality: QpDataQualityStatus,
    pub staleness_ms: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub source_refs: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub decision_capture: Json,
    #[sea_orm(column_type = "Text")]
    pub decision_capture_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "market_id",
        to = "market_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub market: BelongsTo<super::market::Entity>,
    #[sea_orm(has_many)]
    pub quant_factor_values: HasMany<super::quant_factor_value::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
