//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpSettlementRoute;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_settlement_external_cursor")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub settlement_external_cursor_id: Uuid,
    pub execution_account_id: Uuid,
    pub chain_id: i64,
    pub route: QpSettlementRoute,
    #[sea_orm(column_type = "Text")]
    pub target_adapter: String,
    #[sea_orm(column_type = "Text")]
    pub target_code_hash: String,
    #[sea_orm(column_type = "Text")]
    pub deployment_digest: String,
    #[sea_orm(column_type = "Text")]
    pub deployment_evidence_version: String,
    pub next_block_number: i64,
    pub last_observed_block_number: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_observed_block_hash: Option<String>,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_account_id",
        to = "execution_account_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_account: BelongsTo<super::quant_execution_account::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
