//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpExecutionOrderState, QpExitReason, QpPositionLedgerState, QpQuantRuntimeMode,
    QpRecommendationExecutionNoFillReason, QpRecommendationExecutionTerminalState,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_recommendation_execution_outcome")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_id: Uuid,
    pub order_intent_id: Uuid,
    pub entry_execution_order_id: Uuid,
    pub entry_reconciliation_id: Uuid,
    pub position_id: Option<Uuid>,
    pub execution_account_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    #[sea_orm(column_type = r#"custom("qp_quant_runtime_mode")"#)]
    pub runtime_mode: QpQuantRuntimeMode,
    pub terminal_state: QpRecommendationExecutionTerminalState,
    pub no_fill_reason: Option<QpRecommendationExecutionNoFillReason>,
    pub entry_order_state: QpExecutionOrderState,
    #[sea_orm(column_type = "Decimal(Some((38, 18)))")]
    pub requested_shares: Decimal,
    #[sea_orm(column_type = "Decimal(Some((38, 18)))")]
    pub filled_shares: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub entry_avg_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))")]
    pub entry_fee_usd: Option<Decimal>,
    pub entry_filled_at: Option<DateTimeWithTimeZone>,
    pub position_terminal_state: Option<QpPositionLedgerState>,
    pub exit_reason: Option<QpExitReason>,
    #[sea_orm(column_type = "Decimal(Some((38, 18)))")]
    pub exit_filled_shares: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub exit_avg_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))")]
    pub exit_fee_usd: Option<Decimal>,
    pub exit_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))")]
    pub settlement_payout_usd: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))")]
    pub realized_pnl_usd: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 4)))")]
    pub max_adverse_excursion_bps: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 4)))")]
    pub max_favorable_excursion_bps: Option<Decimal>,
    pub terminal_at: DateTimeWithTimeZone,
    pub source_observed_at: DateTimeWithTimeZone,
    pub available_at: DateTimeWithTimeZone,
    pub source_checkpoint_hash: String,
    pub execution_fact_hash: String,
    pub execution_fact_schema_version: i32,
    pub outcome_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "entry_execution_order_id",
        to = "execution_order_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_order: BelongsTo<super::quant_execution_order::Entity>,
    #[sea_orm(
        belongs_to,
        from = "order_intent_id",
        to = "order_intent_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_order_intent: BelongsTo<super::quant_order_intent::Entity>,
    #[sea_orm(
        belongs_to,
        from = "position_id",
        to = "position_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_position: BelongsTo<Option<super::quant_position::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "recommendation_id",
        to = "recommendation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation: BelongsTo<super::quant_recommendation::Entity>,
    #[sea_orm(
        belongs_to,
        from = "entry_reconciliation_id",
        to = "reconciliation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_reconciliation: BelongsTo<super::quant_reconciliation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
