//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{
    QpAccountSource, QpQuantRuntimeMode, QpRecommendationReportStatus, QpReportKind,
};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_recommendation_report")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_report_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub profile_id: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub profile_ref: Json,
    pub report_kind: QpReportKind,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    pub decision_at: DateTimeWithTimeZone,
    pub horizon_secs: i64,
    pub runtime_mode: QpQuantRuntimeMode,
    pub runtime_config_version_id: Uuid,
    pub model_run_id: Option<Uuid>,
    pub model_version_id: Uuid,
    pub market_selection_id: Uuid,
    pub portfolio_plan_id: Uuid,
    pub top_n: i32,
    pub status: QpRecommendationReportStatus,
    pub account_source: QpAccountSource,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))")]
    pub capital_base_usd: Decimal,
    pub account_snapshot_ref: Uuid,
    pub equity_snapshot_ref: Uuid,
    pub data_quality_snapshot_ref: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub summary_json: Json,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub successor_report_id: Option<Uuid>,
    pub superseded_at: Option<DateTimeWithTimeZone>,
    pub obsoleted_at: Option<DateTimeWithTimeZone>,
    pub valid_until: Option<DateTimeWithTimeZone>,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    pub expired_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status_reason: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
