//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpExecutionWalletKind;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_execution_account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub execution_account_id: Uuid,
    pub chain_id: i64,
    #[sea_orm(column_type = "Text")]
    pub funder_address: String,
    pub wallet_kind: QpExecutionWalletKind,
    #[sea_orm(column_type = "Text")]
    pub owner_address: String,
    #[sea_orm(column_type = "Text")]
    pub controller_address: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub wallet_factory_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub wallet_implementation_code_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub identity_digest: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_account_chain_executions: HasMany<super::quant_account_chain_execution::Entity>,
    #[sea_orm(has_many)]
    pub quant_account_recovery_incidents: HasMany<super::quant_account_recovery_incident::Entity>,
    #[sea_orm(has_many)]
    pub quant_account_snapshots: HasMany<super::quant_account_snapshot::Entity>,
    #[sea_orm(has_many)]
    pub quant_order_intents: HasMany<super::quant_order_intent::Entity>,
    #[sea_orm(has_many)]
    pub quant_clob_trade_observations: HasMany<super::quant_clob_trade_observation::Entity>,
    #[sea_orm(has_many)]
    pub quant_venue_incentive_events: HasMany<super::quant_venue_incentive_event::Entity>,
    #[sea_orm(has_many)]
    pub quant_venue_incentive_reconciliation_scans:
        HasMany<super::quant_venue_incentive_reconciliation_scan::Entity>,
    #[sea_orm(has_many)]
    pub quant_strategy_position_lots: HasMany<super::quant_strategy_position_lot::Entity>,
    #[sea_orm(has_many)]
    pub quant_settlement_redeems: HasMany<super::quant_settlement_redeem::Entity>,
    #[sea_orm(has_many)]
    pub quant_settlement_inventory_lots: HasMany<super::quant_settlement_inventory_lot::Entity>,
    #[sea_orm(has_many)]
    pub quant_settlement_governed_actions: HasMany<super::quant_settlement_governed_action::Entity>,
    #[sea_orm(has_many)]
    pub quant_settlement_external_cursors: HasMany<super::quant_settlement_external_cursor::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
