//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpVenueIncentiveKind, QpVenueIncentiveStage};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_venue_incentive_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub venue_incentive_event_id: Uuid,
    pub execution_account_id: Uuid,
    pub clob_trade_observation_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub market_id: Option<String>,
    pub kind: QpVenueIncentiveKind,
    pub stage: QpVenueIncentiveStage,
    pub program_date: Date,
    pub amount_usd: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_terms_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub source_partition: String,
    #[sea_orm(column_type = "Text", unique)]
    pub source_identity: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub transaction_hash: Option<String>,
    pub observed_at: DateTimeWithTimeZone,
    pub available_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_account_id",
        to = "execution_account_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_account: BelongsTo<super::quant_execution_account::Entity>,
    #[sea_orm(
        belongs_to,
        from = "clob_trade_observation_id",
        to = "clob_trade_observation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_clob_trade_observation:
        BelongsTo<Option<super::quant_clob_trade_observation::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
