//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpFeedbackDriftAssessment, QpFeedbackDriftKind, QpFeedbackDriftMetric,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_drift_report")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub drift_report_id: Uuid,
    pub feedback_cycle_id: Uuid,
    pub kind: QpFeedbackDriftKind,
    pub metric: QpFeedbackDriftMetric,
    pub assessment: QpFeedbackDriftAssessment,
    pub baseline_window_start: DateTimeWithTimeZone,
    pub baseline_window_end: DateTimeWithTimeZone,
    pub evaluation_window_start: DateTimeWithTimeZone,
    pub evaluation_window_end: DateTimeWithTimeZone,
    pub label_cutoff: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Decimal(Some((28, 12)))", nullable)]
    pub observed_value: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 12)))")]
    pub threshold: Decimal,
    pub sample_count: i64,
    #[sea_orm(column_type = "Text")]
    pub detail_uri: String,
    #[sea_orm(column_type = "Text")]
    pub detail_hash: String,
    pub observed_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub report_hash: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
