//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpModelGovernanceAction, QpPublicationStatus};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_model_governance_audit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub audit_id: Uuid,
    pub model_version_id: Option<Uuid>,
    pub training_dataset_id: Option<Uuid>,
    pub action: QpModelGovernanceAction,
    #[sea_orm(column_type = "Text")]
    pub actor_username: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub actor_role: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub before_status: QpPublicationStatus,
    pub after_status: QpPublicationStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub before_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub after_hash: Option<String>,
    pub quality_gate_passed: bool,
    pub rollback_target_version_id: Option<Uuid>,
    pub shadow_window_secs: Option<i64>,
    #[sea_orm(column_type = "JsonBinary")]
    pub detail_json: Json,
    pub audit_event_id: Option<Uuid>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
