//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpExecutionOrderPhase, QpFeeLiquidityRole, QpSide};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_execution_fill")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub execution_fill_id: Uuid,
    pub execution_order_id: Uuid,
    pub order_intent_id: Uuid,
    pub execution_account_id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub venue_trade_id: String,
    pub venue_bucket_index: i32,
    #[sea_orm(column_type = "Text")]
    pub venue_order_id: String,
    pub order_phase: QpExecutionOrderPhase,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    pub side: QpSide,
    pub liquidity_role: QpFeeLiquidityRole,
    pub shares: Decimal,
    pub price: Decimal,
    pub principal_usd: Decimal,
    pub matched_at: DateTimeWithTimeZone,
    pub available_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_order_id",
        to = "execution_order_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_order: BelongsTo<super::quant_execution_order::Entity>,
    #[sea_orm(
        belongs_to,
        from = "order_intent_id",
        to = "order_intent_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_order_intent: BelongsTo<super::quant_order_intent::Entity>,
    #[sea_orm(
        belongs_to,
        from = "execution_account_id",
        to = "execution_account_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_account: BelongsTo<super::quant_execution_account::Entity>,
    #[sea_orm(has_many)]
    pub quant_execution_fee_measurements: HasMany<super::quant_execution_fee_measurement::Entity>,
    #[sea_orm(has_many)]
    pub quant_venue_incentive_events: HasMany<super::quant_venue_incentive_event::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
