//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpOutcomeSide;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_settlement_redeem_lot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub settlement_redeem_lot_id: Uuid,
    pub settlement_redeem_id: Uuid,
    pub position_id: Uuid,
    pub order_intent_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    pub side: QpOutcomeSide,
    #[sea_orm(column_type = "Decimal(Some((38, 18)))")]
    pub shares_redeemed: Decimal,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))")]
    pub cost_basis_usd: Decimal,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))")]
    pub payout_usd: Decimal,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))")]
    pub realized_pnl_usd: Decimal,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
