//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpExchangeHistoryChunkStatus, QpExchangeHistoryContinuityBasis, QpExchangeHistoryFrontier,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_exchange_history_chunk")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chunk_id: Uuid,
    pub frontier: QpExchangeHistoryFrontier,
    pub from_block: i64,
    pub to_block: i64,
    pub status: QpExchangeHistoryChunkStatus,
    pub attempt_count: i32,
    pub hypersync_count: Option<i64>,
    pub attestor_count: Option<i64>,
    pub hypersync_digest: Option<String>,
    pub attestor_digest: Option<String>,
    pub first_block_hash: Option<String>,
    pub last_block_hash: Option<String>,
    pub archive_height: Option<i64>,
    pub continuity_basis: Option<QpExchangeHistoryContinuityBasis>,
    pub continuity_block: Option<i64>,
    pub continuity_hash: Option<String>,
    pub effective_through_at: Option<DateTimeWithTimeZone>,
    pub state_revision: Option<i64>,
    pub accepted_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
