//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpFeedbackTriggerFamily;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_feedback_trigger_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub feedback_trigger_event_id: Uuid,
    pub feedback_cycle_id: Uuid,
    pub trigger_family: QpFeedbackTriggerFamily,
    pub actor_user_id: Option<Uuid>,
    pub actor_label: String,
    pub actor_role: Option<String>,
    pub reason_code: String,
    #[sea_orm(column_type = "Text")]
    pub event_hash: String,
    pub occurred_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "feedback_cycle_id",
        to = "feedback_cycle_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_feedback_cycle: BelongsTo<super::quant_feedback_cycle::Entity>,
    #[sea_orm(
        belongs_to,
        from = "actor_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
