//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpAccountSource, QpQuantRuntimeMode, QpRecommendationReportStatus, QpReportKind,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_recommendation_report")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_report_id: Uuid,
    #[sea_orm(unique)]
    pub report_run_id: Uuid,
    pub report_kind: QpReportKind,
    pub decision_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = r#"custom("qp_quant_runtime_mode")"#)]
    pub runtime_mode: QpQuantRuntimeMode,
    pub decision_policy_snapshot_id: Uuid,
    pub market_selection_id: Uuid,
    pub portfolio_plan_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub represented_routes_json: Json,
    pub scenario_artifact_id: Option<Uuid>,
    pub scenario_artifact_hash: Option<String>,
    pub top_n: i32,
    pub status: QpRecommendationReportStatus,
    pub account_source: QpAccountSource,
    pub capital_base_usd: Decimal,
    pub account_snapshot_ref: Uuid,
    pub equity_snapshot_ref: Uuid,
    pub data_quality_snapshot_ref: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub summary_json: Json,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub successor_report_id: Option<Uuid>,
    pub superseded_at: Option<DateTimeWithTimeZone>,
    pub obsoleted_at: Option<DateTimeWithTimeZone>,
    pub valid_until: Option<DateTimeWithTimeZone>,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub status_reason: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "successor_report_id",
        to = "recommendation_report_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation_report: BelongsTo<Option<Entity>>,
    #[sea_orm(
        belongs_to,
        from = "report_run_id",
        to = "report_run_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_report_run: BelongsTo<super::quant_report_run::Entity>,
    #[sea_orm(
        belongs_to,
        from = "decision_policy_snapshot_id",
        to = "decision_policy_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub decision_policy_snapshot: BelongsTo<super::decision_policy_snapshot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "market_selection_id",
        to = "market_selection_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_market_selection: BelongsTo<super::quant_market_selection::Entity>,
    #[sea_orm(
        belongs_to,
        from = "portfolio_plan_id",
        to = "portfolio_plan_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_portfolio_plan: BelongsTo<super::quant_portfolio_plan::Entity>,
    #[sea_orm(
        belongs_to,
        from = "account_snapshot_ref",
        to = "account_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_account_snapshot: BelongsTo<super::quant_account_snapshot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "equity_snapshot_ref",
        to = "equity_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_equity_snapshot: BelongsTo<super::quant_equity_snapshot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "data_quality_snapshot_ref",
        to = "report_data_quality_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_report_data_quality_snapshot:
        BelongsTo<super::quant_report_data_quality_snapshot::Entity>,
    #[sea_orm(has_many)]
    pub quant_recommendations: HasMany<super::quant_recommendation::Entity>,
    #[sea_orm(has_one)]
    pub quant_report_fact_delivery: HasOne<super::quant_report_fact_delivery::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
