//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::{QpExecutionWalletKind, QpSettlementRedeemState};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_settlement_redeem")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub settlement_redeem_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    pub funder_address: String,
    pub wallet_kind: QpExecutionWalletKind,
    pub state: QpSettlementRedeemState,
    pub tx_hash: Option<String>,
    pub index_sets_json: Json,
    pub payout_vector_json: Json,
    pub balance_before_json: Json,
    pub balance_after_json: Option<Json>,
    pub payout_usd: Decimal,
    pub gas_fee_pol: Option<Decimal>,
    pub attempt_count: i32,
    pub next_attempt_at: Option<DateTimeWithTimeZone>,
    pub last_error: Option<String>,
    pub submitted_at: Option<DateTimeWithTimeZone>,
    pub confirmed_at: Option<DateTimeWithTimeZone>,
    pub failed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "market_id",
        to = "market_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub market: BelongsTo<super::market::Entity>,
    #[sea_orm(has_many)]
    pub quant_settlement_redeem_lots: HasMany<super::quant_settlement_redeem_lot::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
