//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpOutcomeSide, QpRecommendationStatus};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_recommendation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub profile_ref: Json,
    pub recommendation_report_id: Uuid,
    pub rank: i32,
    #[sea_orm(column_type = "String(StringLen::N(66))")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    pub outcome_side: QpOutcomeSide,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub composite_score: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub risk_adjusted_score: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub confidence: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 4)))")]
    pub expected_return_bps: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 4)))")]
    pub downside_bps: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub identity: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub market_context: Json,
    pub rank_before_portfolio: i32,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub liquidity_score: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub data_quality_score: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub model_score_percentile: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub trade_plan: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub factor_breakdown: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub evidence_refs: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub execution_eligibility: Json,
    pub valid_from: DateTimeWithTimeZone,
    pub valid_until: DateTimeWithTimeZone,
    pub status: QpRecommendationStatus,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
