//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_entry_condition_artifact")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub artifact_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub schema_version: i32,
    pub evaluator_version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload_json: Json,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_entry_condition_instances: HasMany<super::quant_entry_condition_instance::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
