//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_trade_policy_validation_row")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub validation_run_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub row_ordinal: i64,
    pub evidence_kind: String,
    pub record_key: String,
    pub example_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub market_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub token_id: Option<String>,
    pub decision_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub expected_row_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub actual_row_hash: Option<String>,
    pub passed: bool,
    pub diagnostic_kind: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub detail: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub row_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "validation_run_id",
        to = "validation_run_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_trade_policy_validation: BelongsTo<super::quant_trade_policy_validation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
