//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::{quant_feedback_stage_event, quant_feedback_trigger_event};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_feedback_event_outbox")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub revision: i64,
    #[sea_orm(unique)]
    pub feedback_stage_event_id: Option<Uuid>,
    #[sea_orm(unique)]
    pub feedback_trigger_event_id: Option<Uuid>,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub publish_attempts: i32,
    pub claim_owner: Option<Uuid>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub last_error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,

    #[sea_orm(
        belongs_to,
        relation_enum = "StageEvent",
        from = "feedback_stage_event_id",
        to = "feedback_stage_event_id"
    )]
    pub stage_event: BelongsTo<Option<quant_feedback_stage_event::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "TriggerEvent",
        from = "feedback_trigger_event_id",
        to = "feedback_trigger_event_id"
    )]
    pub trigger_event: BelongsTo<Option<quant_feedback_trigger_event::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
