//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_resolution_observation_inbox")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub resolution_observation_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub source_checkpoint_hash: String,
    #[sea_orm(column_type = "Text")]
    pub source_id: String,
    #[sea_orm(column_type = "Text")]
    pub instrument_key: String,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub denominator: String,
    #[sea_orm(column_type = "Text")]
    pub yes_numerator: String,
    #[sea_orm(column_type = "Text")]
    pub no_numerator: String,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub yes_payout_ratio: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub no_payout_ratio: Decimal,
    #[sea_orm(column_type = "Text")]
    pub oracle: String,
    #[sea_orm(column_type = "Text")]
    pub question_id: String,
    #[sea_orm(column_type = "Text")]
    pub transaction_hash: String,
    pub block_number: i64,
    #[sea_orm(column_type = "Text")]
    pub block_hash: String,
    pub log_index: i64,
    pub resolved_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub raw_payload_hash: String,
    #[sea_orm(column_type = "Text")]
    pub raw_uri: String,
    #[sea_orm(column_type = "Text")]
    pub provider_revision: String,
    pub available_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_one)]
    pub quant_resolution_observation_projection:
        HasOne<super::quant_resolution_observation_projection::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
