//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpFeedbackCycleStatus, QpFeedbackDecision, QpFeedbackTriggerFamily,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_feedback_cycle")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub feedback_cycle_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub idempotency_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub idempotency_key: Json,
    pub trigger_family: QpFeedbackTriggerFamily,
    #[sea_orm(column_type = "JsonBinary")]
    pub profile_ref: Json,
    #[sea_orm(column_type = "Text")]
    pub research_profile_artifact_id: String,
    #[sea_orm(column_type = "Text")]
    pub profile_hash: String,
    #[sea_orm(column_type = "Text")]
    pub feedback_policy_hash: String,
    pub label_cutoff: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary")]
    pub capability_registry_hashes: Json,
    pub champion_model_version_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub champion_serving_contract_hash: String,
    #[sea_orm(column_type = "Text")]
    pub candidate_family_hash: String,
    pub status: QpFeedbackCycleStatus,
    pub decision: Option<QpFeedbackDecision>,
    pub terminal_reason_code: Option<String>,
    pub generation: i64,
    pub lease_owner: Option<Uuid>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub cancel_requested_at: Option<DateTimeWithTimeZone>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
