//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpShadowBindingStatus;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_model_route_shadow_binding")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub binding_id: Uuid,
    #[sea_orm(unique)]
    pub feedback_cycle_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub route: Json,
    pub status: QpShadowBindingStatus,
    pub lifecycle_generation: i64,
    pub binding_generation: i64,
    pub champion_model_version_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub champion_serving_contract_hash: String,
    pub candidate_model_version_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub candidate_serving_contract_hash: String,
    #[sea_orm(column_type = "Text")]
    pub candidate_recipe_hash: String,
    pub candidate_manifest_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub candidate_manifest_hash: String,
    pub reserved_model_bytes: i64,
    pub committed_policy_generation: i64,
    #[sea_orm(unique)]
    pub policy_activation_id: Uuid,
    #[sea_orm(unique)]
    pub audit_event_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub receipt_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub receipt: Json,
    pub bound_at: DateTimeWithTimeZone,
    pub terminated_at: Option<DateTimeWithTimeZone>,
    pub termination_policy_activation_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub termination_request_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub termination_reason_code: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub termination_note: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub termination_actor_role: Option<String>,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "feedback_cycle_id",
        to = "feedback_cycle_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub feedback_cycle: BelongsTo<super::quant_feedback_cycle::Entity>,
    #[sea_orm(
        belongs_to,
        from = "policy_activation_id",
        to = "policy_activation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub policy_activation: BelongsTo<super::policy_activation::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "TerminationPolicyActivation",
        from = "termination_policy_activation_id",
        to = "policy_activation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub termination_policy_activation: BelongsTo<Option<super::policy_activation::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ChampionModelVersion",
        from = "champion_model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub champion_model_version: BelongsTo<super::quant_model_version::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "CandidateModelVersion",
        from = "candidate_model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub candidate_model_version: BelongsTo<super::quant_model_version::Entity>,
    #[sea_orm(
        belongs_to,
        from = "candidate_manifest_id",
        to = "manifest_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub candidate_manifest: BelongsTo<super::quant_model_candidate_manifest::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
