//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpReconciliationResult;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_reconciliation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub reconciliation_id: Uuid,
    pub execution_order_id: Uuid,
    pub order_intent_id: Uuid,
    pub result: QpReconciliationResult,
    #[sea_orm(column_type = "JsonBinary")]
    pub evidence_json: Json,
    pub venue_filled_shares: Option<Decimal>,
    pub venue_avg_price: Option<Decimal>,
    pub expected_cash_delta_usd: Option<Decimal>,
    pub venue_cash_delta_usd: Option<Decimal>,
    pub realized_pnl_usd: Option<Decimal>,
    pub expected_fee_usd: Option<Decimal>,
    pub observed_fee_usd: Option<Decimal>,
    pub fee_delta_usd: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolved_by: Option<String>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_order_id",
        to = "execution_order_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_order: BelongsTo<super::quant_execution_order::Entity>,
    #[sea_orm(
        belongs_to,
        from = "order_intent_id",
        to = "order_intent_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_order_intent: BelongsTo<super::quant_order_intent::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
