//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpCalibrationKind;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "public",
    table_name = "quant_calibration_artifact_publication"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub publication_id: Uuid,
    pub artifact_id: Uuid,
    pub kind: QpCalibrationKind,
    pub published_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
