//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpResolutionProjectionErrorCode, QpResolutionProjectionStatus, QpResolutionRemediationAction,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_resolution_projection_remediation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub remediation_id: Uuid,
    pub resolution_observation_id: Uuid,
    pub expected_revision: i64,
    pub committed_revision: i64,
    pub action: QpResolutionRemediationAction,
    pub prior_status: QpResolutionProjectionStatus,
    pub prior_error_code: QpResolutionProjectionErrorCode,
    #[sea_orm(column_type = "Text")]
    pub prior_error: String,
    pub resulting_status: QpResolutionProjectionStatus,
    #[sea_orm(unique)]
    pub idempotency_key: String,
    #[sea_orm(column_type = "Text", unique)]
    pub request_hash: String,
    pub reason_code: String,
    #[sea_orm(column_type = "Text")]
    pub operator_note: String,
    pub actor_user_id: Uuid,
    pub actor_username: String,
    pub actor_role: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "resolution_observation_id",
        to = "resolution_observation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_resolution_observation_projection:
        BelongsTo<super::quant_resolution_observation_projection::Entity>,
    #[sea_orm(
        belongs_to,
        from = "actor_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: BelongsTo<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
