//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpEntryConditionState;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_entry_condition_instance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub condition_instance_id: Uuid,
    pub recommendation_id: Uuid,
    pub artifact_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub artifact_hash: Option<String>,
    pub state: QpEntryConditionState,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub truth_json: Option<Json>,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub revision: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub evaluation_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub input_fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub continuity_hash: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    #[sea_orm(default_expr = "Expr::cust(\"'{\\\"crypto\\\": []}'::jsonb\")")]
    pub fold_state_json: Json,
    pub confirmation_started_at: Option<DateTimeWithTimeZone>,
    pub last_evaluated_at: Option<DateTimeWithTimeZone>,
    pub next_evaluation_at: Option<DateTimeWithTimeZone>,
    pub expires_at: DateTimeWithTimeZone,
    pub lease_owner: Option<Uuid>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub lease_epoch: i64,
    pub claimed_by_intent_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub claim_admission_state_version: Option<String>,
    pub consumed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
