//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::{QpTradeTapeBlockCursorStatus, QpTradeTapeSourceKind};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_trade_tape_block_cursor")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source: QpTradeTapeSourceKind,
    #[sea_orm(primary_key, auto_increment = false)]
    pub contract_address: String,
    pub last_finalized_block: i64,
    pub last_log_index: i32,
    pub head_lag_blocks: i64,
    pub status: QpTradeTapeBlockCursorStatus,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
