//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::QpParitySubjectKind;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_feature_parity_subject")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub parity_subject_id: Uuid,
    pub run_id: Uuid,
    pub subject_kind: QpParitySubjectKind,
    pub model_run_id: Option<Uuid>,
    pub recommendation_report_id: Option<Uuid>,
    pub model_version_id: Option<Uuid>,
    pub training_dataset_id: Option<Uuid>,
    pub market_selection_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub subject_generation: String,
    pub decision_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub selection_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_feature_parity_candidates: HasMany<super::quant_feature_parity_candidate::Entity>,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "run_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_feature_parity_run: BelongsTo<super::quant_feature_parity_run::Entity>,
    #[sea_orm(
        belongs_to,
        from = "market_selection_id",
        to = "market_selection_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_market_selection: BelongsTo<Option<super::quant_market_selection::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "model_run_id",
        to = "model_run_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_run: BelongsTo<Option<super::quant_model_run::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_version: BelongsTo<Option<super::quant_model_version::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "recommendation_report_id",
        to = "recommendation_report_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation_report: BelongsTo<Option<super::quant_recommendation_report::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "training_dataset_id",
        to = "training_dataset_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_training_dataset: BelongsTo<Option<super::quant_training_dataset::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
