//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_trade_tape_block_cursor")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub source: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub contract_address: String,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub last_finalized_block: i64,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub last_log_index: i32,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub head_lag_blocks: i64,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
