//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpMarketCategory, QpMarketStatus};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_market_selection_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub market_selection_id: Uuid,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "String(StringLen::N(66))"
    )]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Custom(QpMarketCategory::name())")]
    pub category: QpMarketCategory,
    pub status: QpMarketStatus,
    #[sea_orm(column_type = "Text")]
    pub primary_token_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub secondary_token_id: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))", nullable)]
    pub liquidity_usd: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))", nullable)]
    pub volume_24h_usd: Option<Decimal>,
}

impl ActiveModelBehavior for ActiveModel {}
