//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::{
    quant_exchange_history_chunk, sea_orm_active_enums::QpExchangeHistoryQuarantineReason,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_exchange_history_quarantine")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub quarantine_id: Uuid,
    pub chunk_id: Uuid,
    pub reason: QpExchangeHistoryQuarantineReason,
    pub evidence_hash: String,
    pub detail: String,
    pub quarantined_at: DateTimeWithTimeZone,

    #[sea_orm(
        belongs_to,
        relation_enum = "Chunk",
        from = "chunk_id",
        to = "chunk_id"
    )]
    pub chunk: BelongsTo<quant_exchange_history_chunk::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
