//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::QpAccountSource;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_account_snapshot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_snapshot_id: Uuid,
    pub as_of: DateTimeWithTimeZone,
    pub source: QpAccountSource,
    pub venue_net_liquidation_usd: Decimal,
    pub capital_base_usd: Decimal,
    pub available_usd: Decimal,
    pub reserved_usd: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub positions_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub exposures_json: Json,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_equity_snapshots: HasMany<super::quant_equity_snapshot::Entity>,
    #[sea_orm(has_many)]
    pub quant_recommendation_reports: HasMany<super::quant_recommendation_report::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
