//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_basis_alert")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub alert_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    pub instrument_key: String,
    pub oracle_instrument_key: String,
    pub basis_bps: Decimal,
    pub threshold_bps: Decimal,
    pub as_of: DateTimeWithTimeZone,
    pub acknowledged: bool,
    pub acknowledged_at: Option<DateTimeWithTimeZone>,
    pub acknowledged_by: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "market_id",
        to = "market_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub market: BelongsTo<super::market::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
