//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::QpReportFactDeliveryStatus;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_report_fact_delivery")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_report_id: Uuid,
    pub status: QpReportFactDeliveryStatus,
    #[sea_orm(column_type = "Text")]
    pub bundle_uri: String,
    #[sea_orm(column_type = "Text")]
    pub bundle_hash: String,
    pub bundle_bytes: i64,
    pub recommendation_row_count: i64,
    #[sea_orm(column_type = "Text")]
    pub recommendation_row_chain_hash: String,
    pub funnel_row_count: i64,
    #[sea_orm(column_type = "Text")]
    pub funnel_row_chain_hash: String,
    pub attempt_count: i32,
    pub claim_owner: Option<Uuid>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub next_attempt_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub verified_at: Option<DateTimeWithTimeZone>,
    pub announced_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "recommendation_report_id",
        to = "recommendation_report_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation_report: BelongsTo<super::quant_recommendation_report::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
