//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpModelFamily;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_model_spec")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_spec_id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    pub model_family: QpModelFamily,
    pub prediction_horizon_secs: i64,
    pub feature_schema_version: i32,
    pub label_schema_version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub thesis: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub input_contract: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub training_contract: Json,
    pub definition_hash: String,
    pub created_by_user_id: Option<Uuid>,
    pub created_by_label: String,
    pub created_by_role: Option<String>,
    pub reason: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_model_versions: HasMany<super::quant_model_version::Entity>,
    #[sea_orm(has_many)]
    pub quant_research_jobs: HasMany<super::quant_research_job::Entity>,
    #[sea_orm(has_many)]
    pub quant_training_datasets: HasMany<super::quant_training_dataset::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
