//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{
    QpReportRunStatus, QpReportRunTerminalReason, QpReportTriggerKind,
};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_report_run")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub report_run_id: Uuid,
    pub trigger_kind: QpReportTriggerKind,
    #[sea_orm(column_type = "Text")]
    pub trigger_key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub schedule_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub request_id: Option<String>,
    pub retry_of_run_id: Option<Uuid>,
    pub scheduled_for: Option<DateTimeWithTimeZone>,
    pub requested_at: DateTimeWithTimeZone,
    pub status: QpReportRunStatus,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub decision_at: Option<DateTimeWithTimeZone>,
    pub heartbeat_at: Option<DateTimeWithTimeZone>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub lease_owner: Option<Uuid>,
    pub runtime_config_version_id: Option<Uuid>,
    pub top_n: Option<i32>,
    pub knowledge_lag_secs: Option<i64>,
    pub output_report_id: Option<Uuid>,
    pub terminal_reason: Option<QpReportRunTerminalReason>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_summary: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
