//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::QpCalibrationKind;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_calibration_artifact")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub artifact_id: Uuid,
    pub kind: QpCalibrationKind,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub fit_window_start: DateTimeWithTimeZone,
    pub fit_window_end: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub calibration_split_hash: String,
    pub sample_count: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    pub active: bool,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_calibration_artifact_publications:
        HasMany<super::quant_calibration_artifact_publication::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
