//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpEntryConditionAuditAction, QpEntryConditionState};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_entry_condition_audit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub audit_id: Uuid,
    pub condition_instance_id: Uuid,
    pub revision: i64,
    pub action: QpEntryConditionAuditAction,
    pub from_state: Option<QpEntryConditionState>,
    pub to_state: QpEntryConditionState,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub truth_json: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub evaluation_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub input_fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub continuity_hash: Option<String>,
    pub lease_epoch: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub detail: Option<String>,
    pub occurred_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
