//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpTradePolicyGovernanceAction, QpTradePolicyStatus};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_trade_policy_governance_audit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub audit_id: Uuid,
    pub artifact_id: Uuid,
    pub action: QpTradePolicyGovernanceAction,
    pub from_status: QpTradePolicyStatus,
    pub to_status: QpTradePolicyStatus,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub actor_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
