//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_basis_alert")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub alert_id: Uuid,
    #[sea_orm(column_type = "String(StringLen::N(66))")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub instrument_key: String,
    #[sea_orm(column_type = "Text")]
    pub oracle_instrument_key: String,
    #[sea_orm(column_type = "Decimal(Some((10, 4)))")]
    pub basis_bps: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 4)))")]
    pub threshold_bps: Decimal,
    pub as_of: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"false\")")]
    pub acknowledged: bool,
    pub acknowledged_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub acknowledged_by: Option<String>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
