//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpFeatureParityLatchState, QpFeatureParityStateTransition};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_feature_parity_state")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub state_id: Uuid,
    pub state: QpFeatureParityLatchState,
    pub transition: QpFeatureParityStateTransition,
    pub cause_run_id: Option<Uuid>,
    pub recovery_run_id: Option<Uuid>,
    pub previous_state_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub actor: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub acting_role: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
