//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpFactorDefinitionScope, QpFactorFamily, QpPublicationStatus};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_factor_definition")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub factor_definition_id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub definition_hash: String,
    #[sea_orm(column_type = "Text")]
    pub feature_contract_hash: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub factor_family: QpFactorFamily,
    pub scope: QpFactorDefinitionScope,
    pub input_schema_version: i32,
    pub output_schema_version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub definition: Json,
    pub status: QpPublicationStatus,
    pub created_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_factor_values: HasMany<super::quant_factor_value::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
