//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpFeatureParityRunKind, QpFeatureParityRunStatus};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_feature_parity_run")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub run_id: Uuid,
    pub kind: QpFeatureParityRunKind,
    #[sea_orm(default_expr = "Expr::cust(\"'queued'::qp_feature_parity_run_status\")")]
    pub status: QpFeatureParityRunStatus,
    pub window_start: DateTimeWithTimeZone,
    pub window_end: DateTimeWithTimeZone,
    pub report_id: Option<Uuid>,
    pub model_version_id: Option<Uuid>,
    pub training_dataset_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub triggered_by: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub requested_by: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub acting_role: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub total_count: i64,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub compared_count: i64,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub matched_count: i64,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub mismatched_count: i64,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub pending_materialization_count: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub feature_contract_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transform_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_detail: Option<String>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub pending_since: Option<DateTimeWithTimeZone>,
    pub containment_completed_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
