//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpCapitalAllocationState;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_capital_allocation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub capital_allocation_id: Uuid,
    pub order_intent_id: Uuid,
    pub recommendation_id: Uuid,
    pub state: QpCapitalAllocationState,
    pub planned_usd: Decimal,
    pub allocated_usd: Decimal,
    pub locked_usd: Decimal,
    pub spent_usd: Decimal,
    pub released_usd: Decimal,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "order_intent_id",
        to = "order_intent_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_order_intent: BelongsTo<super::quant_order_intent::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recommendation_id",
        to = "recommendation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation: BelongsTo<super::quant_recommendation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
