//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpResearchJobKind, QpResearchJobStatus};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_research_job")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub job_id: Uuid,
    pub kind: QpResearchJobKind,
    #[sea_orm(default_expr = "Expr::cust(\"'queued'::qp_research_job_status\")")]
    pub status: QpResearchJobStatus,
    pub model_spec_id: Option<Uuid>,
    pub runtime_config_version_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary")]
    pub params_json: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub progress_json: Option<Json>,
    pub result_ref: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub error_json: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub coverage_json: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub requested_by: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub acting_role: String,
    pub parent_job_id: Option<Uuid>,
    #[sea_orm(default_expr = "Expr::cust(\"0\")")]
    pub recovery_attempt: i32,
    pub max_recovery_attempts: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub lease_owner: Option<String>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub heartbeat_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
