//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpResearchJobKind, QpResearchJobResultKind, QpResearchJobStatus,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_research_job")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub job_id: Uuid,
    pub kind: QpResearchJobKind,
    pub status: QpResearchJobStatus,
    pub model_spec_id: Option<Uuid>,
    pub decision_policy_snapshot_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary")]
    pub params_json: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub progress_json: Option<Json>,
    pub result_kind: Option<QpResearchJobResultKind>,
    pub result_ref: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub error_json: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub coverage_json: Option<Json>,
    pub requested_by: Option<String>,
    pub acting_role: String,
    pub parent_job_id: Option<Uuid>,
    pub recovery_attempt: i32,
    pub max_recovery_attempts: i32,
    pub lease_owner: Option<Uuid>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub heartbeat_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "decision_policy_snapshot_id",
        to = "decision_policy_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub decision_policy_snapshot: BelongsTo<Option<super::decision_policy_snapshot::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "model_spec_id",
        to = "model_spec_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_spec: BelongsTo<Option<super::quant_model_spec::Entity>>,
    #[sea_orm(has_many)]
    pub quant_trade_policy_trial_attempts: HasMany<super::quant_trade_policy_trial_attempt::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
