//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_shadow_comparison")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub shadow_comparison_id: Uuid,
    pub active_model_version_id: Uuid,
    pub shadow_model_version_id: Uuid,
    pub decision_at: DateTimeWithTimeZone,
    pub topn_overlap: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub rank_delta_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub score_delta_json: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub matured_outcome_json: Option<Json>,
    pub hard_divergence: bool,
    #[sea_orm(column_type = "Text")]
    pub comparison_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        relation_enum = "QuantModelVersion2",
        from = "active_model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_version_2: BelongsTo<super::quant_model_version::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "QuantModelVersion1",
        from = "shadow_model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_version_1: BelongsTo<super::quant_model_version::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
