//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpLinkageSourceRole;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_market_linkage_source")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub linkage_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role: QpLinkageSourceRole,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub source_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub instrument_key: String,
    #[sea_orm(column_type = "Text")]
    pub binding_hash: String,
    pub available_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "linkage_id",
        to = "linkage_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_market_linkage: BelongsTo<super::quant_market_linkage::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
