//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpDomainFamily, QpDomainSourceExpectationStatus};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_domain_source_expectation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub expectation_id: Uuid,
    pub family: QpDomainFamily,
    #[sea_orm(column_type = "Text", unique_key = "source_instrument")]
    pub source_id: String,
    #[sea_orm(column_type = "Text", unique_key = "source_instrument")]
    pub instrument_key: String,
    #[sea_orm(column_type = "Text")]
    pub capability_registry_hash: String,
    #[sea_orm(column_type = "Text")]
    pub binding_hash: String,
    pub required: bool,
    pub credential_required: bool,
    pub freshness_secs: i64,
    pub affected_market_ids: Vec<String>,
    pub affected_profile_ids: Vec<String>,
    pub status: QpDomainSourceExpectationStatus,
    pub status_reason: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
