//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_model_comparison_report")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub comparison_report_id: Uuid,
    pub baseline_model_version_id: Uuid,
    pub candidate_model_version_id: Uuid,
    pub baseline_report_id: Uuid,
    pub candidate_report_id: Uuid,
    pub model_run_id: Uuid,
    pub rank_ic_delta: Decimal,
    pub hit_rate_delta: Decimal,
    pub realized_pnl_delta: Decimal,
    pub score_correlation: Decimal,
    pub side_disagreement_rate: Decimal,
    pub common_samples: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub category_breakdown_diff: Json,
    #[sea_orm(column_type = "Text")]
    pub comparison_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        relation_enum = "QuantBacktestReport2",
        from = "baseline_report_id",
        to = "backtest_report_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_backtest_report_2: BelongsTo<super::quant_backtest_report::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "QuantBacktestReport1",
        from = "candidate_report_id",
        to = "backtest_report_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_backtest_report_1: BelongsTo<super::quant_backtest_report::Entity>,
    #[sea_orm(
        belongs_to,
        from = "model_run_id",
        to = "model_run_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_run: BelongsTo<super::quant_model_run::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "QuantModelVersion2",
        from = "baseline_model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_version_2: BelongsTo<super::quant_model_version::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "QuantModelVersion1",
        from = "candidate_model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_version_1: BelongsTo<super::quant_model_version::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
