//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpFreshBootEventKind, QpFreshBootStage, QpFreshBootStatus};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_fresh_boot_run_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: Uuid,
    pub run_id: Uuid,
    pub event_sequence: i64,
    pub from_stage: QpFreshBootStage,
    pub to_stage: QpFreshBootStage,
    pub from_status: QpFreshBootStatus,
    pub to_status: QpFreshBootStatus,
    pub event_kind: QpFreshBootEventKind,
    pub research_job_id: Option<Uuid>,
    pub result_ref: Option<Uuid>,
    pub evidence_hash: Option<String>,
    pub attempt: i32,
    pub actor: String,
    pub detail: Option<String>,
    pub occurred_at: DateTimeWithTimeZone,
    pub event_hash: String,
}

impl ActiveModelBehavior for ActiveModel {}
