//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpModelFamily, QpPublicationStatus};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_model_spec")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_spec_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub model_family: QpModelFamily,
    pub prediction_horizon_secs: i64,
    pub feature_schema_version: i32,
    pub label_schema_version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub spec_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub input_contract: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub training_contract: Json,
    pub status: QpPublicationStatus,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
