//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpResolutionProjectionErrorCode, QpResolutionProjectionStatus};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_resolution_observation_projection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub resolution_observation_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub source_checkpoint_hash: String,
    pub status: QpResolutionProjectionStatus,
    pub revision: i64,
    pub attempt_count: i32,
    pub claim_owner: Option<Uuid>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub next_attempt_at: Option<DateTimeWithTimeZone>,
    pub last_error_code: Option<QpResolutionProjectionErrorCode>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub canonical_fact_hash: Option<String>,
    pub verified_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "resolution_observation_id",
        to = "resolution_observation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_resolution_observation_inbox:
        BelongsTo<super::quant_resolution_observation_inbox::Entity>,
    #[sea_orm(has_many)]
    pub quant_resolution_projection_remediation:
        HasMany<super::quant_resolution_projection_remediation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
