//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_exchange_history_plan")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub plan_id: Uuid,
    #[sea_orm(unique)]
    pub chain_id: i64,
    pub policy_hash: String,
    pub bootstrap_profile_set_hash: String,
    pub finalized_anchor_block: i64,
    pub finalized_anchor_hash: String,
    pub finalized_anchor_timestamp: i64,
    pub activation_from_block: i64,
    pub activation_through_block: i64,
    pub crypto_required_from_block: i64,
    pub weather_required_from_block: i64,
    pub retention_from_block: i64,
    pub retention_through_block: i64,
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
