//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpMarketCategory, QpModelVersionDerivationKind};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_model_version")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_version_id: Uuid,
    pub model_spec_id: Uuid,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub artifact_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub serving_contract: Json,
    pub serving_contract_hash: Vec<u8>,
    #[sea_orm(column_type = r#"custom("qp_market_category")"#)]
    pub category_scope: Option<QpMarketCategory>,
    #[sea_orm(column_type = "Text")]
    pub research_profile_artifact_id: String,
    pub training_dataset_id: Option<Uuid>,
    pub trade_policy_artifact_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub trade_policy_hash: Option<String>,
    pub derivation_kind: QpModelVersionDerivationKind,
    pub parent_model_version_id: Option<Uuid>,
    pub calibration_artifact_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub derivation_evidence_hash: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub metrics: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub training_objective: Json,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "research_profile_artifact_id",
        to = "research_profile_artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub research_profile_artifact: BelongsTo<super::research_profile_artifact::Entity>,
    #[sea_orm(has_many)]
    pub quant_backtest_path_sets: HasMany<super::quant_backtest_path_set::Entity>,
    #[sea_orm(has_many)]
    pub quant_feature_parity_runs: HasMany<super::quant_feature_parity_run::Entity>,
    #[sea_orm(has_many)]
    pub quant_feature_parity_subjects: HasMany<super::quant_feature_parity_subject::Entity>,
    #[sea_orm(has_many)]
    pub quant_model_governance_audits: HasMany<super::quant_model_governance_audit::Entity>,
    #[sea_orm(has_many)]
    pub quant_model_runs: HasMany<super::quant_model_run::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ParentModelVersion",
        from = "parent_model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub parent_model_version: BelongsTo<Option<super::quant_model_version::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "CalibrationArtifact",
        from = "calibration_artifact_id",
        to = "artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub calibration_artifact: BelongsTo<Option<super::quant_calibration_artifact::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "model_spec_id",
        to = "model_spec_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_spec: BelongsTo<super::quant_model_spec::Entity>,
    #[sea_orm(has_many)]
    pub quant_order_intents: HasMany<super::quant_order_intent::Entity>,
    #[sea_orm(has_many)]
    pub quant_recommendation_reports: HasMany<super::quant_recommendation_report::Entity>,
    #[sea_orm(
        belongs_to,
        from = "trade_policy_artifact_id",
        to = "artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_trade_policy_artifact: BelongsTo<Option<super::quant_trade_policy_artifact::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "training_dataset_id",
        to = "training_dataset_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_training_dataset: BelongsTo<Option<super::quant_training_dataset::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
