//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpOutcomeSide;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_settlement_redeem_lot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub settlement_redeem_lot_id: Uuid,
    pub settlement_redeem_id: Uuid,
    pub position_id: Uuid,
    pub order_intent_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    pub side: QpOutcomeSide,
    pub shares_redeemed: Decimal,
    pub cost_basis_usd: Decimal,
    pub payout_usd: Decimal,
    pub realized_pnl_usd: Decimal,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "order_intent_id",
        to = "order_intent_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_order_intent: BelongsTo<super::quant_order_intent::Entity>,
    #[sea_orm(
        belongs_to,
        from = "position_id",
        to = "position_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_position: BelongsTo<super::quant_position::Entity>,
    #[sea_orm(
        belongs_to,
        from = "settlement_redeem_id",
        to = "settlement_redeem_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_settlement_redeem: BelongsTo<super::quant_settlement_redeem::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
