//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpFeedbackRecipeTemplateStatus, QpModelFamily};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_feedback_recipe_template")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recipe_template_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub revision: i32,
    #[sea_orm(column_type = "Text")]
    pub research_profile_artifact_id: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub route: Json,
    pub model_family: QpModelFamily,
    pub model_spec_id: Uuid,
    pub status: QpFeedbackRecipeTemplateStatus,
    pub catalog_priority: i32,
    pub approved_by_user_id: Option<Uuid>,
    pub approved_by_role: Option<String>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub governance_reason: String,
    #[sea_orm(column_type = "Text")]
    pub template_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub template: Json,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "research_profile_artifact_id",
        to = "research_profile_artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub research_profile_artifact: BelongsTo<super::research_profile_artifact::Entity>,
    #[sea_orm(
        belongs_to,
        from = "model_spec_id",
        to = "model_spec_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub model_spec: BelongsTo<super::quant_model_spec::Entity>,
    #[sea_orm(
        belongs_to,
        from = "approved_by_user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub approved_by_user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
