//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpEntryConditionState;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_entry_condition_instance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub condition_instance_id: Uuid,
    pub recommendation_id: Uuid,
    pub artifact_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub artifact_hash: Option<String>,
    pub state: QpEntryConditionState,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub truth_json: Option<Json>,
    pub revision: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub evaluation_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub input_fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub continuity_hash: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub fold_state_json: Json,
    pub confirmation_started_at: Option<DateTimeWithTimeZone>,
    pub last_evaluated_at: Option<DateTimeWithTimeZone>,
    pub next_evaluation_at: Option<DateTimeWithTimeZone>,
    pub expires_at: DateTimeWithTimeZone,
    pub lease_owner: Option<Uuid>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    pub lease_epoch: i64,
    pub claimed_by_intent_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub claim_admission_state_version: Option<String>,
    pub consumed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "artifact_id",
        to = "artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_entry_condition_artifact:
        BelongsTo<Option<super::quant_entry_condition_artifact::Entity>>,
    #[sea_orm(has_many)]
    pub quant_entry_condition_audits: HasMany<super::quant_entry_condition_audit::Entity>,
    #[sea_orm(has_many)]
    pub quant_order_intents: HasMany<super::quant_order_intent::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recommendation_id",
        to = "recommendation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation: BelongsTo<super::quant_recommendation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
