//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpRecommendationAttributionOutcome;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_recommendation_attribution")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_id: Uuid,
    pub outcome: QpRecommendationAttributionOutcome,
    #[sea_orm(column_type = "JsonBinary")]
    pub entry_outcome_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub exit_outcome_json: Json,
    pub realized_pnl_usd: Option<Decimal>,
    pub max_adverse_excursion_bps: Option<Decimal>,
    pub max_favorable_excursion_bps: Option<Decimal>,
    pub label_available_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary")]
    pub attribution_json: Json,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "recommendation_id",
        to = "recommendation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation: BelongsTo<super::quant_recommendation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
