//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_crypto_price_projection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub source_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub instrument_key: String,
    pub previous_price: Option<Decimal>,
    pub current_price: Decimal,
    pub source_sequence: i64,
    pub event_time: DateTimeWithTimeZone,
    pub available_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub report_hash: String,
    pub gap_generation: i64,
    pub source_healthy: bool,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
