//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpRecommendationEconomicOutcomeState;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_recommendation_economic_outcome")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_id: Uuid,
    pub recommendation_report_id: Uuid,
    pub report_route_run_id: Uuid,
    pub decision_policy_snapshot_id: Uuid,
    pub economic_tier_id: Uuid,
    pub model_version_id: Uuid,
    pub trade_policy_artifact_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub research_profile_artifact_id: String,
    pub state: QpRecommendationEconomicOutcomeState,
    pub decision_at: DateTimeWithTimeZone,
    pub horizon_at: DateTimeWithTimeZone,
    pub source_available_until: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub replay_kernel_version: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload_json: Json,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    pub available_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "recommendation_id",
        to = "recommendation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation: BelongsTo<super::quant_recommendation::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recommendation_report_id",
        to = "recommendation_report_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation_report: BelongsTo<super::quant_recommendation_report::Entity>,
    #[sea_orm(
        belongs_to,
        from = "report_route_run_id",
        to = "report_route_run_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_report_route_run: BelongsTo<super::quant_report_route_run::Entity>,
    #[sea_orm(
        belongs_to,
        from = "decision_policy_snapshot_id",
        to = "decision_policy_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub decision_policy_snapshot: BelongsTo<super::decision_policy_snapshot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_version: BelongsTo<super::quant_model_version::Entity>,
    #[sea_orm(
        belongs_to,
        from = "trade_policy_artifact_id",
        to = "artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_trade_policy_artifact: BelongsTo<super::quant_trade_policy_artifact::Entity>,
    #[sea_orm(
        belongs_to,
        from = "research_profile_artifact_id",
        to = "research_profile_artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub research_profile_artifact: BelongsTo<super::research_profile_artifact::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
