//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpExitSettlementMode, QpOutcomeSide, QpRedeemPolicy};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_settlement_inventory_lot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub settlement_inventory_lot_id: Uuid,
    pub settlement_redeem_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub inventory_digest: String,
    #[sea_orm(column_type = "Text")]
    pub contributor_lots_digest: String,
    pub execution_account_id: Uuid,
    pub strategy_position_lot_id: Uuid,
    pub order_intent_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    pub side: QpOutcomeSide,
    pub shares: Decimal,
    pub cost_basis_usd: Decimal,
    pub settlement_mode: QpExitSettlementMode,
    pub redeem_policy: QpRedeemPolicy,
    pub position_version_at: DateTimeWithTimeZone,
    pub intent_version_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "settlement_redeem_id",
        to = "settlement_redeem_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_settlement_redeem: BelongsTo<super::quant_settlement_redeem::Entity>,
    #[sea_orm(
        belongs_to,
        from = "execution_account_id",
        to = "execution_account_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_account: BelongsTo<super::quant_execution_account::Entity>,
    #[sea_orm(
        belongs_to,
        from = "strategy_position_lot_id",
        to = "strategy_position_lot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_strategy_position_lot: BelongsTo<super::quant_strategy_position_lot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "order_intent_id",
        to = "order_intent_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_order_intent: BelongsTo<super::quant_order_intent::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
