//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpReportScheduleGapReason;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_report_schedule_gap")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub gap_id: Uuid,
    pub schedule_id: String,
    pub decision_policy_snapshot_id: Uuid,
    pub reason: QpReportScheduleGapReason,
    pub first_scheduled_for: DateTimeWithTimeZone,
    pub last_scheduled_for: DateTimeWithTimeZone,
    pub missed_count: i64,
    pub detected_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub detail: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "decision_policy_snapshot_id",
        to = "decision_policy_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub decision_policy_snapshot: BelongsTo<super::decision_policy_snapshot::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
