//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpRecommendationAttributionOutcome;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "public",
    table_name = "quant_recommendation_attribution"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_id: Uuid,
    pub outcome: QpRecommendationAttributionOutcome,
    #[sea_orm(column_type = "JsonBinary")]
    pub entry_outcome_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub exit_outcome_json: Json,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))", nullable)]
    pub realized_pnl_usd: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))", nullable)]
    pub max_adverse_excursion_bps: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))", nullable)]
    pub max_favorable_excursion_bps: Option<Decimal>,
    pub label_available_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary")]
    pub attribution_json: Json,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
