//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpAccountPauseSubmissionState, QpSettlementSubmissionKind};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_account_pause_submission")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_pause_submission_id: Uuid,
    pub recovery_incident_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub exchange_address: String,
    pub state: QpAccountPauseSubmissionState,
    pub kind: QpSettlementSubmissionKind,
    pub requested_block: i64,
    pub interval_blocks: i64,
    pub effective_block: i64,
    pub prepared_block_number: i64,
    #[sea_orm(column_type = "Text")]
    pub prepared_block_hash: String,
    #[sea_orm(column_type = "Text")]
    pub prepared_nonce: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub gas_limit: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub calldata_hash: String,
    #[sea_orm(column_type = "Text")]
    pub deployment_digest: String,
    pub signed_envelope: Vec<u8>,
    #[sea_orm(column_type = "Text")]
    pub signed_envelope_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub transaction_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub relayer_transaction_id: Option<String>,
    pub confirmation_block_number: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub confirmation_block_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub confirmation_transaction_hash: Option<String>,
    pub confirmation_log_index: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_detail: Option<String>,
    pub dispatched_at: Option<DateTimeWithTimeZone>,
    pub confirmed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "recovery_incident_id",
        to = "account_recovery_incident_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_account_recovery_incident: BelongsTo<super::quant_account_recovery_incident::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
