//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpFreshBootBlockedReason, QpFreshBootRetryReason, QpFreshBootStage, QpFreshBootStatus,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_fresh_boot_run")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub run_id: Uuid,
    pub supersedes_run_id: Option<Uuid>,
    pub research_profile_artifact_id: String,
    pub profile_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub route: Json,
    pub stage: QpFreshBootStage,
    pub status: QpFreshBootStatus,
    #[sea_orm(column_type = "JsonBinary")]
    pub source_coverage_manifest: Option<Json>,
    pub source_coverage_hash: Option<String>,
    pub source_slice_id: Option<Uuid>,
    pub source_slice_hash: Option<String>,
    pub decision_policy_snapshot_id: Uuid,
    pub model_spec_id: Option<Uuid>,
    pub training_dataset_id: Option<Uuid>,
    pub calibration_dataset_id: Option<Uuid>,
    pub source_model_version_id: Option<Uuid>,
    pub model_version_id: Option<Uuid>,
    pub path_set_id: Option<Uuid>,
    pub calibration_id: Option<Uuid>,
    pub parity_run_id: Option<Uuid>,
    pub scenario_artifact_id: Option<Uuid>,
    pub scenario_artifact_hash: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub bootstrap_preflight: Option<Json>,
    pub bootstrap_preflight_hash: Option<String>,
    pub active_job_id: Option<Uuid>,
    pub last_job_id: Option<Uuid>,
    pub bootstrap_policy_activation_id: Option<Uuid>,
    pub first_report_run_id: Option<Uuid>,
    pub first_report_id: Option<Uuid>,
    pub next_scheduled_report_at: Option<DateTimeWithTimeZone>,
    pub retry_reason: Option<QpFreshBootRetryReason>,
    pub retry_detail: Option<String>,
    pub retry_count: i32,
    pub next_attempt_at: Option<DateTimeWithTimeZone>,
    pub blocked_reason: Option<QpFreshBootBlockedReason>,
    pub blocked_detail: Option<String>,
    pub lease_owner: Option<Uuid>,
    pub lease_expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", unique)]
    pub idempotency_key: String,
    pub revision: i64,
    pub stage_entered_at: DateTimeWithTimeZone,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
