//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpOutcomeSide, QpRecommendationStatus};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_recommendation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_id: Uuid,
    pub recommendation_report_id: Uuid,
    pub report_route_run_id: Uuid,
    pub portfolio_plan_id: Uuid,
    pub economic_tier_id: Uuid,
    pub rank: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub route: Json,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    pub outcome_side: QpOutcomeSide,
    #[sea_orm(column_type = "JsonBinary")]
    pub economics_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub economic_tier_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub identity: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub market_context: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub trade_plan: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub factor_breakdown: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub evidence_refs: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub execution_eligibility: Json,
    pub valid_from: DateTimeWithTimeZone,
    pub valid_until: DateTimeWithTimeZone,
    pub status: QpRecommendationStatus,
    pub status_changed_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "recommendation_report_id",
        to = "recommendation_report_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation_report: BelongsTo<super::quant_recommendation_report::Entity>,
    #[sea_orm(
        belongs_to,
        from = "report_route_run_id",
        to = "report_route_run_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_report_route_run: BelongsTo<super::quant_report_route_run::Entity>,
    #[sea_orm(
        belongs_to,
        from = "portfolio_plan_id",
        to = "portfolio_plan_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_portfolio_plan: BelongsTo<super::quant_portfolio_plan::Entity>,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "event_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub event: BelongsTo<super::event::Entity>,
    #[sea_orm(
        belongs_to,
        from = "market_id",
        to = "market_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub market: BelongsTo<super::market::Entity>,
    #[sea_orm(has_many)]
    pub quant_capital_allocations: HasMany<super::quant_capital_allocation::Entity>,
    #[sea_orm(has_many)]
    pub quant_entry_condition_instances: HasMany<super::quant_entry_condition_instance::Entity>,
    #[sea_orm(has_many)]
    pub quant_order_intents: HasMany<super::quant_order_intent::Entity>,
    #[sea_orm(has_one)]
    pub quant_recommendation_execution_rollup:
        HasOne<super::quant_recommendation_execution_rollup::Entity>,
    #[sea_orm(has_one)]
    pub quant_recommendation_resolution_outcome:
        HasOne<super::quant_recommendation_resolution_outcome::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
