//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::{QpDomainFamily, QpLinkageStatus, QpResolverTier};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_market_linkage")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub linkage_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    pub domain_family: QpDomainFamily,
    pub status: QpLinkageStatus,
    pub resolver_tier: QpResolverTier,
    pub resolver_version: i32,
    pub confidence: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub outcome: Json,
    #[sea_orm(column_type = "Text")]
    pub metadata_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub capability_registry_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub derived_at: DateTimeWithTimeZone,
    pub override_reason: Option<String>,
    pub override_actor: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "market_id",
        to = "market_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub market: BelongsTo<super::market::Entity>,
    #[sea_orm(has_many)]
    pub quant_market_linkage_sources: HasMany<super::quant_market_linkage_source::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
