//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_market_selection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub market_selection_id: Uuid,
    pub decision_at: DateTimeWithTimeZone,
    pub decision_policy_snapshot_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub selector_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub selector_evidence: Json,
    pub market_count: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub exclusion_summary: Json,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_feature_parity_subjects: HasMany<super::quant_feature_parity_subject::Entity>,
    #[sea_orm(has_many)]
    pub quant_market_selection_members: HasMany<super::quant_market_selection_member::Entity>,
    #[sea_orm(has_many)]
    pub quant_model_runs: HasMany<super::quant_model_run::Entity>,
    #[sea_orm(has_many)]
    pub quant_portfolio_plans: HasMany<super::quant_portfolio_plan::Entity>,
    #[sea_orm(has_many)]
    pub quant_recommendation_reports: HasMany<super::quant_recommendation_report::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
