//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::QpTradePolicyStatus;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_trade_policy_artifact")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub artifact_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    pub status: QpTradePolicyStatus,
    pub source_dataset_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload_json: Json,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_model_versions: HasMany<super::quant_model_version::Entity>,
    #[sea_orm(has_many)]
    pub quant_trade_policy_validations: HasMany<super::quant_trade_policy_validation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
