//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{
    QpExecutionOrderPhase, QpExecutionOrderState, QpOrderTypeKind, QpSide, QpVenueOrderStatus,
};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_execution_order")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub execution_order_id: Uuid,
    pub order_intent_id: Uuid,
    pub order_phase: QpExecutionOrderPhase,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    pub side: QpSide,
    pub order_type: QpOrderTypeKind,
    pub price: Decimal,
    pub shares: Decimal,
    pub cost_usd: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub prepared_order_json: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub venue_order_id: Option<String>,
    pub venue_status: Option<QpVenueOrderStatus>,
    pub state: QpExecutionOrderState,
    pub submitted_at: Option<DateTimeWithTimeZone>,
    pub filled_at: Option<DateTimeWithTimeZone>,
    pub cancelled_at: Option<DateTimeWithTimeZone>,
    pub gtd_expiration_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "market_id",
        to = "market_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub market: BelongsTo<super::market::Entity>,
    #[sea_orm(
        belongs_to,
        from = "order_intent_id",
        to = "order_intent_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_order_intent: BelongsTo<super::quant_order_intent::Entity>,
    #[sea_orm(has_many)]
    pub quant_reconciliations: HasMany<super::quant_reconciliation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
