//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpSourceSliceStatus;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_source_slice")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_slice_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub identity_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub profile_ref: Json,
    #[sea_orm(column_type = "Text")]
    pub evaluation_track: String,
    #[sea_orm(column_type = "Text")]
    pub research_program_hash: String,
    pub runtime_config_version_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub runtime_config_hash: String,
    pub window_start: DateTimeWithTimeZone,
    pub window_end: DateTimeWithTimeZone,
    pub pit_cutoff: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub reader_contract_version: String,
    #[sea_orm(column_type = "Text")]
    pub schema_contract_version: String,
    pub status: QpSourceSliceStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub manifest_uri: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub manifest_hash: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub manifest_json: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_detail: Option<String>,
    pub completed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
