//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_account_recovery_manifest")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_recovery_manifest_id: Uuid,
    pub recovery_incident_id: Uuid,
    pub attempt_no: i32,
    pub observed_at: DateTimeWithTimeZone,
    pub finalized_block_number: i64,
    #[sea_orm(column_type = "Text")]
    pub finalized_block_hash: String,
    pub converged: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub input_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub assessment_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub created_lots_json: Json,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "recovery_incident_id",
        to = "account_recovery_incident_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_account_recovery_incident: BelongsTo<super::quant_account_recovery_incident::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
