//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpSettlementFailureCode, QpSettlementRoute, QpSettlementSubmissionKind,
    QpSettlementSubmissionPurpose, QpSettlementSubmissionState,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_settlement_chain_submission")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub settlement_chain_submission_id: Uuid,
    pub settlement_redeem_id: Option<Uuid>,
    pub settlement_governed_action_id: Option<Uuid>,
    pub canary_action_id: Option<Uuid>,
    pub purpose: QpSettlementSubmissionPurpose,
    pub kind: QpSettlementSubmissionKind,
    pub state: QpSettlementSubmissionState,
    pub route: QpSettlementRoute,
    #[sea_orm(column_type = "Text")]
    pub target_adapter: String,
    #[sea_orm(column_type = "Text")]
    pub target_code_hash: String,
    #[sea_orm(column_type = "Text")]
    pub conditional_tokens: String,
    #[sea_orm(column_type = "Text")]
    pub collateral_token: String,
    #[sea_orm(column_type = "Text")]
    pub usdce: String,
    #[sea_orm(column_type = "Text")]
    pub call_target: String,
    #[sea_orm(column_type = "Text")]
    pub deployment_digest: String,
    #[sea_orm(column_type = "Text")]
    pub deployment_evidence_version: String,
    pub verified_block_number: i64,
    #[sea_orm(column_type = "Text")]
    pub verified_block_hash: String,
    pub prepared_block_number: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub prepared_block_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub calldata_hash: String,
    pub calldata: Vec<u8>,
    pub signed_envelope: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub signed_envelope_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub prepared_nonce: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gas_limit: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub relayer_transaction_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transaction_hash: Option<String>,
    pub failure_code: Option<QpSettlementFailureCode>,
    #[sea_orm(column_type = "JsonBinary")]
    pub failure_history_json: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub receipt_evidence_json: Option<Json>,
    pub attempt_ordinal: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
    pub dispatched_at: Option<DateTimeWithTimeZone>,
    pub chain_hash_observed_at: Option<DateTimeWithTimeZone>,
    pub confirmed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "settlement_redeem_id",
        to = "settlement_redeem_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_settlement_redeem: BelongsTo<Option<super::quant_settlement_redeem::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "settlement_governed_action_id",
        to = "settlement_governed_action_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_settlement_governed_action:
        BelongsTo<Option<super::quant_settlement_governed_action::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "CanaryAction",
        from = "canary_action_id",
        to = "settlement_governed_action_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub canary_action: BelongsTo<Option<super::quant_settlement_governed_action::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
