//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use super::sea_orm_active_enums::QpTradePolicyValidationStatus;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_trade_policy_validation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub validation_run_id: Uuid,
    pub artifact_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub artifact_hash: String,
    pub source_dataset_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub source_dataset_hash: String,
    #[sea_orm(column_type = "Text")]
    pub source_slice_manifest_hash: String,
    #[sea_orm(column_type = "Text")]
    pub evidence_manifest_hash: String,
    pub status: QpTradePolicyValidationStatus,
    pub total_rows: i64,
    pub passed_rows: i64,
    pub failed_rows: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub validation_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub failure_detail: Option<String>,
    pub actor_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "artifact_id",
        to = "artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_trade_policy_artifact: BelongsTo<super::quant_trade_policy_artifact::Entity>,
    #[sea_orm(has_many)]
    pub quant_trade_policy_validation_rows:
        HasMany<super::quant_trade_policy_validation_row::Entity>,
    #[sea_orm(
        belongs_to,
        from = "source_dataset_id",
        to = "training_dataset_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_training_dataset: BelongsTo<super::quant_training_dataset::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
