//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpAccountExecutionAssociationKind;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_account_execution_association")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_chain_execution_id: Uuid,
    pub kind: QpAccountExecutionAssociationKind,
    pub execution_order_id: Option<Uuid>,
    pub recovery_incident_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    pub associated_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "account_chain_execution_id",
        to = "account_chain_execution_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_account_chain_execution: BelongsTo<super::quant_account_chain_execution::Entity>,
    #[sea_orm(
        belongs_to,
        from = "execution_order_id",
        to = "execution_order_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_order: BelongsTo<Option<super::quant_execution_order::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "recovery_incident_id",
        to = "account_recovery_incident_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_account_recovery_incident:
        BelongsTo<Option<super::quant_account_recovery_incident::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
