//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpModelRunErrorCode, QpModelRunKind, QpModelRunStatus};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_model_run")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_run_id: Uuid,
    pub run_kind: QpModelRunKind,
    pub model_version_id: Option<Uuid>,
    pub runtime_config_version_id: Uuid,
    pub market_selection_id: Option<Uuid>,
    pub window_start: DateTimeWithTimeZone,
    pub window_end: DateTimeWithTimeZone,
    pub status: QpModelRunStatus,
    #[sea_orm(column_type = "Text")]
    pub input_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub output_hash: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub metrics_json: Json,
    pub error_code: Option<QpModelRunErrorCode>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub started_at: DateTimeWithTimeZone,
    pub finished_at: Option<DateTimeWithTimeZone>,
}

impl ActiveModelBehavior for ActiveModel {}
