//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpVenueTradeStatus;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_execution_trade_ref")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub execution_trade_ref_id: Uuid,
    pub execution_order_id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub venue_trade_id: String,
    pub trade_status: Option<QpVenueTradeStatus>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transaction_hash: Option<String>,
    pub observed_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_order_id",
        to = "execution_order_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_order: BelongsTo<super::quant_execution_order::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
