//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpAttributionArtifactKind, QpAttributionCohort};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_attribution_artifact")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub attribution_artifact_id: Uuid,
    pub artifact_kind: QpAttributionArtifactKind,
    pub source_cohort: QpAttributionCohort,
    pub source_feedback_cycle_id: Uuid,
    pub model_version_id: Option<Uuid>,
    pub recommendation_id: Option<Uuid>,
    pub order_intent_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub artifact_uri: String,
    #[sea_orm(column_type = "Text")]
    pub artifact_hash: String,
    pub source_cutoff: DateTimeWithTimeZone,
    pub available_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "source_feedback_cycle_id",
        to = "feedback_cycle_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_feedback_cycle: BelongsTo<super::quant_feedback_cycle::Entity>,
    #[sea_orm(
        belongs_to,
        from = "model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_version: BelongsTo<Option<super::quant_model_version::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "recommendation_id",
        to = "recommendation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation: BelongsTo<Option<super::quant_recommendation::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "order_intent_id",
        to = "order_intent_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_order_intent: BelongsTo<Option<super::quant_order_intent::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
