//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_portfolio_plan")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub portfolio_plan_id: Uuid,
    pub model_run_id: Option<Uuid>,
    pub market_selection_id: Uuid,
    pub decision_at: DateTimeWithTimeZone,
    pub budget_usd: Decimal,
    pub allocated_usd: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub risk_budget_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub constraints_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub rejected_summary: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub optimizer_meta_json: Json,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "market_selection_id",
        to = "market_selection_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_market_selection: BelongsTo<super::quant_market_selection::Entity>,
    #[sea_orm(
        belongs_to,
        from = "model_run_id",
        to = "model_run_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_run: BelongsTo<Option<super::quant_model_run::Entity>>,
    #[sea_orm(has_many)]
    pub quant_recommendation_reports: HasMany<super::quant_recommendation_report::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
