//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpReconciliationResult;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_reconciliation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub reconciliation_id: Uuid,
    pub execution_order_id: Uuid,
    pub order_intent_id: Uuid,
    pub result: QpReconciliationResult,
    #[sea_orm(column_type = "JsonBinary")]
    pub evidence_json: Json,
    #[sea_orm(column_type = "Decimal(Some((38, 18)))", nullable)]
    pub venue_filled_shares: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))", nullable)]
    pub venue_avg_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))", nullable)]
    pub expected_cash_delta_usd: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))", nullable)]
    pub venue_cash_delta_usd: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))", nullable)]
    pub realized_pnl_usd: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))", nullable)]
    pub expected_fee_usd: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))", nullable)]
    pub observed_fee_usd: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((28, 8)))", nullable)]
    pub fee_delta_usd: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolved_by: Option<String>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
