//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpModelGovernanceAction, QpPublicationStatus};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_model_governance_audit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub audit_id: Uuid,
    pub model_version_id: Option<Uuid>,
    pub training_dataset_id: Option<Uuid>,
    pub action: QpModelGovernanceAction,
    pub actor_user_id: Option<Uuid>,
    pub actor_username: String,
    pub actor_role: Option<String>,
    pub reason: String,
    pub before_status: QpPublicationStatus,
    pub after_status: QpPublicationStatus,
    #[sea_orm(column_type = "JsonBinary")]
    pub detail: Json,
    pub audit_event_id: Uuid,
    #[sea_orm(unique)]
    pub promotion_permit_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", unique)]
    pub promotion_transaction_hash: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_version: BelongsTo<Option<super::quant_model_version::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "training_dataset_id",
        to = "training_dataset_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_training_dataset: BelongsTo<Option<super::quant_training_dataset::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "promotion_permit_id",
        to = "promotion_permit_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_feedback_promotion_permit:
        BelongsTo<Option<super::quant_feedback_promotion_permit::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
