//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpParitySubjectKind;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_feature_parity_subject")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub parity_subject_id: Uuid,
    pub run_id: Uuid,
    pub subject_kind: QpParitySubjectKind,
    #[sea_orm(column_type = "Text")]
    pub subject_generation: String,
    pub decision_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub selection_hash: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    pub model_run_id: Option<Uuid>,
    pub recommendation_report_id: Option<Uuid>,
    pub market_selection_id: Option<Uuid>,
    pub model_version_id: Option<Uuid>,
    pub training_dataset_id: Option<Uuid>,
}

impl ActiveModelBehavior for ActiveModel {}
