//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "public",
    table_name = "quant_weather_observation_current"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub station: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub local_date: Date,
    #[sea_orm(primary_key, auto_increment = false)]
    pub observation_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Decimal(Some((8, 4)))")]
    pub temperature_celsius: Decimal,
    #[sea_orm(column_type = "Text")]
    pub report_hash: String,
    pub revision: i64,
    pub published_at: DateTimeWithTimeZone,
    pub available_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
