//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpTradePolicyTrialScope, QpTradePolicyTrialStatus};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_trade_policy_trial_attempt")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub trial_attempt_id: Uuid,
    pub fit_job_id: Uuid,
    pub attempt_ordinal: i64,
    #[sea_orm(column_type = "Text")]
    pub experiment_family_hash: String,
    #[sea_orm(column_type = "Text")]
    pub research_program_hash: String,
    pub candidate_id: String,
    #[sea_orm(column_type = "Text")]
    pub candidate_hash: String,
    pub scope: QpTradePolicyTrialScope,
    pub fold_index: Option<i32>,
    pub path_index: Option<i32>,
    pub status: QpTradePolicyTrialStatus,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metrics_json: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub evidence_uri: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub evidence_hash: Option<String>,
    pub evidence_row_count: Option<i64>,
    pub failure_detail: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub row_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "fit_job_id",
        to = "job_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_research_job: BelongsTo<super::quant_research_job::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
