//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_backtest_report")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub backtest_report_id: Uuid,
    pub model_version_id: Uuid,
    pub model_run_id: Uuid,
    pub decision_policy_snapshot_id: Uuid,
    pub window_start: DateTimeWithTimeZone,
    pub window_end: DateTimeWithTimeZone,
    pub coverage: Decimal,
    pub sample_count: i64,
    pub missing_feature_count: i64,
    pub rank_ic: Decimal,
    pub sharpe: Decimal,
    pub hit_rate: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub expected_vs_realized: Json,
    pub max_drawdown: Decimal,
    pub turnover: Decimal,
    pub liquidity_feasibility: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub category_breakdown: Json,
    pub tail_loss: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub report_pnl_simulation: Json,
    #[sea_orm(column_type = "Text")]
    pub report_hash: String,
    pub parquet_uri: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "decision_policy_snapshot_id",
        to = "decision_policy_snapshot_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub decision_policy_snapshot: BelongsTo<super::decision_policy_snapshot::Entity>,
    #[sea_orm(
        belongs_to,
        from = "model_run_id",
        to = "model_run_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_run: BelongsTo<super::quant_model_run::Entity>,
    #[sea_orm(
        belongs_to,
        from = "model_version_id",
        to = "model_version_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_model_version: BelongsTo<super::quant_model_version::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
