//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpFeeMeasurementStage;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_execution_fee_measurement")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub execution_fee_measurement_id: Uuid,
    pub execution_fill_id: Uuid,
    pub stage: QpFeeMeasurementStage,
    pub fee_usd: Decimal,
    pub fee_rate_bps: Option<Decimal>,
    #[sea_orm(column_type = "Text")]
    pub source_identity: String,
    pub chain_id: Option<i64>,
    pub protocol_version: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub exchange_address: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub transaction_hash: Option<String>,
    pub log_index: Option<i64>,
    pub observed_at: DateTimeWithTimeZone,
    pub available_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_fill_id",
        to = "execution_fill_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_fill: BelongsTo<super::quant_execution_fill::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
