//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_backtest_path_set")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub path_set_id: Uuid,
    pub model_version_id: Uuid,
    pub model_run_id: Uuid,
    pub training_dataset_id: Uuid,
    pub runtime_config_version_id: Uuid,
    pub window_start: DateTimeWithTimeZone,
    pub window_end: DateTimeWithTimeZone,
    pub path_count: i64,
    pub combination_count: i64,
    #[sea_orm(column_type = "Decimal(Some((28, 12)))")]
    pub median_rank_ic: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub sharpe_distribution: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub paths: Json,
    #[sea_orm(column_type = "Decimal(Some((28, 12)))")]
    pub deflated_sharpe: Decimal,
    #[sea_orm(column_type = "Decimal(Some((28, 12)))")]
    pub dsr_benchmark_sharpe: Decimal,
    #[sea_orm(column_type = "Decimal(Some((28, 12)))")]
    pub pbo: Decimal,
    pub min_track_record_length_secs: Option<i64>,
    pub trial_count: i64,
    pub trial_grid_count: i64,
    pub coord_search_effective_n: i64,
    #[sea_orm(column_type = "Text")]
    pub path_set_hash: String,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
