//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpRouteEconomicHealthState;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_route_economic_health")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub route_economic_health_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub route: Json,
    #[sea_orm(column_type = "Text")]
    pub route_identity_hash: String,
    #[sea_orm(column_type = "Text")]
    pub research_profile_artifact_id: String,
    #[sea_orm(column_type = "Text")]
    pub feedback_policy_hash: String,
    pub state: QpRouteEconomicHealthState,
    pub window_start: Option<DateTimeWithTimeZone>,
    pub assessed_through: DateTimeWithTimeZone,
    pub due_observation_count: i64,
    pub usable_observation_count: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub coverage: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))", nullable)]
    pub effective_sample_size: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))", nullable)]
    pub weighted_mean_return_bps: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))", nullable)]
    pub lower_confidence_return_bps: Option<Decimal>,
    pub comparison_minimum_observations: i64,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub minimum_coverage: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub minimum_effect_bps: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub confidence: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub evidence_json: Json,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    pub available_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "research_profile_artifact_id",
        to = "research_profile_artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub research_profile_artifact: BelongsTo<super::research_profile_artifact::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
