//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(
    schema_name = "public",
    table_name = "quant_weather_daily_high_projection"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub source_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub instrument_key: String,
    #[sea_orm(column_type = "Text")]
    pub station: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub local_date: Date,
    #[sea_orm(column_type = "Text")]
    pub timezone: String,
    #[sea_orm(column_type = "Decimal(Some((8, 4)))")]
    pub current_high_celsius: Decimal,
    #[sea_orm(column_type = "Decimal(Some((8, 4)))", nullable)]
    pub previous_high_celsius: Option<Decimal>,
    pub last_observation_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub last_report_hash: String,
    pub last_event_id: Option<Uuid>,
    pub revision: i64,
    pub day_closed: bool,
    pub gap_generation: i64,
    pub source_healthy: bool,
    pub available_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
