//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{
    QpApprovalStatus, QpExitReason, QpExitState, QpOrderIntentKind, QpOrderIntentStatus,
    QpQuantRuntimeMode,
};
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "quant_order_intent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub order_intent_id: Uuid,
    pub recommendation_id: Uuid,
    pub runtime_mode: QpQuantRuntimeMode,
    pub runtime_config_version_id: Uuid,
    pub model_version_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub profile_ref: Json,
    pub intent_kind: QpOrderIntentKind,
    pub status: QpOrderIntentStatus,
    pub approval_status: QpApprovalStatus,
    pub approved_by: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub approval_reason: Option<String>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub policy_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub policy_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub status_reason: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub admission_trace_ref: Option<String>,
    pub condition_instance_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub entry_order_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub exit_policy_json: Json,
    #[sea_orm(column_type = "Text")]
    pub risk_envelope_hash: String,
    pub expires_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"'not_started'::qp_exit_state\")")]
    pub exit_state: QpExitState,
    pub exit_reason: Option<QpExitReason>,
    pub next_check_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))", nullable)]
    pub peak_mark_price: Option<Decimal>,
    pub last_signal_recheck_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub latest_reinference_json: Option<Json>,
    #[sea_orm(column_type = "JsonBinary")]
    #[sea_orm(
        default_expr = "Expr::cust(\"'{\\\"pending_target\\\": null, \\\"denominator_shares\\\": null, \\\"settled_target_ids\\\": [], \\\"cumulative_exited_shares\\\": \\\"0\\\"}'::jsonb\")"
    )]
    pub scale_out_state: Json,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
