//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::{QpOutcomeSide, QpRecommendationStatus};
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_recommendation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub research_profile_artifact_id: String,
    pub recommendation_report_id: Uuid,
    pub rank: i32,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub event_id: String,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    pub outcome_side: QpOutcomeSide,
    pub composite_score: Decimal,
    pub risk_adjusted_score: Decimal,
    pub confidence: Decimal,
    pub expected_return_bps: Decimal,
    pub downside_bps: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub identity: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub market_context: Json,
    pub rank_before_portfolio: i32,
    pub liquidity_score: Decimal,
    pub data_quality_score: Decimal,
    pub model_score_percentile: Decimal,
    #[sea_orm(column_type = "JsonBinary")]
    pub trade_plan: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub factor_breakdown: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub evidence_refs: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub execution_eligibility: Json,
    pub valid_from: DateTimeWithTimeZone,
    pub valid_until: DateTimeWithTimeZone,
    pub status: QpRecommendationStatus,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "research_profile_artifact_id",
        to = "research_profile_artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub research_profile_artifact: BelongsTo<super::research_profile_artifact::Entity>,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "event_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub event: BelongsTo<super::event::Entity>,
    #[sea_orm(
        belongs_to,
        from = "market_id",
        to = "market_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub market: BelongsTo<super::market::Entity>,
    #[sea_orm(has_many)]
    pub quant_capital_allocations: HasMany<super::quant_capital_allocation::Entity>,
    #[sea_orm(has_many)]
    pub quant_entry_condition_instances: HasMany<super::quant_entry_condition_instance::Entity>,
    #[sea_orm(has_many)]
    pub quant_order_intents: HasMany<super::quant_order_intent::Entity>,
    #[sea_orm(has_one)]
    pub quant_recommendation_attribution: HasOne<super::quant_recommendation_attribution::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recommendation_report_id",
        to = "recommendation_report_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation_report: BelongsTo<super::quant_recommendation_report::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
