//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{
    QpVenueIncentiveKind, QpVenueIncentiveReconciliationScanStatus, QpVenueIncentiveStage,
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_venue_incentive_reconciliation_scan")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub venue_incentive_reconciliation_scan_id: Uuid,
    pub execution_account_id: Uuid,
    pub kind: QpVenueIncentiveKind,
    pub stage: QpVenueIncentiveStage,
    pub program_date: Date,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: DateTimeWithTimeZone,
    pub status: QpVenueIncentiveReconciliationScanStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub response_digest: Option<String>,
    pub response_count: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_code: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "execution_account_id",
        to = "execution_account_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_execution_account: BelongsTo<super::quant_execution_account::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
