//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::quant_exchange_history_plan;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_history_fit_seal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub fit_seal_id: Uuid,
    #[sea_orm(unique)]
    pub seal_hash: String,
    pub plan_id: Uuid,
    pub window_from_block: i64,
    pub window_to_block: i64,
    pub policy_hash: String,
    pub profile_hash: String,
    pub cohort_hash: String,
    pub created_at: DateTimeWithTimeZone,

    #[sea_orm(belongs_to, from = "plan_id", to = "plan_id")]
    pub plan: BelongsTo<quant_exchange_history_plan::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
