//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpAccountChainExecutionRole;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_account_clean_funder_blocker")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recovery_incident_id: Uuid,
    pub account_chain_execution_id: Uuid,
    pub role: QpAccountChainExecutionRole,
    #[sea_orm(column_type = "Text")]
    pub evidence_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "recovery_incident_id",
        to = "account_recovery_incident_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_account_recovery_incident: BelongsTo<super::quant_account_recovery_incident::Entity>,
    #[sea_orm(
        belongs_to,
        from = "account_chain_execution_id",
        to = "account_chain_execution_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_account_chain_execution: BelongsTo<super::quant_account_chain_execution::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
