//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_feature_parity_candidate")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub parity_candidate_id: Uuid,
    pub parity_subject_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    pub ordinal: i32,
    #[sea_orm(column_type = "Text")]
    pub membership_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "parity_subject_id",
        to = "parity_subject_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_feature_parity_subject: BelongsTo<super::quant_feature_parity_subject::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
