//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpSettlementAuthorizationState;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_settlement_authorization")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub settlement_authorization_id: Uuid,
    pub settlement_redeem_id: Uuid,
    pub attempt_ordinal: i32,
    pub state: QpSettlementAuthorizationState,
    #[sea_orm(column_type = "Text")]
    pub scope_digest: String,
    pub staged_by: Uuid,
    pub expires_at: DateTimeWithTimeZone,
    pub approved_by: Option<Uuid>,
    pub approved_at: Option<DateTimeWithTimeZone>,
    pub revoked_by: Option<Uuid>,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    pub consumed_at: Option<DateTimeWithTimeZone>,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "settlement_redeem_id",
        to = "settlement_redeem_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_settlement_redeem: BelongsTo<super::quant_settlement_redeem::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ApprovedBy",
        from = "approved_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub approved_by_user: BelongsTo<Option<super::user::Entity>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "RevokedBy",
        from = "revoked_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub revoked_by_user: BelongsTo<Option<super::user::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
