//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpCalibrationKind;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_calibration_artifact_publication")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub publication_id: Uuid,
    pub artifact_id: Uuid,
    pub kind: QpCalibrationKind,
    pub published_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "artifact_id",
        to = "artifact_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_calibration_artifact: BelongsTo<super::quant_calibration_artifact::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
