//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpRecommendationResolutionKind;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "quant_recommendation_resolution_outcome")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recommendation_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub market_id: String,
    #[sea_orm(column_type = "Text")]
    pub token_id: String,
    pub resolution_kind: QpRecommendationResolutionKind,
    #[sea_orm(column_type = "Decimal(Some((20, 18)))")]
    pub token_payout_ratio: Decimal,
    pub resolved_at: DateTimeWithTimeZone,
    pub source_observed_at: DateTimeWithTimeZone,
    pub available_at: DateTimeWithTimeZone,
    pub source_checkpoint_hash: String,
    pub resolution_fact_hash: String,
    pub resolution_fact_log_index: i64,
    pub resolution_fact_schema_version: i32,
    pub outcome_hash: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "market_id",
        to = "market_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub market: BelongsTo<super::market::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recommendation_id",
        to = "recommendation_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub quant_recommendation: BelongsTo<super::quant_recommendation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
