//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "research_profile_artifact")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[sea_orm(column_type = "Text")]
    pub research_profile_artifact_id: String,
    #[sea_orm(column_type = "Text")]
    pub research_profile_id: String,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub content_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub spec: Json,
    #[sea_orm(column_type = "Text")]
    pub published_by: String,
    pub published_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub governance_reason: String,
    #[sea_orm(default_expr = "Expr::current_timestamp()")]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub quant_model_versions: HasMany<super::quant_model_version::Entity>,
    #[sea_orm(has_many)]
    pub quant_order_intents: HasMany<super::quant_order_intent::Entity>,
    #[sea_orm(has_many)]
    pub quant_recommendations: HasMany<super::quant_recommendation::Entity>,
    #[sea_orm(has_many)]
    pub quant_recommendation_reports: HasMany<super::quant_recommendation_report::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
