//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpRoleKind, QpRoleStatus};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub kind: QpRoleKind,
    pub status: QpRoleStatus,
    pub sort: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many, via = "role_menu")]
    pub menus: HasMany<super::menu::Entity>,
    #[sea_orm(has_many, via = "user_role")]
    pub users: HasMany<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
