//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpRuntimeConfigSource;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "runtime_config_version")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub runtime_config_version_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub config_hash: String,
    pub schema_version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub config_json: Json,
    pub source: QpRuntimeConfigSource,
    #[sea_orm(column_type = "Text")]
    pub created_by: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
