//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpRuntimeConfigActivationKind;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "runtime_config_activation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub runtime_config_activation_id: Uuid,
    pub runtime_config_version_id: Uuid,
    pub activated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub activated_by: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub activation_kind: QpRuntimeConfigActivationKind,
    pub previous_runtime_config_version_id: Option<Uuid>,
    pub rollback_target_version_id: Option<Uuid>,
    pub audit_event_id: Option<Uuid>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
    pub runtime_config_approval_id: Option<Uuid>,
}

impl ActiveModelBehavior for ActiveModel {}
