//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpRuntimeConfigApprovalDecision;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "runtime_config_approval")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub runtime_config_approval_id: Uuid,
    pub runtime_config_version_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub config_hash: String,
    pub decision: QpRuntimeConfigApprovalDecision,
    #[sea_orm(column_type = "Text")]
    pub decided_by: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub decided_at: DateTimeWithTimeZone,
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub created_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
