//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "schema_migration_audit")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "String(StringLen::N(255))"
    )]
    pub version: String,
    #[sea_orm(column_type = "String(StringLen::N(32))")]
    pub checksum_algorithm: String,
    #[sea_orm(column_type = "Char(Some(64))")]
    pub checksum: String,
    pub artifact_length: i64,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub migration_engine: String,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub applied_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
