//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_account_source")]
pub enum QpAccountSource {
    #[sea_orm(string_value = "polymarket")]
    Polymarket,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_approval_status")]
pub enum QpApprovalStatus {
    #[sea_orm(string_value = "not_required")]
    NotRequired,
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "expired")]
    Expired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_bootstrap_phase")]
pub enum QpBootstrapPhase {
    #[sea_orm(string_value = "initializing")]
    Initializing,
    #[sea_orm(string_value = "collecting_baseline")]
    CollectingBaseline,
    #[sea_orm(string_value = "awaiting_activation")]
    AwaitingActivation,
    #[sea_orm(string_value = "active")]
    Active,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_calibration_kind")]
pub enum QpCalibrationKind {
    #[sea_orm(string_value = "model_score")]
    ModelScore,
    #[sea_orm(string_value = "market_price_bias")]
    MarketPriceBias,
    #[sea_orm(string_value = "weather_station_lead_bias")]
    WeatherStationLeadBias,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_capital_allocation_state"
)]
pub enum QpCapitalAllocationState {
    #[sea_orm(string_value = "allocated")]
    Allocated,
    #[sea_orm(string_value = "locked")]
    Locked,
    #[sea_orm(string_value = "spent")]
    Spent,
    #[sea_orm(string_value = "released")]
    Released,
    #[sea_orm(string_value = "impaired")]
    Impaired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_change_type"
)]
pub enum QpCatalogChangeType {
    #[sea_orm(string_value = "gamma_scan_upsert")]
    GammaScanUpsert,
    #[sea_orm(string_value = "gamma_id_recheck_upsert")]
    GammaIdRecheckUpsert,
    #[sea_orm(string_value = "gamma_confirmed_tombstone")]
    GammaConfirmedTombstone,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_entity_kind"
)]
pub enum QpCatalogEntityKind {
    #[sea_orm(string_value = "event")]
    Event,
    #[sea_orm(string_value = "market")]
    Market,
    #[sea_orm(string_value = "cursor")]
    Cursor,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_filter_reason"
)]
pub enum QpCatalogFilterReason {
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "clob_disabled")]
    ClobDisabled,
    #[sea_orm(string_value = "orders_not_accepted")]
    OrdersNotAccepted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_rejection_reason"
)]
pub enum QpCatalogRejectionReason {
    #[sea_orm(string_value = "empty_condition_id")]
    EmptyConditionId,
    #[sea_orm(string_value = "missing_clob_token_ids")]
    MissingClobTokenIds,
    #[sea_orm(string_value = "not_binary")]
    NotBinary,
    #[sea_orm(string_value = "invalid_token_pair")]
    InvalidTokenPair,
    #[sea_orm(string_value = "unsupported_tick_size")]
    UnsupportedTickSize,
    #[sea_orm(string_value = "duplicate_entity_id")]
    DuplicateEntityId,
    #[sea_orm(string_value = "malformed_entity")]
    MalformedEntity,
    #[sea_orm(string_value = "cursor_protocol_violation")]
    CursorProtocolViolation,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_sync_failure_stage"
)]
pub enum QpCatalogSyncFailureStage {
    #[sea_orm(string_value = "fetch")]
    Fetch,
    #[sea_orm(string_value = "normalize")]
    Normalize,
    #[sea_orm(string_value = "persist")]
    Persist,
    #[sea_orm(string_value = "recovery")]
    Recovery,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_catalog_sync_kind")]
pub enum QpCatalogSyncKind {
    #[sea_orm(string_value = "baseline")]
    Baseline,
    #[sea_orm(string_value = "reconcile")]
    Reconcile,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_sync_status"
)]
pub enum QpCatalogSyncStatus {
    #[sea_orm(string_value = "committed")]
    Committed,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_timestamp_quality"
)]
pub enum QpCatalogTimestampQuality {
    #[sea_orm(string_value = "source")]
    Source,
    #[sea_orm(string_value = "commit_time_fallback")]
    CommitTimeFallback,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_config_resource_kind"
)]
pub enum QpConfigResourceKind {
    #[sea_orm(string_value = "recommendation_policy")]
    RecommendationPolicy,
    #[sea_orm(string_value = "execution_risk_policy")]
    ExecutionRiskPolicy,
    #[sea_orm(string_value = "model_routing")]
    ModelRouting,
    #[sea_orm(string_value = "report_schedule")]
    ReportSchedule,
    #[sea_orm(string_value = "operational_control")]
    OperationalControl,
    #[sea_orm(string_value = "execution_authorization")]
    ExecutionAuthorization,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_data_quality_status"
)]
pub enum QpDataQualityStatus {
    #[sea_orm(string_value = "fresh")]
    Fresh,
    #[sea_orm(string_value = "acceptable")]
    Acceptable,
    #[sea_orm(string_value = "degraded")]
    Degraded,
    #[sea_orm(string_value = "stale")]
    Stale,
    #[sea_orm(string_value = "insufficient")]
    Insufficient,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_dataset_purpose")]
pub enum QpDatasetPurpose {
    #[sea_orm(string_value = "training")]
    Training,
    #[sea_orm(string_value = "calibration")]
    Calibration,
    #[sea_orm(string_value = "policy_fit")]
    PolicyFit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_decision_policy_snapshot_source"
)]
pub enum QpDecisionPolicySnapshotSource {
    #[sea_orm(string_value = "bootstrap")]
    Bootstrap,
    #[sea_orm(string_value = "activation")]
    Activation,
    #[sea_orm(string_value = "rollback")]
    Rollback,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_profile_artifact_kind"
)]
pub enum QpProfileArtifactKind {
    #[sea_orm(string_value = "feature")]
    Feature,
    #[sea_orm(string_value = "scoring")]
    Scoring,
    #[sea_orm(string_value = "domain")]
    Domain,
    #[sea_orm(string_value = "research_method")]
    ResearchMethod,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_domain_cursor_status"
)]
pub enum QpDomainCursorStatus {
    #[sea_orm(string_value = "bootstrap")]
    Bootstrap,
    #[sea_orm(string_value = "backfilling")]
    Backfilling,
    #[sea_orm(string_value = "live")]
    Live,
    #[sea_orm(string_value = "error")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_domain_family")]
pub enum QpDomainFamily {
    #[sea_orm(string_value = "crypto")]
    Crypto,
    #[sea_orm(string_value = "weather")]
    Weather,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_domain_source_expectation_status"
)]
pub enum QpDomainSourceExpectationStatus {
    #[sea_orm(string_value = "not_started")]
    NotStarted,
    #[sea_orm(string_value = "live")]
    Live,
    #[sea_orm(string_value = "stale")]
    Stale,
    #[sea_orm(string_value = "credential_blocked")]
    CredentialBlocked,
    #[sea_orm(string_value = "error")]
    Failed,
    #[sea_orm(string_value = "unsupported")]
    Unsupported,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_entry_condition_audit_action"
)]
pub enum QpEntryConditionAuditAction {
    #[sea_orm(string_value = "created")]
    Created,
    #[sea_orm(string_value = "evaluated")]
    Evaluated,
    #[sea_orm(string_value = "lease_taken_over")]
    LeaseTakenOver,
    #[sea_orm(string_value = "claimed")]
    Claimed,
    #[sea_orm(string_value = "reverted")]
    Reverted,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "invalidated")]
    Invalidated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_entry_condition_state"
)]
pub enum QpEntryConditionState {
    #[sea_orm(string_value = "not_required")]
    NotRequired,
    #[sea_orm(string_value = "waiting")]
    Waiting,
    #[sea_orm(string_value = "unavailable")]
    Unavailable,
    #[sea_orm(string_value = "confirming")]
    Confirming,
    #[sea_orm(string_value = "qualified")]
    Qualified,
    #[sea_orm(string_value = "consumed")]
    Consumed,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "invalidated")]
    Invalidated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_event_status")]
pub enum QpEventStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "archived")]
    Archived,
    #[sea_orm(string_value = "unknown")]
    Unknown,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_execution_order_phase"
)]
pub enum QpExecutionOrderPhase {
    #[sea_orm(string_value = "entry")]
    Entry,
    #[sea_orm(string_value = "exit")]
    Exit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_execution_order_state"
)]
pub enum QpExecutionOrderState {
    #[sea_orm(string_value = "planned")]
    Planned,
    #[sea_orm(string_value = "accepted")]
    Accepted,
    #[sea_orm(string_value = "submitted")]
    Submitted,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "filled")]
    Filled,
    #[sea_orm(string_value = "cancel_requested")]
    CancelRequested,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "ambiguous")]
    Ambiguous,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_execution_wallet_kind"
)]
pub enum QpExecutionWalletKind {
    #[sea_orm(string_value = "eoa")]
    Eoa,
    #[sea_orm(string_value = "proxy")]
    Proxy,
    #[sea_orm(string_value = "gnosis_safe")]
    GnosisSafe,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_exit_reason")]
pub enum QpExitReason {
    #[sea_orm(string_value = "take_profit")]
    TakeProfit,
    #[sea_orm(string_value = "stop_loss")]
    StopLoss,
    #[sea_orm(string_value = "time_exit")]
    TimeExit,
    #[sea_orm(string_value = "partial_exit")]
    PartialExit,
    #[sea_orm(string_value = "signal_invalidated")]
    SignalInvalidated,
    #[sea_orm(string_value = "opportunistic")]
    Opportunistic,
    #[sea_orm(string_value = "manual")]
    Manual,
    #[sea_orm(string_value = "settlement_hold")]
    SettlementHold,
    #[sea_orm(string_value = "resolution_redeem")]
    ResolutionRedeem,
    #[sea_orm(string_value = "kill_switch_emergency")]
    KillSwitchEmergency,
    #[sea_orm(string_value = "risk_envelope_breached")]
    RiskEnvelopeBreached,
    #[sea_orm(string_value = "market_abnormal")]
    MarketAbnormal,
    #[sea_orm(string_value = "data_stale")]
    DataStale,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_exit_state")]
pub enum QpExitState {
    #[sea_orm(string_value = "not_started")]
    NotStarted,
    #[sea_orm(string_value = "monitoring")]
    Monitoring,
    #[sea_orm(string_value = "triggered")]
    Triggered,
    #[sea_orm(string_value = "order_submitted")]
    OrderSubmitted,
    #[sea_orm(string_value = "partially_exited")]
    PartiallyExited,
    #[sea_orm(string_value = "exited")]
    Exited,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "manual_required")]
    ManualRequired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_factor_definition_scope"
)]
pub enum QpFactorDefinitionScope {
    #[sea_orm(string_value = "generic")]
    Generic,
    #[sea_orm(string_value = "structural")]
    Structural,
    #[sea_orm(string_value = "domain_crypto")]
    DomainCrypto,
    #[sea_orm(string_value = "domain_weather")]
    DomainWeather,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_factor_direction")]
pub enum QpFactorDirection {
    #[sea_orm(string_value = "positive")]
    Positive,
    #[sea_orm(string_value = "negative")]
    Negative,
    #[sea_orm(string_value = "neutral")]
    Neutral,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_factor_family")]
pub enum QpFactorFamily {
    #[sea_orm(string_value = "liquidity")]
    Liquidity,
    #[sea_orm(string_value = "microstructure")]
    Microstructure,
    #[sea_orm(string_value = "momentum")]
    Momentum,
    #[sea_orm(string_value = "mean_reversion")]
    MeanReversion,
    #[sea_orm(string_value = "volatility")]
    Volatility,
    #[sea_orm(string_value = "activity")]
    Activity,
    #[sea_orm(string_value = "resolution")]
    Resolution,
    #[sea_orm(string_value = "data_quality")]
    DataQuality,
    #[sea_orm(string_value = "structural")]
    Structural,
    #[sea_orm(string_value = "domain_crypto")]
    DomainCrypto,
    #[sea_orm(string_value = "domain_weather")]
    DomainWeather,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_factor_indeterminate_reason"
)]
pub enum QpFactorIndeterminateReason {
    #[sea_orm(string_value = "cross_section_too_small")]
    CrossSectionTooSmall,
    #[sea_orm(string_value = "zero_variance")]
    ZeroVariance,
    #[sea_orm(string_value = "no_frozen_reference")]
    NoFrozenReference,
    #[sea_orm(string_value = "leg_book_missing")]
    LegBookMissing,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_factor_value_state"
)]
pub enum QpFactorValueState {
    #[sea_orm(string_value = "scored")]
    Scored,
    #[sea_orm(string_value = "missing_input")]
    MissingInput,
    #[sea_orm(string_value = "not_applicable")]
    NotApplicable,
    #[sea_orm(string_value = "indeterminate")]
    Indeterminate,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feature_parity_latch_state"
)]
pub enum QpFeatureParityLatchState {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "clear")]
    Clear,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feature_parity_run_kind"
)]
pub enum QpFeatureParityRunKind {
    #[sea_orm(string_value = "sampled")]
    Sampled,
    #[sea_orm(string_value = "full")]
    Full,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feature_parity_run_status"
)]
pub enum QpFeatureParityRunStatus {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "pending_materialization")]
    PendingMaterialization,
    #[sea_orm(string_value = "passed")]
    Passed,
    #[sea_orm(string_value = "mismatched")]
    Mismatched,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feature_parity_state_transition"
)]
pub enum QpFeatureParityStateTransition {
    #[sea_orm(string_value = "bootstrap_proof")]
    BootstrapProof,
    #[sea_orm(string_value = "deterministic_mismatch")]
    DeterministicMismatch,
    #[sea_orm(string_value = "integrity_failure")]
    IntegrityFailure,
    #[sea_orm(string_value = "governed_acknowledge")]
    GovernedAcknowledge,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_kill_switch_state")]
pub enum QpKillSwitchState {
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "report_only_forced")]
    ReportOnlyForced,
    #[sea_orm(string_value = "execution_halted")]
    ExecutionHalted,
    #[sea_orm(string_value = "exit_only")]
    ExitOnly,
    #[sea_orm(string_value = "emergency_halted")]
    EmergencyHalted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_linkage_source_role"
)]
pub enum QpLinkageSourceRole {
    #[sea_orm(string_value = "feature")]
    Feature,
    #[sea_orm(string_value = "live_event")]
    LiveEvent,
    #[sea_orm(string_value = "resolution")]
    Resolution,
    #[sea_orm(string_value = "historical_calibration")]
    HistoricalCalibration,
    #[sea_orm(string_value = "forecast")]
    Forecast,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_linkage_status")]
pub enum QpLinkageStatus {
    #[sea_orm(string_value = "resolved")]
    Resolved,
    #[sea_orm(string_value = "unresolved")]
    Unresolved,
    #[sea_orm(string_value = "overridden")]
    Overridden,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_market_category")]
pub enum QpMarketCategory {
    #[sea_orm(string_value = "geopolitics")]
    Geopolitics,
    #[sea_orm(string_value = "sports")]
    Sports,
    #[sea_orm(string_value = "politics")]
    Politics,
    #[sea_orm(string_value = "finance")]
    Finance,
    #[sea_orm(string_value = "tech")]
    Tech,
    #[sea_orm(string_value = "culture")]
    Culture,
    #[sea_orm(string_value = "weather")]
    Weather,
    #[sea_orm(string_value = "economics")]
    Economics,
    #[sea_orm(string_value = "crypto")]
    Crypto,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_market_status")]
pub enum QpMarketStatus {
    #[sea_orm(string_value = "discovered")]
    Discovered,
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "filtered")]
    Filtered,
    #[sea_orm(string_value = "paused")]
    Paused,
    #[sea_orm(string_value = "manually_blocked")]
    ManuallyBlocked,
    #[sea_orm(string_value = "settled")]
    Settled,
    #[sea_orm(string_value = "delisted")]
    Delisted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_menu_kind")]
pub enum QpMenuKind {
    #[sea_orm(string_value = "directory")]
    Directory,
    #[sea_orm(string_value = "menu")]
    Menu,
    #[sea_orm(string_value = "button")]
    Button,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_model_family")]
pub enum QpModelFamily {
    #[sea_orm(string_value = "weighted_factor")]
    WeightedFactor,
    #[sea_orm(string_value = "classical_random_forest")]
    ClassicalRandomForest,
    #[sea_orm(string_value = "classical_extra_trees")]
    ClassicalExtraTrees,
    #[sea_orm(string_value = "classical_logistic_regression")]
    ClassicalLogisticRegression,
    #[sea_orm(string_value = "classical_ridge")]
    ClassicalRidge,
    #[sea_orm(string_value = "classical_lasso")]
    ClassicalLasso,
    #[sea_orm(string_value = "classical_elastic_net")]
    ClassicalElasticNet,
    #[sea_orm(string_value = "hold_vs_exit_weighted")]
    HoldVsExitWeighted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_model_governance_action"
)]
pub enum QpModelGovernanceAction {
    #[sea_orm(string_value = "publish")]
    Publish,
    #[sea_orm(string_value = "retire")]
    Retire,
    #[sea_orm(string_value = "rollback")]
    Rollback,
    #[sea_orm(string_value = "bind_calibration")]
    BindCalibration,
    #[sea_orm(string_value = "bind_publish_path_set")]
    BindPublishPathSet,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_model_version_derivation_kind"
)]
pub enum QpModelVersionDerivationKind {
    #[sea_orm(string_value = "training")]
    Training,
    #[sea_orm(string_value = "score_multiplier_calibration")]
    ScoreMultiplierCalibration,
    #[sea_orm(string_value = "return_calibration")]
    ReturnCalibration,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_model_run_error_code"
)]
pub enum QpModelRunErrorCode {
    #[sea_orm(string_value = "active_inference_failed")]
    ActiveInferenceFailed,
    #[sea_orm(string_value = "shadow_inference_failed")]
    ShadowInferenceFailed,
    #[sea_orm(string_value = "feature_plane_failed")]
    FeaturePlaneFailed,
    #[sea_orm(string_value = "factor_plane_failed")]
    FactorPlaneFailed,
    #[sea_orm(string_value = "selection_failed")]
    SelectionFailed,
    #[sea_orm(string_value = "artifact_load_failed")]
    ArtifactLoadFailed,
    #[sea_orm(string_value = "schema_binding_failed")]
    SchemaBindingFailed,
    #[sea_orm(string_value = "training_failed")]
    TrainingFailed,
    #[sea_orm(string_value = "cancelled_by_operator")]
    CancelledByOperator,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_model_weight_source"
)]
pub enum QpModelWeightSource {
    #[sea_orm(string_value = "artifact")]
    Artifact,
    #[sea_orm(string_value = "config_overlay")]
    ConfigOverlay,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_model_run_kind")]
pub enum QpModelRunKind {
    #[sea_orm(string_value = "training")]
    Training,
    #[sea_orm(string_value = "backtest")]
    Backtest,
    #[sea_orm(string_value = "cpcv")]
    Cpcv,
    #[sea_orm(string_value = "shadow")]
    Shadow,
    #[sea_orm(string_value = "live_inference")]
    LiveInference,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_model_run_status")]
pub enum QpModelRunStatus {
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_normalization_source"
)]
pub enum QpNormalizationSource {
    #[sea_orm(string_value = "cross_section")]
    CrossSection,
    #[sea_orm(string_value = "per_market")]
    PerMarket,
    #[sea_orm(string_value = "frozen_reference_quantile")]
    FrozenReferenceQuantile,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_operation_category"
)]
pub enum QpOperationCategory {
    #[sea_orm(string_value = "auth")]
    Auth,
    #[sea_orm(string_value = "rbac")]
    Rbac,
    #[sea_orm(string_value = "governance")]
    Governance,
    #[sea_orm(string_value = "config")]
    Config,
    #[sea_orm(string_value = "config_lifecycle")]
    ConfigLifecycle,
    #[sea_orm(string_value = "system")]
    System,
    #[sea_orm(string_value = "risk")]
    Risk,
    #[sea_orm(string_value = "quant_report")]
    QuantReport,
    #[sea_orm(string_value = "market")]
    Market,
    #[sea_orm(string_value = "replay")]
    Replay,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_operation_http_method"
)]
pub enum QpOperationHttpMethod {
    #[sea_orm(string_value = "GET")]
    Get,
    #[sea_orm(string_value = "POST")]
    Post,
    #[sea_orm(string_value = "PUT")]
    Put,
    #[sea_orm(string_value = "PATCH")]
    Patch,
    #[sea_orm(string_value = "DELETE")]
    Delete,
    #[sea_orm(string_value = "SYSTEM")]
    System,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_operation_outcome")]
pub enum QpOperationOutcome {
    #[sea_orm(string_value = "success")]
    Success,
    #[sea_orm(string_value = "failure")]
    Failure,
    #[sea_orm(string_value = "denied")]
    Denied,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_order_intent_kind")]
pub enum QpOrderIntentKind {
    #[sea_orm(string_value = "buy")]
    Buy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_order_intent_status"
)]
pub enum QpOrderIntentStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "pending_approval")]
    PendingApproval,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "approved_by_policy")]
    ApprovedByPolicy,
    #[sea_orm(string_value = "admission_pending")]
    AdmissionPending,
    #[sea_orm(string_value = "admission_rejected")]
    AdmissionRejected,
    #[sea_orm(string_value = "submitted")]
    Submitted,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "filled")]
    Filled,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "invalidated")]
    Invalidated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_order_type_kind")]
pub enum QpOrderTypeKind {
    #[sea_orm(string_value = "fok")]
    Fok,
    #[sea_orm(string_value = "fak")]
    Fak,
    #[sea_orm(string_value = "gtc")]
    Gtc,
    #[sea_orm(string_value = "gtd")]
    Gtd,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_outcome_side")]
pub enum QpOutcomeSide {
    #[sea_orm(string_value = "yes")]
    Yes,
    #[sea_orm(string_value = "no")]
    No,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_parity_subject_kind"
)]
pub enum QpParitySubjectKind {
    #[sea_orm(string_value = "recommendation_report")]
    RecommendationReport,
    #[sea_orm(string_value = "model_run")]
    ModelRun,
    #[sea_orm(string_value = "model_version")]
    ModelVersion,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_policy_activation_kind"
)]
pub enum QpPolicyActivationKind {
    #[sea_orm(string_value = "initial")]
    Initial,
    #[sea_orm(string_value = "promote")]
    Promote,
    #[sea_orm(string_value = "rollback")]
    Rollback,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_policy_actor_kind")]
pub enum QpPolicyActorKind {
    #[sea_orm(string_value = "operator")]
    Operator,
    #[sea_orm(string_value = "system")]
    System,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_policy_approval_decision"
)]
pub enum QpPolicyApprovalDecision {
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "rejected")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_policy_revision_status"
)]
pub enum QpPolicyRevisionStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "validated")]
    Validated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_position_ledger_state"
)]
pub enum QpPositionLedgerState {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "closing")]
    Closing,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "settled")]
    Settled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_publication_status"
)]
pub enum QpPublicationStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "candidate")]
    Candidate,
    #[sea_orm(string_value = "shadow")]
    Shadow,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "retired")]
    Retired,
    #[sea_orm(string_value = "rejected")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_quant_runtime_mode"
)]
pub enum QpQuantRuntimeMode {
    #[sea_orm(string_value = "report_only")]
    ReportOnly,
    #[sea_orm(string_value = "semi_auto")]
    SemiAuto,
    #[sea_orm(string_value = "auto_execution")]
    AutoExecution,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_recommendation_attribution_outcome"
)]
pub enum QpRecommendationAttributionOutcome {
    #[sea_orm(string_value = "filled_exited")]
    FilledExited,
    #[sea_orm(string_value = "filled_settled")]
    FilledSettled,
    #[sea_orm(string_value = "expired_unfilled")]
    ExpiredUnfilled,
    #[sea_orm(string_value = "superseded_unfilled")]
    SupersededUnfilled,
    #[sea_orm(string_value = "cancelled_unfilled")]
    CancelledUnfilled,
    #[sea_orm(string_value = "failed_unfilled")]
    FailedUnfilled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_recommendation_report_status"
)]
pub enum QpRecommendationReportStatus {
    #[sea_orm(string_value = "prepared")]
    Prepared,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "superseded")]
    Superseded,
    #[sea_orm(string_value = "obsolete")]
    Obsolete,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "expired")]
    Expired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_recommendation_status"
)]
pub enum QpRecommendationStatus {
    #[sea_orm(string_value = "prepared")]
    Prepared,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "superseded")]
    Superseded,
    #[sea_orm(string_value = "obsolete")]
    Obsolete,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "intent_created")]
    IntentCreated,
    #[sea_orm(string_value = "executed")]
    Executed,
    #[sea_orm(string_value = "attributed")]
    Attributed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_reconciliation_result"
)]
pub enum QpReconciliationResult {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "filled")]
    Filled,
    #[sea_orm(string_value = "not_filled")]
    NotFilled,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "unresolvable")]
    Unresolvable,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_report_fact_delivery_status"
)]
pub enum QpReportFactDeliveryStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "delivering")]
    Delivering,
    #[sea_orm(string_value = "retrying")]
    Retrying,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "verified")]
    Verified,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_report_kind")]
pub enum QpReportKind {
    #[sea_orm(string_value = "top_n")]
    TopN,
    #[sea_orm(string_value = "shadow_top_n")]
    ShadowTopN,
    #[sea_orm(string_value = "post_run_audit")]
    PostRunAudit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_report_run_status")]
pub enum QpReportRunStatus {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "skipped")]
    Skipped,
    #[sea_orm(string_value = "abandoned")]
    Abandoned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_report_run_terminal_reason"
)]
pub enum QpReportRunTerminalReason {
    #[sea_orm(string_value = "coalesced_by_newer_occurrence")]
    CoalescedByNewerOccurrence,
    #[sea_orm(string_value = "schedule_reconfigured")]
    ScheduleReconfigured,
    #[sea_orm(string_value = "queue_expired")]
    QueueExpired,
    #[sea_orm(string_value = "build_failed")]
    BuildFailed,
    #[sea_orm(string_value = "lease_expired")]
    LeaseExpired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_report_schedule_gap_reason"
)]
pub enum QpReportScheduleGapReason {
    #[sea_orm(string_value = "coordinator_lag")]
    CoordinatorLag,
    #[sea_orm(string_value = "coalesced_by_newer_occurrence")]
    CoalescedByNewerOccurrence,
    #[sea_orm(string_value = "schedule_reconfigured")]
    ScheduleReconfigured,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_report_trigger_kind"
)]
pub enum QpReportTriggerKind {
    #[sea_orm(string_value = "scheduled")]
    Scheduled,
    #[sea_orm(string_value = "ad_hoc")]
    AdHoc,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_research_job_kind")]
pub enum QpResearchJobKind {
    #[sea_orm(string_value = "dataset_build")]
    DatasetBuild,
    #[sea_orm(string_value = "model_train")]
    ModelTrain,
    #[sea_orm(string_value = "backtest")]
    Backtest,
    #[sea_orm(string_value = "bias_table_fit")]
    BiasTableFit,
    #[sea_orm(string_value = "model_calibration_fit")]
    ModelCalibrationFit,
    #[sea_orm(string_value = "cpcv_backtest")]
    CpcvBacktest,
    #[sea_orm(string_value = "feature_parity")]
    FeatureParity,
    #[sea_orm(string_value = "trade_policy_fit")]
    TradePolicyFit,
    #[sea_orm(string_value = "trade_policy_validation")]
    TradePolicyValidation,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_research_job_status"
)]
pub enum QpResearchJobStatus {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_research_readiness_evidence_kind"
)]
pub enum QpResearchReadinessEvidenceKind {
    #[sea_orm(string_value = "retention_runway")]
    RetentionRunway,
    #[sea_orm(string_value = "shadow_latency_profile")]
    ShadowLatencyProfile,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_production_evidence_kind"
)]
pub enum QpProductionEvidenceKind {
    #[sea_orm(string_value = "backup_restore")]
    BackupRestore,
    #[sea_orm(string_value = "protected_config_end_to_end")]
    ProtectedConfigEndToEnd,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_resolver_tier")]
pub enum QpResolverTier {
    #[sea_orm(string_value = "tier0_slug")]
    Tier0Slug,
    #[sea_orm(string_value = "tier1_template")]
    Tier1Template,
    #[sea_orm(string_value = "override")]
    Override,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_resource_type")]
pub enum QpResourceType {
    #[sea_orm(string_value = "system")]
    System,
    #[sea_orm(string_value = "market")]
    Market,
    #[sea_orm(string_value = "config")]
    Config,
    #[sea_orm(string_value = "config_lifecycle")]
    ConfigLifecycle,
    #[sea_orm(string_value = "publication")]
    Publication,
    #[sea_orm(string_value = "materialization")]
    Materialization,
    #[sea_orm(string_value = "replay")]
    Replay,
    #[sea_orm(string_value = "quant_report")]
    QuantReport,
    #[sea_orm(string_value = "account_snapshot")]
    AccountSnapshot,
    #[sea_orm(string_value = "equity_snapshot")]
    EquitySnapshot,
    #[sea_orm(string_value = "order_intent")]
    OrderIntent,
    #[sea_orm(string_value = "execution_order")]
    ExecutionOrder,
    #[sea_orm(string_value = "position")]
    Position,
    #[sea_orm(string_value = "recommendation_attribution")]
    RecommendationAttribution,
    #[sea_orm(string_value = "reconciliation")]
    Reconciliation,
    #[sea_orm(string_value = "settlement_redeem")]
    SettlementRedeem,
    #[sea_orm(string_value = "factor_definition")]
    FactorDefinition,
    #[sea_orm(string_value = "operation_log")]
    OperationLog,
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "role")]
    Role,
    #[sea_orm(string_value = "menu")]
    Menu,
    #[sea_orm(string_value = "permission")]
    Permission,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_role_kind")]
pub enum QpRoleKind {
    #[sea_orm(string_value = "builtin")]
    Builtin,
    #[sea_orm(string_value = "custom")]
    Custom,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_role_status")]
pub enum QpRoleStatus {
    #[sea_orm(string_value = "enabled")]
    Enabled,
    #[sea_orm(string_value = "disabled")]
    Disabled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_redeem_state"
)]
pub enum QpSettlementRedeemState {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "submitted")]
    Submitted,
    #[sea_orm(string_value = "confirmed")]
    Confirmed,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "manual_required")]
    ManualRequired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_side")]
pub enum QpSide {
    #[sea_orm(string_value = "BUY")]
    Buy,
    #[sea_orm(string_value = "SELL")]
    Sell,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_source_slice_status"
)]
pub enum QpSourceSliceStatus {
    #[sea_orm(string_value = "materializing")]
    Materializing,
    #[sea_orm(string_value = "ready")]
    Ready,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_tick_size")]
pub enum QpTickSize {
    #[sea_orm(string_value = "0.1")]
    _0U002E1,
    #[sea_orm(string_value = "0.01")]
    _0U002E01,
    #[sea_orm(string_value = "0.005")]
    _0U002E005,
    #[sea_orm(string_value = "0.0025")]
    _0U002E0025,
    #[sea_orm(string_value = "0.001")]
    _0U002E001,
    #[sea_orm(string_value = "0.0001")]
    _0U002E0001,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_governance_action"
)]
pub enum QpTradePolicyGovernanceAction {
    #[sea_orm(string_value = "validate")]
    Validate,
    #[sea_orm(string_value = "publish")]
    Publish,
    #[sea_orm(string_value = "retire")]
    Retire,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_status"
)]
pub enum QpTradePolicyStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "validated")]
    Validated,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "retired")]
    Retired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_trial_scope"
)]
pub enum QpTradePolicyTrialScope {
    #[sea_orm(string_value = "candidate")]
    Candidate,
    #[sea_orm(string_value = "fold")]
    Fold,
    #[sea_orm(string_value = "path")]
    Path,
    #[sea_orm(string_value = "latency_stress")]
    LatencyStress,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_trial_status"
)]
pub enum QpTradePolicyTrialStatus {
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_validation_status"
)]
pub enum QpTradePolicyValidationStatus {
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_training_dataset_status"
)]
pub enum QpTrainingDatasetStatus {
    #[sea_orm(string_value = "planned")]
    Planned,
    #[sea_orm(string_value = "building")]
    Building,
    #[sea_orm(string_value = "insufficient_labels")]
    InsufficientLabels,
    #[sea_orm(string_value = "ready")]
    Ready,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_user_status")]
pub enum QpUserStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "disabled")]
    Disabled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_venue_order_status"
)]
pub enum QpVenueOrderStatus {
    #[sea_orm(string_value = "filled")]
    Filled,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "expired")]
    Expired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_weather_temperature_statistic"
)]
pub enum QpWeatherTemperatureStatistic {
    #[sea_orm(string_value = "maximum")]
    Maximum,
    #[sea_orm(string_value = "minimum")]
    Minimum,
}
