//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_account_chain_execution_role"
)]
pub enum QpAccountChainExecutionRole {
    #[sea_orm(string_value = "maker")]
    Maker,
    #[sea_orm(string_value = "taker")]
    Taker,
    #[sea_orm(string_value = "self_match")]
    SelfMatch,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_account_execution_association_kind"
)]
pub enum QpAccountExecutionAssociationKind {
    #[sea_orm(string_value = "system_order")]
    SystemOrder,
    #[sea_orm(string_value = "recovery_incident")]
    RecoveryIncident,
    #[sea_orm(string_value = "opening_inventory")]
    OpeningInventory,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_account_pause_operation_state"
)]
pub enum QpAccountPauseOperationState {
    #[sea_orm(string_value = "prepared")]
    Prepared,
    #[sea_orm(string_value = "dispatched")]
    Dispatched,
    #[sea_orm(string_value = "ambiguous")]
    Ambiguous,
    #[sea_orm(string_value = "confirmed")]
    Confirmed,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_account_recovery_incident_kind"
)]
pub enum QpAccountRecoveryIncidentKind {
    #[sea_orm(string_value = "unknown_external_execution")]
    UnknownExternalExecution,
    #[sea_orm(string_value = "break_glass_restart")]
    BreakGlassRestart,
    #[sea_orm(string_value = "opening_inventory")]
    OpeningInventory,
    #[sea_orm(string_value = "account_mismatch")]
    AccountMismatch,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_account_recovery_incident_status"
)]
pub enum QpAccountRecoveryIncidentStatus {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "reconciling")]
    Reconciling,
    #[sea_orm(string_value = "sealed")]
    Sealed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_strategy_position_origin_kind"
)]
pub enum QpStrategyPositionOriginKind {
    #[sea_orm(string_value = "system_intent")]
    SystemIntent,
    #[sea_orm(string_value = "account_recovery_incident")]
    AccountRecoveryIncident,
    #[sea_orm(string_value = "opening_inventory")]
    OpeningInventory,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_account_source")]
pub enum QpAccountSource {
    #[sea_orm(string_value = "polymarket")]
    Polymarket,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_authorization_kind"
)]
pub enum QpAuthorizationKind {
    #[sea_orm(string_value = "operator_approval")]
    OperatorApproval,
    #[sea_orm(string_value = "active_policy")]
    ActivePolicy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_exit_settlement_mode"
)]
pub enum QpExitSettlementMode {
    #[sea_orm(string_value = "hold_to_resolution")]
    HoldToResolution,
    #[sea_orm(string_value = "exit_before_resolution")]
    ExitBeforeResolution,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_redeem_policy")]
pub enum QpRedeemPolicy {
    #[sea_orm(string_value = "manual")]
    Manual,
    #[sea_orm(string_value = "auto")]
    Auto,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_calibration_kind")]
pub enum QpCalibrationKind {
    #[sea_orm(string_value = "model_score")]
    ModelScore,
    #[sea_orm(string_value = "market_price_bias")]
    MarketPriceBias,
    #[sea_orm(string_value = "weather_station_lead_bias")]
    WeatherStationLeadBias,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_capital_allocation_state"
)]
pub enum QpCapitalAllocationState {
    #[sea_orm(string_value = "allocated")]
    Allocated,
    #[sea_orm(string_value = "locked")]
    Locked,
    #[sea_orm(string_value = "spent")]
    Spent,
    #[sea_orm(string_value = "released")]
    Released,
    #[sea_orm(string_value = "impaired")]
    Impaired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_change_type"
)]
pub enum QpCatalogChangeType {
    #[sea_orm(string_value = "gamma_scan_upsert")]
    GammaScanUpsert,
    #[sea_orm(string_value = "gamma_id_recheck_upsert")]
    GammaIdRecheckUpsert,
    #[sea_orm(string_value = "gamma_confirmed_tombstone")]
    GammaConfirmedTombstone,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_entity_kind"
)]
pub enum QpCatalogEntityKind {
    #[sea_orm(string_value = "event")]
    Event,
    #[sea_orm(string_value = "market")]
    Market,
    #[sea_orm(string_value = "cursor")]
    Cursor,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_filter_reason"
)]
pub enum QpCatalogFilterReason {
    #[sea_orm(string_value = "inactive")]
    Inactive,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "clob_disabled")]
    ClobDisabled,
    #[sea_orm(string_value = "orders_not_accepted")]
    OrdersNotAccepted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_rejection_reason"
)]
pub enum QpCatalogRejectionReason {
    #[sea_orm(string_value = "empty_condition_id")]
    EmptyConditionId,
    #[sea_orm(string_value = "missing_clob_token_ids")]
    MissingClobTokenIds,
    #[sea_orm(string_value = "not_binary")]
    NotBinary,
    #[sea_orm(string_value = "invalid_token_pair")]
    InvalidTokenPair,
    #[sea_orm(string_value = "unsupported_tick_size")]
    UnsupportedTickSize,
    #[sea_orm(string_value = "invalid_fee_schedule")]
    InvalidFeeSchedule,
    #[sea_orm(string_value = "duplicate_entity_id")]
    DuplicateEntityId,
    #[sea_orm(string_value = "malformed_entity")]
    MalformedEntity,
    #[sea_orm(string_value = "cursor_protocol_violation")]
    CursorProtocolViolation,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_sync_failure_stage"
)]
pub enum QpCatalogSyncFailureStage {
    #[sea_orm(string_value = "fetch")]
    Fetch,
    #[sea_orm(string_value = "normalize")]
    Normalize,
    #[sea_orm(string_value = "persist")]
    Persist,
    #[sea_orm(string_value = "recovery")]
    Recovery,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_catalog_sync_kind")]
pub enum QpCatalogSyncKind {
    #[sea_orm(string_value = "baseline")]
    Baseline,
    #[sea_orm(string_value = "reconcile")]
    Reconcile,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_sync_status"
)]
pub enum QpCatalogSyncStatus {
    #[sea_orm(string_value = "committed")]
    Committed,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_catalog_timestamp_quality"
)]
pub enum QpCatalogTimestampQuality {
    #[sea_orm(string_value = "source")]
    Source,
    #[sea_orm(string_value = "commit_time_fallback")]
    CommitTimeFallback,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_config_resource_kind"
)]
pub enum QpConfigResourceKind {
    #[sea_orm(string_value = "recommendation_policy")]
    RecommendationPolicy,
    #[sea_orm(string_value = "execution_risk_policy")]
    ExecutionRiskPolicy,
    #[sea_orm(string_value = "model_routing")]
    ModelRouting,
    #[sea_orm(string_value = "report_schedule")]
    ReportSchedule,
    #[sea_orm(string_value = "operations_policy")]
    OperationsPolicy,
    #[sea_orm(string_value = "execution_authorization_policy")]
    ExecutionAuthorizationPolicy,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_data_quality_status"
)]
pub enum QpDataQualityStatus {
    #[sea_orm(string_value = "fresh")]
    Fresh,
    #[sea_orm(string_value = "acceptable")]
    Acceptable,
    #[sea_orm(string_value = "degraded")]
    Degraded,
    #[sea_orm(string_value = "stale")]
    Stale,
    #[sea_orm(string_value = "insufficient")]
    Insufficient,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_dataset_purpose")]
pub enum QpDatasetPurpose {
    #[sea_orm(string_value = "training")]
    Training,
    #[sea_orm(string_value = "calibration")]
    Calibration,
    #[sea_orm(string_value = "evaluation")]
    Evaluation,
    #[sea_orm(string_value = "policy_fit")]
    PolicyFit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_decision_policy_snapshot_source"
)]
pub enum QpDecisionPolicySnapshotSource {
    #[sea_orm(string_value = "bootstrap")]
    Bootstrap,
    #[sea_orm(string_value = "activation")]
    Activation,
    #[sea_orm(string_value = "rollback")]
    Rollback,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_profile_artifact_kind"
)]
pub enum QpProfileArtifactKind {
    #[sea_orm(string_value = "feature")]
    Feature,
    #[sea_orm(string_value = "scoring")]
    Scoring,
    #[sea_orm(string_value = "domain")]
    Domain,
    #[sea_orm(string_value = "research_method")]
    ResearchMethod,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_domain_cursor_status"
)]
pub enum QpDomainCursorStatus {
    #[sea_orm(string_value = "bootstrap")]
    Bootstrap,
    #[sea_orm(string_value = "backfilling")]
    Backfilling,
    #[sea_orm(string_value = "live")]
    Live,
    #[sea_orm(string_value = "error")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_domain_family")]
pub enum QpDomainFamily {
    #[sea_orm(string_value = "crypto")]
    Crypto,
    #[sea_orm(string_value = "weather")]
    Weather,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_domain_source_expectation_status"
)]
pub enum QpDomainSourceExpectationStatus {
    #[sea_orm(string_value = "not_started")]
    NotStarted,
    #[sea_orm(string_value = "live")]
    Live,
    #[sea_orm(string_value = "stale")]
    Stale,
    #[sea_orm(string_value = "credential_blocked")]
    CredentialBlocked,
    #[sea_orm(string_value = "error")]
    Failed,
    #[sea_orm(string_value = "unsupported")]
    Unsupported,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_entry_condition_audit_action"
)]
pub enum QpEntryConditionAuditAction {
    #[sea_orm(string_value = "created")]
    Created,
    #[sea_orm(string_value = "evaluated")]
    Evaluated,
    #[sea_orm(string_value = "lease_taken_over")]
    LeaseTakenOver,
    #[sea_orm(string_value = "claimed")]
    Claimed,
    #[sea_orm(string_value = "reverted")]
    Reverted,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "invalidated")]
    Invalidated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_entry_condition_state"
)]
pub enum QpEntryConditionState {
    #[sea_orm(string_value = "not_required")]
    NotRequired,
    #[sea_orm(string_value = "waiting")]
    Waiting,
    #[sea_orm(string_value = "unavailable")]
    Unavailable,
    #[sea_orm(string_value = "confirming")]
    Confirming,
    #[sea_orm(string_value = "qualified")]
    Qualified,
    #[sea_orm(string_value = "consumed")]
    Consumed,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "invalidated")]
    Invalidated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_event_status")]
pub enum QpEventStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "archived")]
    Archived,
    #[sea_orm(string_value = "unknown")]
    Unknown,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_execution_order_phase"
)]
pub enum QpExecutionOrderPhase {
    #[sea_orm(string_value = "entry")]
    Entry,
    #[sea_orm(string_value = "exit")]
    Exit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_fee_liquidity_role"
)]
pub enum QpFeeLiquidityRole {
    #[sea_orm(string_value = "taker")]
    Taker,
    #[sea_orm(string_value = "maker")]
    Maker,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_venue_incentive_kind"
)]
pub enum QpVenueIncentiveKind {
    #[sea_orm(string_value = "maker_rebate")]
    MakerRebate,
    #[sea_orm(string_value = "taker_rebate")]
    TakerRebate,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_venue_incentive_stage"
)]
pub enum QpVenueIncentiveStage {
    #[sea_orm(string_value = "estimated_accrual")]
    EstimatedAccrual,
    #[sea_orm(string_value = "venue_reported_accrual")]
    VenueReportedAccrual,
    #[sea_orm(string_value = "wallet_credited")]
    WalletCredited,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_venue_incentive_reconciliation_scan_status"
)]
pub enum QpVenueIncentiveReconciliationScanStatus {
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_execution_order_state"
)]
pub enum QpExecutionOrderState {
    #[sea_orm(string_value = "planned")]
    Planned,
    #[sea_orm(string_value = "accepted")]
    Accepted,
    #[sea_orm(string_value = "submitted")]
    Submitted,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "filled")]
    Filled,
    #[sea_orm(string_value = "cancel_requested")]
    CancelRequested,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "ambiguous")]
    Ambiguous,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_execution_wallet_kind"
)]
pub enum QpExecutionWalletKind {
    #[sea_orm(string_value = "eoa")]
    Eoa,
    #[sea_orm(string_value = "proxy")]
    Proxy,
    #[sea_orm(string_value = "gnosis_safe")]
    GnosisSafe,
    #[sea_orm(string_value = "deposit_wallet")]
    DepositWallet,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_exit_reason")]
pub enum QpExitReason {
    #[sea_orm(string_value = "take_profit")]
    TakeProfit,
    #[sea_orm(string_value = "stop_loss")]
    StopLoss,
    #[sea_orm(string_value = "time_exit")]
    TimeExit,
    #[sea_orm(string_value = "partial_exit")]
    PartialExit,
    #[sea_orm(string_value = "signal_invalidated")]
    SignalInvalidated,
    #[sea_orm(string_value = "opportunistic")]
    Opportunistic,
    #[sea_orm(string_value = "manual")]
    Manual,
    #[sea_orm(string_value = "settlement_hold")]
    SettlementHold,
    #[sea_orm(string_value = "resolution_redeem")]
    ResolutionRedeem,
    #[sea_orm(string_value = "kill_switch_emergency")]
    KillSwitchEmergency,
    #[sea_orm(string_value = "risk_envelope_breached")]
    RiskEnvelopeBreached,
    #[sea_orm(string_value = "market_abnormal")]
    MarketAbnormal,
    #[sea_orm(string_value = "data_stale")]
    DataStale,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_exit_state")]
pub enum QpExitState {
    #[sea_orm(string_value = "not_started")]
    NotStarted,
    #[sea_orm(string_value = "monitoring")]
    Monitoring,
    #[sea_orm(string_value = "triggered")]
    Triggered,
    #[sea_orm(string_value = "order_submitted")]
    OrderSubmitted,
    #[sea_orm(string_value = "partially_exited")]
    PartiallyExited,
    #[sea_orm(string_value = "exited")]
    Exited,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "manual_required")]
    ManualRequired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_factor_definition_scope"
)]
pub enum QpFactorDefinitionScope {
    #[sea_orm(string_value = "generic")]
    Generic,
    #[sea_orm(string_value = "structural")]
    Structural,
    #[sea_orm(string_value = "domain_crypto")]
    DomainCrypto,
    #[sea_orm(string_value = "domain_weather")]
    DomainWeather,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_factor_direction")]
pub enum QpFactorDirection {
    #[sea_orm(string_value = "positive")]
    Positive,
    #[sea_orm(string_value = "negative")]
    Negative,
    #[sea_orm(string_value = "neutral")]
    Neutral,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_factor_family")]
pub enum QpFactorFamily {
    #[sea_orm(string_value = "liquidity")]
    Liquidity,
    #[sea_orm(string_value = "microstructure")]
    Microstructure,
    #[sea_orm(string_value = "momentum")]
    Momentum,
    #[sea_orm(string_value = "mean_reversion")]
    MeanReversion,
    #[sea_orm(string_value = "volatility")]
    Volatility,
    #[sea_orm(string_value = "activity")]
    Activity,
    #[sea_orm(string_value = "resolution")]
    Resolution,
    #[sea_orm(string_value = "data_quality")]
    DataQuality,
    #[sea_orm(string_value = "structural")]
    Structural,
    #[sea_orm(string_value = "domain_crypto")]
    DomainCrypto,
    #[sea_orm(string_value = "domain_weather")]
    DomainWeather,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_factor_indeterminate_reason"
)]
pub enum QpFactorIndeterminateReason {
    #[sea_orm(string_value = "cross_section_too_small")]
    CrossSectionTooSmall,
    #[sea_orm(string_value = "zero_variance")]
    ZeroVariance,
    #[sea_orm(string_value = "no_frozen_reference")]
    NoFrozenReference,
    #[sea_orm(string_value = "leg_book_missing")]
    LegBookMissing,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_factor_value_state"
)]
pub enum QpFactorValueState {
    #[sea_orm(string_value = "scored")]
    Scored,
    #[sea_orm(string_value = "missing_input")]
    MissingInput,
    #[sea_orm(string_value = "not_applicable")]
    NotApplicable,
    #[sea_orm(string_value = "indeterminate")]
    Indeterminate,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feature_parity_latch_state"
)]
pub enum QpFeatureParityLatchState {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "clear")]
    Clear,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feature_parity_run_kind"
)]
pub enum QpFeatureParityRunKind {
    #[sea_orm(string_value = "sampled")]
    Sampled,
    #[sea_orm(string_value = "full")]
    Full,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feature_parity_run_status"
)]
pub enum QpFeatureParityRunStatus {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "pending_materialization")]
    PendingMaterialization,
    #[sea_orm(string_value = "passed")]
    Passed,
    #[sea_orm(string_value = "mismatched")]
    Mismatched,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feature_parity_state_transition"
)]
pub enum QpFeatureParityStateTransition {
    #[sea_orm(string_value = "bootstrap_proof")]
    BootstrapProof,
    #[sea_orm(string_value = "deterministic_mismatch")]
    DeterministicMismatch,
    #[sea_orm(string_value = "integrity_failure")]
    IntegrityFailure,
    #[sea_orm(string_value = "governed_acknowledge")]
    GovernedAcknowledge,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_kill_switch_state")]
pub enum QpKillSwitchState {
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "execution_halted")]
    ExecutionHalted,
    #[sea_orm(string_value = "exit_only")]
    ExitOnly,
    #[sea_orm(string_value = "emergency_halted")]
    EmergencyHalted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_linkage_source_role"
)]
pub enum QpLinkageSourceRole {
    #[sea_orm(string_value = "feature")]
    Feature,
    #[sea_orm(string_value = "live_event")]
    LiveEvent,
    #[sea_orm(string_value = "resolution")]
    Resolution,
    #[sea_orm(string_value = "historical_calibration")]
    HistoricalCalibration,
    #[sea_orm(string_value = "forecast")]
    Forecast,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_linkage_status")]
pub enum QpLinkageStatus {
    #[sea_orm(string_value = "resolved")]
    Resolved,
    #[sea_orm(string_value = "unresolved")]
    Unresolved,
    #[sea_orm(string_value = "overridden")]
    Overridden,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_market_category")]
pub enum QpMarketCategory {
    #[sea_orm(string_value = "geopolitics")]
    Geopolitics,
    #[sea_orm(string_value = "sports")]
    Sports,
    #[sea_orm(string_value = "politics")]
    Politics,
    #[sea_orm(string_value = "finance")]
    Finance,
    #[sea_orm(string_value = "tech")]
    Tech,
    #[sea_orm(string_value = "culture")]
    Culture,
    #[sea_orm(string_value = "weather")]
    Weather,
    #[sea_orm(string_value = "economics")]
    Economics,
    #[sea_orm(string_value = "crypto")]
    Crypto,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_market_status")]
pub enum QpMarketStatus {
    #[sea_orm(string_value = "discovered")]
    Discovered,
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "filtered")]
    Filtered,
    #[sea_orm(string_value = "paused")]
    Paused,
    #[sea_orm(string_value = "manually_blocked")]
    ManuallyBlocked,
    #[sea_orm(string_value = "settled")]
    Settled,
    #[sea_orm(string_value = "delisted")]
    Delisted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_menu_kind")]
pub enum QpMenuKind {
    #[sea_orm(string_value = "directory")]
    Directory,
    #[sea_orm(string_value = "menu")]
    Menu,
    #[sea_orm(string_value = "button")]
    Button,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_fresh_boot_stage")]
pub enum QpFreshBootStage {
    #[sea_orm(string_value = "awaiting_source_coverage")]
    AwaitingSourceCoverage,
    #[sea_orm(string_value = "dataset_queued")]
    DatasetQueued,
    #[sea_orm(string_value = "dataset_running")]
    DatasetRunning,
    #[sea_orm(string_value = "dataset_ready")]
    DatasetReady,
    #[sea_orm(string_value = "training_queued")]
    TrainingQueued,
    #[sea_orm(string_value = "training_running")]
    TrainingRunning,
    #[sea_orm(string_value = "training_ready")]
    TrainingReady,
    #[sea_orm(string_value = "calibration_dataset_queued")]
    CalibrationDatasetQueued,
    #[sea_orm(string_value = "calibration_dataset_running")]
    CalibrationDatasetRunning,
    #[sea_orm(string_value = "calibration_dataset_ready")]
    CalibrationDatasetReady,
    #[sea_orm(string_value = "calibration_queued")]
    CalibrationQueued,
    #[sea_orm(string_value = "calibration_running")]
    CalibrationRunning,
    #[sea_orm(string_value = "calibration_ready")]
    CalibrationReady,
    #[sea_orm(string_value = "cpcv_queued")]
    CpcvQueued,
    #[sea_orm(string_value = "cpcv_running")]
    CpcvRunning,
    #[sea_orm(string_value = "cpcv_ready")]
    CpcvReady,
    #[sea_orm(string_value = "parity_ready")]
    ParityReady,
    #[sea_orm(string_value = "scenario_ready")]
    ScenarioReady,
    #[sea_orm(string_value = "bootstrap_preflight")]
    BootstrapPreflight,
    #[sea_orm(string_value = "bootstrap_committed")]
    BootstrapCommitted,
    #[sea_orm(string_value = "first_report_queued")]
    FirstReportQueued,
    #[sea_orm(string_value = "first_report_published")]
    FirstReportPublished,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_fresh_boot_status")]
pub enum QpFreshBootStatus {
    #[sea_orm(string_value = "waiting_evidence")]
    WaitingEvidence,
    #[sea_orm(string_value = "retry_scheduled")]
    RetryScheduled,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "blocked_terminal")]
    BlockedTerminal,
    #[sea_orm(string_value = "superseded")]
    Superseded,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_fresh_boot_event_kind"
)]
pub enum QpFreshBootEventKind {
    #[sea_orm(string_value = "run_created")]
    RunCreated,
    #[sea_orm(string_value = "source_coverage_satisfied")]
    SourceCoverageSatisfied,
    #[sea_orm(string_value = "dataset_started")]
    DatasetStarted,
    #[sea_orm(string_value = "dataset_completed")]
    DatasetCompleted,
    #[sea_orm(string_value = "training_enqueued")]
    TrainingEnqueued,
    #[sea_orm(string_value = "training_started")]
    TrainingStarted,
    #[sea_orm(string_value = "training_completed")]
    TrainingCompleted,
    #[sea_orm(string_value = "calibration_dataset_enqueued")]
    CalibrationDatasetEnqueued,
    #[sea_orm(string_value = "calibration_dataset_started")]
    CalibrationDatasetStarted,
    #[sea_orm(string_value = "calibration_dataset_completed")]
    CalibrationDatasetCompleted,
    #[sea_orm(string_value = "calibration_enqueued")]
    CalibrationEnqueued,
    #[sea_orm(string_value = "calibration_started")]
    CalibrationStarted,
    #[sea_orm(string_value = "calibration_completed")]
    CalibrationCompleted,
    #[sea_orm(string_value = "cpcv_enqueued")]
    CpcvEnqueued,
    #[sea_orm(string_value = "cpcv_started")]
    CpcvStarted,
    #[sea_orm(string_value = "cpcv_completed")]
    CpcvCompleted,
    #[sea_orm(string_value = "parity_verified")]
    ParityVerified,
    #[sea_orm(string_value = "scenario_bound")]
    ScenarioBound,
    #[sea_orm(string_value = "bootstrap_prepared")]
    BootstrapPrepared,
    #[sea_orm(string_value = "preflight_refreshed")]
    PreflightRefreshed,
    #[sea_orm(string_value = "bootstrap_committed")]
    BootstrapCommitted,
    #[sea_orm(string_value = "report_enabled")]
    ReportEnabled,
    #[sea_orm(string_value = "report_retried")]
    ReportRetried,
    #[sea_orm(string_value = "report_published")]
    ReportPublished,
    #[sea_orm(string_value = "evidence_wait_scheduled")]
    EvidenceWaitScheduled,
    #[sea_orm(string_value = "retry_scheduled")]
    RetryScheduled,
    #[sea_orm(string_value = "retry_started")]
    RetryStarted,
    #[sea_orm(string_value = "terminal_blocked")]
    TerminalBlocked,
    #[sea_orm(string_value = "retry_accelerated")]
    RetryAccelerated,
    #[sea_orm(string_value = "superseded")]
    Superseded,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_fresh_boot_retry_reason"
)]
pub enum QpFreshBootRetryReason {
    #[sea_orm(string_value = "source_coverage_incomplete")]
    SourceCoverageIncomplete,
    #[sea_orm(string_value = "dependency_unavailable")]
    DependencyUnavailable,
    #[sea_orm(string_value = "storage_transient")]
    StorageTransient,
    #[sea_orm(string_value = "provider_unavailable")]
    ProviderUnavailable,
    #[sea_orm(string_value = "job_retry_scheduled")]
    JobRetryScheduled,
    #[sea_orm(string_value = "preflight_stale")]
    PreflightStale,
    #[sea_orm(string_value = "report_pending")]
    ReportPending,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_fresh_boot_blocked_reason"
)]
pub enum QpFreshBootBlockedReason {
    #[sea_orm(string_value = "provider_mismatch")]
    ProviderMismatch,
    #[sea_orm(string_value = "unknown_token")]
    UnknownToken,
    #[sea_orm(string_value = "decode_failure")]
    DecodeFailure,
    #[sea_orm(string_value = "history_quarantined")]
    HistoryQuarantined,
    #[sea_orm(string_value = "insufficient_mature_labels")]
    InsufficientMatureLabels,
    #[sea_orm(string_value = "dataset_build_failed")]
    DatasetBuildFailed,
    #[sea_orm(string_value = "model_training_failed")]
    ModelTrainingFailed,
    #[sea_orm(string_value = "calibration_failed")]
    CalibrationFailed,
    #[sea_orm(string_value = "cpcv_failed")]
    CpcvFailed,
    #[sea_orm(string_value = "quality_gate_failed")]
    QualityGateFailed,
    #[sea_orm(string_value = "parity_failed")]
    ParityFailed,
    #[sea_orm(string_value = "scenario_binding_failed")]
    ScenarioBindingFailed,
    #[sea_orm(string_value = "bootstrap_conflict")]
    BootstrapConflict,
    #[sea_orm(string_value = "report_enqueue_failed")]
    ReportEnqueueFailed,
    #[sea_orm(string_value = "report_publication_failed")]
    ReportPublicationFailed,
    #[sea_orm(string_value = "policy_unavailable")]
    PolicyUnavailable,
    #[sea_orm(string_value = "source_slice_mismatch")]
    SourceSliceMismatch,
    #[sea_orm(string_value = "retry_budget_exhausted")]
    RetryBudgetExhausted,
    #[sea_orm(string_value = "source_coverage_invalid")]
    SourceCoverageInvalid,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_model_family")]
pub enum QpModelFamily {
    #[sea_orm(string_value = "weighted_factor")]
    WeightedFactor,
    #[sea_orm(string_value = "classical_logistic_regression")]
    ClassicalLogisticRegression,
    #[sea_orm(string_value = "hold_vs_exit_weighted")]
    HoldVsExitWeighted,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_model_governance_action"
)]
pub enum QpModelGovernanceAction {
    #[sea_orm(string_value = "bootstrap_route")]
    BootstrapRoute,
    #[sea_orm(string_value = "promote_route")]
    PromoteRoute,
    #[sea_orm(string_value = "seal_calibration")]
    SealCalibration,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_model_version_derivation_kind"
)]
pub enum QpModelVersionDerivationKind {
    #[sea_orm(string_value = "training")]
    Training,
    #[sea_orm(string_value = "return_calibration")]
    ReturnCalibration,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_model_run_error_code"
)]
pub enum QpModelRunErrorCode {
    #[sea_orm(string_value = "active_inference_failed")]
    ActiveInferenceFailed,
    #[sea_orm(string_value = "shadow_inference_failed")]
    ShadowInferenceFailed,
    #[sea_orm(string_value = "feature_plane_failed")]
    FeaturePlaneFailed,
    #[sea_orm(string_value = "factor_plane_failed")]
    FactorPlaneFailed,
    #[sea_orm(string_value = "selection_failed")]
    SelectionFailed,
    #[sea_orm(string_value = "artifact_load_failed")]
    ArtifactLoadFailed,
    #[sea_orm(string_value = "schema_binding_failed")]
    SchemaBindingFailed,
    #[sea_orm(string_value = "training_failed")]
    TrainingFailed,
    #[sea_orm(string_value = "calibration_failed")]
    CalibrationFailed,
    #[sea_orm(string_value = "cancelled_by_operator")]
    CancelledByOperator,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_model_weight_source"
)]
pub enum QpModelWeightSource {
    #[sea_orm(string_value = "artifact")]
    Artifact,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_model_run_kind")]
pub enum QpModelRunKind {
    #[sea_orm(string_value = "training")]
    Training,
    #[sea_orm(string_value = "backtest")]
    Backtest,
    #[sea_orm(string_value = "calibration")]
    Calibration,
    #[sea_orm(string_value = "cpcv")]
    Cpcv,
    #[sea_orm(string_value = "shadow")]
    Shadow,
    #[sea_orm(string_value = "live_inference")]
    LiveInference,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_feedback_cohort")]
pub enum QpFeedbackCohort {
    #[sea_orm(string_value = "model_learning")]
    ModelLearning,
    #[sea_orm(string_value = "model_score_learning")]
    ModelScoreLearning,
    #[sea_orm(string_value = "execution_learning")]
    ExecutionLearning,
    #[sea_orm(string_value = "policy_evaluation")]
    PolicyEvaluation,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_model_run_status")]
pub enum QpModelRunStatus {
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_normalization_source"
)]
pub enum QpNormalizationSource {
    #[sea_orm(string_value = "cross_section")]
    CrossSection,
    #[sea_orm(string_value = "per_market")]
    PerMarket,
    #[sea_orm(string_value = "frozen_reference_quantile")]
    FrozenReferenceQuantile,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_operation_category"
)]
pub enum QpOperationCategory {
    #[sea_orm(string_value = "auth")]
    Auth,
    #[sea_orm(string_value = "rbac")]
    Rbac,
    #[sea_orm(string_value = "governance")]
    Governance,
    #[sea_orm(string_value = "config")]
    Config,
    #[sea_orm(string_value = "system")]
    System,
    #[sea_orm(string_value = "risk")]
    Risk,
    #[sea_orm(string_value = "quant_report")]
    QuantReport,
    #[sea_orm(string_value = "market")]
    Market,
    #[sea_orm(string_value = "replay")]
    Replay,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_operation_http_method"
)]
pub enum QpOperationHttpMethod {
    #[sea_orm(string_value = "GET")]
    Get,
    #[sea_orm(string_value = "POST")]
    Post,
    #[sea_orm(string_value = "PUT")]
    Put,
    #[sea_orm(string_value = "PATCH")]
    Patch,
    #[sea_orm(string_value = "DELETE")]
    Delete,
    #[sea_orm(string_value = "SYSTEM")]
    System,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_operation_outcome")]
pub enum QpOperationOutcome {
    #[sea_orm(string_value = "success")]
    Success,
    #[sea_orm(string_value = "failure")]
    Failure,
    #[sea_orm(string_value = "denied")]
    Denied,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_order_intent_status"
)]
pub enum QpOrderIntentStatus {
    #[sea_orm(string_value = "pending_authorization")]
    PendingAuthorization,
    #[sea_orm(string_value = "authorized")]
    Authorized,
    #[sea_orm(string_value = "admission_pending")]
    AdmissionPending,
    #[sea_orm(string_value = "admission_rejected")]
    AdmissionRejected,
    #[sea_orm(string_value = "submitted")]
    Submitted,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "filled")]
    Filled,
    #[sea_orm(string_value = "authorization_rejected")]
    AuthorizationRejected,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "invalidated")]
    Invalidated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_order_type_kind")]
pub enum QpOrderTypeKind {
    #[sea_orm(string_value = "fok")]
    Fok,
    #[sea_orm(string_value = "fak")]
    Fak,
    #[sea_orm(string_value = "gtc")]
    Gtc,
    #[sea_orm(string_value = "gtd")]
    Gtd,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_outcome_side")]
pub enum QpOutcomeSide {
    #[sea_orm(string_value = "yes")]
    Yes,
    #[sea_orm(string_value = "no")]
    No,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_parity_subject_kind"
)]
pub enum QpParitySubjectKind {
    #[sea_orm(string_value = "recommendation_report")]
    RecommendationReport,
    #[sea_orm(string_value = "model_run")]
    ModelRun,
    #[sea_orm(string_value = "model_version")]
    ModelVersion,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_policy_activation_kind"
)]
pub enum QpPolicyActivationKind {
    #[sea_orm(string_value = "initial")]
    Initial,
    #[sea_orm(string_value = "promote")]
    Promote,
    #[sea_orm(string_value = "model_bootstrap")]
    ModelBootstrap,
    #[sea_orm(string_value = "model_shadow_binding")]
    ModelShadowBinding,
    #[sea_orm(string_value = "model_shadow_cancellation")]
    ModelShadowCancellation,
    #[sea_orm(string_value = "model_shadow_rejection")]
    ModelShadowRejection,
    #[sea_orm(string_value = "model_promotion")]
    ModelPromotion,
    #[sea_orm(string_value = "rollback")]
    Rollback,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_policy_actor_kind")]
pub enum QpPolicyActorKind {
    #[sea_orm(string_value = "operator")]
    Operator,
    #[sea_orm(string_value = "system")]
    System,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_policy_approval_decision"
)]
pub enum QpPolicyApprovalDecision {
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "rejected")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_policy_revision_status"
)]
pub enum QpPolicyRevisionStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "validated")]
    Validated,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_position_ledger_state"
)]
pub enum QpPositionLedgerState {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "closing")]
    Closing,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "settled")]
    Settled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_entry_authorization_policy"
)]
pub enum QpEntryAuthorizationPolicy {
    #[sea_orm(string_value = "operator_approval_required")]
    OperatorApprovalRequired,
    #[sea_orm(string_value = "policy_automatic")]
    PolicyAutomatic,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_execution_authority_ceiling"
)]
pub enum QpExecutionAuthorityCeiling {
    #[sea_orm(string_value = "analysis_only")]
    AnalysisOnly,
    #[sea_orm(string_value = "operator_approval")]
    OperatorApproval,
    #[sea_orm(string_value = "policy_automatic")]
    PolicyAutomatic,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_execution_attempt_no_fill_reason"
)]
pub enum QpExecutionAttemptNoFillReason {
    #[sea_orm(string_value = "venue_rejected")]
    VenueRejected,
    #[sea_orm(string_value = "venue_cancelled")]
    VenueCancelled,
    #[sea_orm(string_value = "venue_expired")]
    VenueExpired,
    #[sea_orm(string_value = "reconciled_not_filled")]
    ReconciledNotFilled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_execution_attempt_terminal_state"
)]
pub enum QpExecutionAttemptTerminalState {
    #[sea_orm(string_value = "unfilled")]
    Unfilled,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "fully_filled")]
    FullyFilled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_recommendation_resolution_kind"
)]
pub enum QpRecommendationResolutionKind {
    #[sea_orm(string_value = "winner_take_all")]
    WinnerTakeAll,
    #[sea_orm(string_value = "split_payout")]
    SplitPayout,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_recommendation_report_status"
)]
pub enum QpRecommendationReportStatus {
    #[sea_orm(string_value = "prepared")]
    Prepared,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "superseded")]
    Superseded,
    #[sea_orm(string_value = "obsolete")]
    Obsolete,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "expired")]
    Expired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_recommendation_status"
)]
pub enum QpRecommendationStatus {
    #[sea_orm(string_value = "prepared")]
    Prepared,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "superseded")]
    Superseded,
    #[sea_orm(string_value = "obsolete")]
    Obsolete,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "intent_created")]
    IntentCreated,
    #[sea_orm(string_value = "executed")]
    Executed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_reconciliation_result"
)]
pub enum QpReconciliationResult {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "filled")]
    Filled,
    #[sea_orm(string_value = "not_filled")]
    NotFilled,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "unresolvable")]
    Unresolvable,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_report_fact_delivery_status"
)]
pub enum QpReportFactDeliveryStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "delivering")]
    Delivering,
    #[sea_orm(string_value = "retrying")]
    Retrying,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "verified")]
    Verified,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_resolution_projection_status"
)]
pub enum QpResolutionProjectionStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "delivering")]
    Delivering,
    #[sea_orm(string_value = "retry_scheduled")]
    RetryScheduled,
    #[sea_orm(string_value = "mapping_blocked")]
    MappingBlocked,
    #[sea_orm(string_value = "quarantined")]
    Quarantined,
    #[sea_orm(string_value = "excluded")]
    Excluded,
    #[sea_orm(string_value = "verified")]
    Verified,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_resolution_projection_error_code"
)]
pub enum QpResolutionProjectionErrorCode {
    #[sea_orm(string_value = "catalog_mapping_unavailable")]
    CatalogMappingUnavailable,
    #[sea_orm(string_value = "invalid_observation")]
    InvalidObservation,
    #[sea_orm(string_value = "persistence_unavailable")]
    PersistenceUnavailable,
    #[sea_orm(string_value = "external_dependency_unavailable")]
    ExternalDependencyUnavailable,
    #[sea_orm(string_value = "unexpected_transient")]
    UnexpectedTransient,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_resolution_remediation_action"
)]
pub enum QpResolutionRemediationAction {
    #[sea_orm(string_value = "requeue")]
    Requeue,
    #[sea_orm(string_value = "exclude")]
    Exclude,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_outcome_reconciliation_task_status"
)]
pub enum QpOutcomeReconciliationTaskStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "delivering")]
    Delivering,
    #[sea_orm(string_value = "retrying")]
    Retrying,
    #[sea_orm(string_value = "completed")]
    Completed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_report_kind")]
pub enum QpReportKind {
    #[sea_orm(string_value = "top_n")]
    TopN,
    #[sea_orm(string_value = "shadow_top_n")]
    ShadowTopN,
    #[sea_orm(string_value = "post_run_audit")]
    PostRunAudit,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_report_run_status")]
pub enum QpReportRunStatus {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "skipped")]
    Skipped,
    #[sea_orm(string_value = "abandoned")]
    Abandoned,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_report_run_terminal_reason"
)]
pub enum QpReportRunTerminalReason {
    #[sea_orm(string_value = "coalesced_by_newer_occurrence")]
    CoalescedByNewerOccurrence,
    #[sea_orm(string_value = "schedule_reconfigured")]
    ScheduleReconfigured,
    #[sea_orm(string_value = "queue_expired")]
    QueueExpired,
    #[sea_orm(string_value = "build_failed")]
    BuildFailed,
    #[sea_orm(string_value = "lease_expired")]
    LeaseExpired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_report_schedule_gap_reason"
)]
pub enum QpReportScheduleGapReason {
    #[sea_orm(string_value = "coordinator_lag")]
    CoordinatorLag,
    #[sea_orm(string_value = "coalesced_by_newer_occurrence")]
    CoalescedByNewerOccurrence,
    #[sea_orm(string_value = "schedule_reconfigured")]
    ScheduleReconfigured,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_report_trigger_kind"
)]
pub enum QpReportTriggerKind {
    #[sea_orm(string_value = "scheduled")]
    Scheduled,
    #[sea_orm(string_value = "ad_hoc")]
    AdHoc,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_research_evaluation_track"
)]
pub enum QpResearchEvaluationTrack {
    #[sea_orm(string_value = "research_only")]
    ResearchOnly,
    #[sea_orm(string_value = "execution_candidate")]
    ExecutionCandidate,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_research_job_kind")]
pub enum QpResearchJobKind {
    #[sea_orm(string_value = "dataset_build")]
    DatasetBuild,
    #[sea_orm(string_value = "model_train")]
    ModelTrain,
    #[sea_orm(string_value = "backtest")]
    Backtest,
    #[sea_orm(string_value = "bias_table_fit")]
    BiasTableFit,
    #[sea_orm(string_value = "model_calibration_fit")]
    ModelCalibrationFit,
    #[sea_orm(string_value = "cpcv_backtest")]
    CpcvBacktest,
    #[sea_orm(string_value = "feature_parity")]
    FeatureParity,
    #[sea_orm(string_value = "feedback_truth_freeze")]
    FeedbackTruthFreeze,
    #[sea_orm(string_value = "feedback_coverage")]
    FeedbackCoverage,
    #[sea_orm(string_value = "feedback_attribution")]
    FeedbackAttribution,
    #[sea_orm(string_value = "feedback_drift")]
    FeedbackDrift,
    #[sea_orm(string_value = "feedback_recipe_plan")]
    FeedbackRecipePlan,
    #[sea_orm(string_value = "feedback_dataset_seal")]
    FeedbackDatasetSeal,
    #[sea_orm(string_value = "feedback_training")]
    FeedbackTraining,
    #[sea_orm(string_value = "feedback_calibration")]
    FeedbackCalibration,
    #[sea_orm(string_value = "feedback_cpcv")]
    FeedbackCpcv,
    #[sea_orm(string_value = "feedback_validation")]
    FeedbackValidation,
    #[sea_orm(string_value = "feedback_comparison")]
    FeedbackComparison,
    #[sea_orm(string_value = "feedback_shadow_bind")]
    FeedbackShadowBind,
    #[sea_orm(string_value = "feedback_shadow")]
    FeedbackShadow,
    #[sea_orm(string_value = "feedback_decision")]
    FeedbackDecision,
    #[sea_orm(string_value = "trade_policy_fit")]
    TradePolicyFit,
    #[sea_orm(string_value = "trade_policy_validation")]
    TradePolicyValidation,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_research_job_result_kind"
)]
pub enum QpResearchJobResultKind {
    #[sea_orm(string_value = "training_dataset")]
    TrainingDataset,
    #[sea_orm(string_value = "model_version")]
    ModelVersion,
    #[sea_orm(string_value = "backtest_report")]
    BacktestReport,
    #[sea_orm(string_value = "backtest_path_set")]
    BacktestPathSet,
    #[sea_orm(string_value = "calibration_artifact")]
    CalibrationArtifact,
    #[sea_orm(string_value = "feature_parity_run")]
    FeatureParityRun,
    #[sea_orm(string_value = "feedback_truth_freeze_artifact")]
    FeedbackTruthFreezeArtifact,
    #[sea_orm(string_value = "feedback_coverage_artifact")]
    FeedbackCoverageArtifact,
    #[sea_orm(string_value = "feedback_attribution_manifest")]
    FeedbackAttributionManifest,
    #[sea_orm(string_value = "feedback_drift_artifact")]
    FeedbackDriftArtifact,
    #[sea_orm(string_value = "candidate_recipe_plan_artifact")]
    CandidateRecipePlanArtifact,
    #[sea_orm(string_value = "feedback_learning_stage_artifact")]
    FeedbackLearningStageArtifact,
    #[sea_orm(string_value = "feedback_validation_artifact")]
    FeedbackValidationArtifact,
    #[sea_orm(string_value = "feedback_comparison_artifact")]
    FeedbackComparisonArtifact,
    #[sea_orm(string_value = "shadow_binding_artifact")]
    ShadowBindingArtifact,
    #[sea_orm(string_value = "feedback_shadow_artifact")]
    FeedbackShadowArtifact,
    #[sea_orm(string_value = "feedback_decision_artifact")]
    FeedbackDecisionArtifact,
    #[sea_orm(string_value = "trade_policy_artifact")]
    TradePolicyArtifact,
    #[sea_orm(string_value = "trade_policy_validation_run")]
    TradePolicyValidationRun,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_exchange_history_frontier"
)]
pub enum QpExchangeHistoryFrontier {
    #[sea_orm(string_value = "activation")]
    Activation,
    #[sea_orm(string_value = "retention")]
    Retention,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_exchange_history_continuity_basis"
)]
pub enum QpExchangeHistoryContinuityBasis {
    #[sea_orm(string_value = "hypersync_rollback_guard")]
    HyperSyncRollbackGuard,
    #[sea_orm(string_value = "hypersync_boundary_headers")]
    HyperSyncBoundaryHeaders,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_exchange_history_chunk_status"
)]
pub enum QpExchangeHistoryChunkStatus {
    #[sea_orm(string_value = "planned")]
    Planned,
    #[sea_orm(string_value = "extracting")]
    Extracting,
    #[sea_orm(string_value = "attesting")]
    Attesting,
    #[sea_orm(string_value = "projecting")]
    Projecting,
    #[sea_orm(string_value = "accepted")]
    Accepted,
    #[sea_orm(string_value = "rewound")]
    Rewound,
    #[sea_orm(string_value = "quarantined")]
    Quarantined,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_exchange_history_quarantine_kind"
)]
pub enum QpExchangeHistoryQuarantineKind {
    #[sea_orm(string_value = "provider_mismatch")]
    ProviderMismatch,
    #[sea_orm(string_value = "decode_failure")]
    DecodeFailure,
    #[sea_orm(string_value = "unknown_token")]
    UnknownToken,
    #[sea_orm(string_value = "missing_correlation")]
    MissingCorrelation,
    #[sea_orm(string_value = "continuity_mismatch")]
    ContinuityMismatch,
    #[sea_orm(string_value = "parent_hash_mismatch")]
    ParentHashMismatch,
    #[sea_orm(string_value = "contract_mismatch")]
    ContractMismatch,
    #[sea_orm(string_value = "archive_probe_failure")]
    ArchiveProbeFailure,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_exchange_history_quarantine_disposition"
)]
pub enum QpExchangeHistoryQuarantineDisposition {
    #[sea_orm(string_value = "accepted_replacement")]
    AcceptedReplacement,
    #[sea_orm(string_value = "canonical_supersession")]
    CanonicalSupersession,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_research_job_status"
)]
pub enum QpResearchJobStatus {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "awaiting_evidence")]
    AwaitingEvidence,
    #[sea_orm(string_value = "retry_scheduled")]
    RetryScheduled,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_research_readiness_evidence_kind"
)]
pub enum QpResearchReadinessEvidenceKind {
    #[sea_orm(string_value = "retention_runway")]
    RetentionRunway,
    #[sea_orm(string_value = "shadow_latency_profile")]
    ShadowLatencyProfile,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_resolver_tier")]
pub enum QpResolverTier {
    #[sea_orm(string_value = "tier0_slug")]
    Tier0Slug,
    #[sea_orm(string_value = "tier1_template")]
    Tier1Template,
    #[sea_orm(string_value = "override")]
    Override,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_resource_type")]
pub enum QpResourceType {
    #[sea_orm(string_value = "system")]
    System,
    #[sea_orm(string_value = "market")]
    Market,
    #[sea_orm(string_value = "config")]
    Config,
    #[sea_orm(string_value = "publication")]
    Publication,
    #[sea_orm(string_value = "materialization")]
    Materialization,
    #[sea_orm(string_value = "replay")]
    Replay,
    #[sea_orm(string_value = "quant_report")]
    QuantReport,
    #[sea_orm(string_value = "account_snapshot")]
    AccountSnapshot,
    #[sea_orm(string_value = "equity_snapshot")]
    EquitySnapshot,
    #[sea_orm(string_value = "order_intent")]
    OrderIntent,
    #[sea_orm(string_value = "execution_order")]
    ExecutionOrder,
    #[sea_orm(string_value = "position")]
    Position,
    #[sea_orm(string_value = "reconciliation")]
    Reconciliation,
    #[sea_orm(string_value = "settlement_redeem")]
    SettlementRedeem,
    #[sea_orm(string_value = "factor_definition")]
    FactorDefinition,
    #[sea_orm(string_value = "operation_log")]
    OperationLog,
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "role")]
    Role,
    #[sea_orm(string_value = "menu")]
    Menu,
    #[sea_orm(string_value = "permission")]
    Permission,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_role_kind")]
pub enum QpRoleKind {
    #[sea_orm(string_value = "builtin")]
    Builtin,
    #[sea_orm(string_value = "custom")]
    Custom,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_role_status")]
pub enum QpRoleStatus {
    #[sea_orm(string_value = "enabled")]
    Enabled,
    #[sea_orm(string_value = "disabled")]
    Disabled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_settlement_route")]
pub enum QpSettlementRoute {
    #[sea_orm(string_value = "standard_v2")]
    StandardV2,
    #[sea_orm(string_value = "neg_risk_v2")]
    NegRiskV2,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_write_policy"
)]
pub enum QpSettlementWritePolicy {
    #[sea_orm(string_value = "disabled")]
    Disabled,
    #[sea_orm(string_value = "governed_canary")]
    GovernedCanary,
    #[sea_orm(string_value = "operator_approval")]
    OperatorApproval,
    #[sea_orm(string_value = "policy_automatic")]
    PolicyAutomatic,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_readiness_status"
)]
pub enum QpSettlementReadinessStatus {
    #[sea_orm(string_value = "unchecked")]
    Unchecked,
    #[sea_orm(string_value = "ready")]
    Ready,
    #[sea_orm(string_value = "blocked")]
    Blocked,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_case_state"
)]
pub enum QpSettlementCaseState {
    #[sea_orm(string_value = "discovered")]
    Discovered,
    #[sea_orm(string_value = "prepared")]
    Prepared,
    #[sea_orm(string_value = "submitted")]
    Submitted,
    #[sea_orm(string_value = "confirmed")]
    Confirmed,
    #[sea_orm(string_value = "retry_scheduled")]
    RetryScheduled,
    #[sea_orm(string_value = "reconciliation_required")]
    ReconciliationRequired,
    #[sea_orm(string_value = "manual_required")]
    ManualRequired,
    #[sea_orm(string_value = "not_required")]
    NotRequired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_authorization_state"
)]
pub enum QpSettlementAuthorizationState {
    #[sea_orm(string_value = "not_required")]
    NotRequired,
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "consumed")]
    Consumed,
    #[sea_orm(string_value = "expired")]
    Expired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_effective_policy"
)]
pub enum QpSettlementEffectivePolicy {
    #[sea_orm(string_value = "automatic_eligible")]
    AutomaticEligible,
    #[sea_orm(string_value = "manual_only")]
    ManualOnly,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_governed_action_kind"
)]
pub enum QpSettlementGovernedActionKind {
    #[sea_orm(string_value = "outcome_token_approval")]
    OutcomeTokenApproval,
    #[sea_orm(string_value = "outcome_token_revocation")]
    OutcomeTokenRevocation,
    #[sea_orm(string_value = "canary_grant")]
    CanaryGrant,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_governed_action_state"
)]
pub enum QpSettlementGovernedActionState {
    #[sea_orm(string_value = "authorized")]
    Authorized,
    #[sea_orm(string_value = "retry_scheduled")]
    RetryScheduled,
    #[sea_orm(string_value = "consumed")]
    Consumed,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "reconciliation_required")]
    ReconciliationRequired,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_submission_kind"
)]
pub enum QpSettlementSubmissionKind {
    #[sea_orm(string_value = "direct_eoa")]
    DirectEoa,
    #[sea_orm(string_value = "relayer")]
    Relayer,
    #[sea_orm(string_value = "externally_observed")]
    ExternallyObserved,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_submission_purpose"
)]
pub enum QpSettlementSubmissionPurpose {
    #[sea_orm(string_value = "outcome_token_approval")]
    OutcomeTokenApproval,
    #[sea_orm(string_value = "outcome_token_revocation")]
    OutcomeTokenRevocation,
    #[sea_orm(string_value = "redeem")]
    Redeem,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_submission_state"
)]
pub enum QpSettlementSubmissionState {
    #[sea_orm(string_value = "prepared")]
    Prepared,
    #[sea_orm(string_value = "dispatching")]
    Dispatching,
    #[sea_orm(string_value = "awaiting_chain_hash")]
    AwaitingChainHash,
    #[sea_orm(string_value = "awaiting_finality")]
    AwaitingFinality,
    #[sea_orm(string_value = "confirmed")]
    Confirmed,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_failure_code"
)]
pub enum QpSettlementFailureCode {
    #[sea_orm(string_value = "route_not_ready")]
    RouteNotReady,
    #[sea_orm(string_value = "balance_mismatch")]
    BalanceMismatch,
    #[sea_orm(string_value = "simulation_reverted")]
    SimulationReverted,
    #[sea_orm(string_value = "transport_uncertain")]
    TransportUncertain,
    #[sea_orm(string_value = "submission_rejected")]
    SubmissionRejected,
    #[sea_orm(string_value = "relayer_terminal_failure")]
    RelayerTerminalFailure,
    #[sea_orm(string_value = "on_chain_reverted")]
    OnChainReverted,
    #[sea_orm(string_value = "receipt_evidence_mismatch")]
    ReceiptEvidenceMismatch,
    #[sea_orm(string_value = "payout_mismatch")]
    PayoutMismatch,
    #[sea_orm(string_value = "deployment_changed")]
    DeploymentChanged,
    #[sea_orm(string_value = "authorization_invalid")]
    AuthorizationInvalid,
    #[sea_orm(string_value = "execution_not_quiescent")]
    ExecutionNotQuiescent,
    #[sea_orm(string_value = "lease_lost")]
    LeaseLost,
    #[sea_orm(string_value = "ledger_unavailable")]
    LedgerUnavailable,
    #[sea_orm(string_value = "local_invariant")]
    LocalInvariant,
    #[sea_orm(string_value = "external_evidence_incomplete")]
    ExternalEvidenceIncomplete,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_settlement_reconciliation_state"
)]
pub enum QpSettlementReconciliationState {
    #[sea_orm(string_value = "not_required")]
    NotRequired,
    #[sea_orm(string_value = "awaiting_relayer_hash")]
    AwaitingRelayerHash,
    #[sea_orm(string_value = "awaiting_receipt")]
    AwaitingReceipt,
    #[sea_orm(string_value = "evidence_mismatch")]
    EvidenceMismatch,
    #[sea_orm(string_value = "operator_review_required")]
    OperatorReviewRequired,
    #[sea_orm(string_value = "reconciled")]
    Reconciled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_side")]
pub enum QpSide {
    #[sea_orm(string_value = "BUY")]
    Buy,
    #[sea_orm(string_value = "SELL")]
    Sell,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_source_slice_status"
)]
pub enum QpSourceSliceStatus {
    #[sea_orm(string_value = "materializing")]
    Materializing,
    #[sea_orm(string_value = "ready")]
    Ready,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_tick_size")]
pub enum QpTickSize {
    #[sea_orm(string_value = "0.1")]
    _0U002E1,
    #[sea_orm(string_value = "0.01")]
    _0U002E01,
    #[sea_orm(string_value = "0.005")]
    _0U002E005,
    #[sea_orm(string_value = "0.0025")]
    _0U002E0025,
    #[sea_orm(string_value = "0.001")]
    _0U002E001,
    #[sea_orm(string_value = "0.0001")]
    _0U002E0001,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_governance_action"
)]
pub enum QpTradePolicyGovernanceAction {
    #[sea_orm(string_value = "validate")]
    Validate,
    #[sea_orm(string_value = "publish")]
    Publish,
    #[sea_orm(string_value = "retire")]
    Retire,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_status"
)]
pub enum QpTradePolicyStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "validated")]
    Validated,
    #[sea_orm(string_value = "published")]
    Published,
    #[sea_orm(string_value = "retired")]
    Retired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_trial_scope"
)]
pub enum QpTradePolicyTrialScope {
    #[sea_orm(string_value = "candidate")]
    Candidate,
    #[sea_orm(string_value = "fold")]
    Fold,
    #[sea_orm(string_value = "path")]
    Path,
    #[sea_orm(string_value = "latency_stress")]
    LatencyStress,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_trial_status"
)]
pub enum QpTradePolicyTrialStatus {
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_trade_policy_validation_status"
)]
pub enum QpTradePolicyValidationStatus {
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_training_dataset_status"
)]
pub enum QpTrainingDatasetStatus {
    #[sea_orm(string_value = "planned")]
    Planned,
    #[sea_orm(string_value = "building")]
    Building,
    #[sea_orm(string_value = "insufficient_labels")]
    InsufficientLabels,
    #[sea_orm(string_value = "ready")]
    Ready,
    #[sea_orm(string_value = "expired")]
    Expired,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_user_status")]
pub enum QpUserStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "disabled")]
    Disabled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_venue_order_status"
)]
pub enum QpVenueOrderStatus {
    #[sea_orm(string_value = "filled")]
    Filled,
    #[sea_orm(string_value = "partially_filled")]
    PartiallyFilled,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "expired")]
    Expired,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_venue_trade_status"
)]
pub enum QpVenueTradeStatus {
    #[sea_orm(string_value = "matched")]
    Matched,
    #[sea_orm(string_value = "mined")]
    Mined,
    #[sea_orm(string_value = "confirmed")]
    Confirmed,
    #[sea_orm(string_value = "retrying")]
    Retrying,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_weather_temperature_statistic"
)]
pub enum QpWeatherTemperatureStatistic {
    #[sea_orm(string_value = "maximum")]
    Maximum,
    #[sea_orm(string_value = "minimum")]
    Minimum,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_cycle_status"
)]
pub enum QpFeedbackCycleStatus {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "quarantined")]
    Quarantined,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_evaluation_mode"
)]
pub enum QpFeedbackEvaluationMode {
    #[sea_orm(string_value = "conditional")]
    Conditional,
    #[sea_orm(string_value = "forced_retraining")]
    ForcedRetraining,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_scheduler_failure_kind"
)]
pub enum QpFeedbackSchedulerFailureKind {
    #[sea_orm(string_value = "materialization")]
    Materialization,
    #[sea_orm(string_value = "settlement")]
    Settlement,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_recipe_template_status"
)]
pub enum QpFeedbackRecipeTemplateStatus {
    #[sea_orm(string_value = "draft")]
    Draft,
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "retired")]
    Retired,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_shadow_binding_status"
)]
pub enum QpShadowBindingStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "promoted")]
    Promoted,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_feedback_decision")]
pub enum QpFeedbackDecision {
    #[sea_orm(string_value = "no_action")]
    NoAction,
    #[sea_orm(string_value = "challenger_rejected")]
    ChallengerRejected,
    #[sea_orm(string_value = "candidate_ready")]
    CandidateReady,
    #[sea_orm(string_value = "promoted")]
    Promoted,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_trigger_family"
)]
pub enum QpFeedbackTriggerFamily {
    #[sea_orm(string_value = "scheduled")]
    Scheduled,
    #[sea_orm(string_value = "manual")]
    Manual,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "qp_feedback_stage")]
pub enum QpFeedbackStage {
    #[sea_orm(string_value = "trigger")]
    Trigger,
    #[sea_orm(string_value = "truth_freeze")]
    TruthFreeze,
    #[sea_orm(string_value = "coverage")]
    Coverage,
    #[sea_orm(string_value = "attribution")]
    Attribution,
    #[sea_orm(string_value = "drift")]
    Drift,
    #[sea_orm(string_value = "recipe_plan")]
    RecipePlan,
    #[sea_orm(string_value = "dataset_seal")]
    DatasetSeal,
    #[sea_orm(string_value = "training")]
    Training,
    #[sea_orm(string_value = "calibration")]
    Calibration,
    #[sea_orm(string_value = "cpcv")]
    Cpcv,
    #[sea_orm(string_value = "validation")]
    Validation,
    #[sea_orm(string_value = "comparison")]
    Comparison,
    #[sea_orm(string_value = "shadow_bind")]
    ShadowBind,
    #[sea_orm(string_value = "shadow")]
    Shadow,
    #[sea_orm(string_value = "decision")]
    Decision,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_stage_event_kind"
)]
pub enum QpFeedbackStageEventKind {
    #[sea_orm(string_value = "triggered")]
    Triggered,
    #[sea_orm(string_value = "job_linked")]
    JobLinked,
    #[sea_orm(string_value = "started")]
    Started,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
    #[sea_orm(string_value = "cancellation_requested")]
    CancellationRequested,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "lease_recovered")]
    LeaseRecovered,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_attribution_artifact_kind"
)]
pub enum QpAttributionArtifactKind {
    #[sea_orm(string_value = "prediction_explanation")]
    PredictionExplanation,
    #[sea_orm(string_value = "decision_intervention_replay")]
    DecisionInterventionReplay,
    #[sea_orm(string_value = "resolution_outcome_association")]
    ResolutionOutcomeAssociation,
    #[sea_orm(string_value = "execution_outcome_association")]
    ExecutionOutcomeAssociation,
    #[sea_orm(string_value = "execution_trajectory")]
    ExecutionTrajectory,
    #[sea_orm(string_value = "policy_counterfactual_outcome")]
    PolicyCounterfactualOutcome,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_attribution_cohort"
)]
pub enum QpAttributionCohort {
    #[sea_orm(string_value = "training")]
    Training,
    #[sea_orm(string_value = "evaluation")]
    Evaluation,
    #[sea_orm(string_value = "shadow")]
    Shadow,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_drift_kind"
)]
pub enum QpFeedbackDriftKind {
    #[sea_orm(string_value = "data")]
    Data,
    #[sea_orm(string_value = "concept")]
    Concept,
    #[sea_orm(string_value = "label")]
    Label,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_drift_metric"
)]
pub enum QpFeedbackDriftMetric {
    #[sea_orm(string_value = "population_stability_index")]
    PopulationStabilityIndex,
    #[sea_orm(string_value = "kolmogorov_smirnov_p_value")]
    KolmogorovSmirnovPValue,
    #[sea_orm(string_value = "target_rank_ic_drop")]
    TargetRankIcDrop,
    #[sea_orm(string_value = "jensen_shannon_divergence")]
    JensenShannonDivergence,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_drift_assessment"
)]
pub enum QpFeedbackDriftAssessment {
    #[sea_orm(string_value = "within_threshold")]
    WithinThreshold,
    #[sea_orm(string_value = "threshold_exceeded")]
    ThresholdExceeded,
    #[sea_orm(string_value = "insufficient_evidence")]
    InsufficientEvidence,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "Enum",
    db_type = "Enum",
    enum_name = "qp_feedback_evaluation_purpose"
)]
pub enum QpFeedbackEvaluationPurpose {
    #[sea_orm(string_value = "promotion_comparison")]
    PromotionComparison,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "qp_account_pause_operation_kind"
)]
pub enum QpAccountPauseOperationKind {
    #[sea_orm(string_value = "pause")]
    Pause,
    #[sea_orm(string_value = "unpause")]
    Unpause,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "qp_recommendation_economic_outcome_state"
)]
pub enum QpRecommendationEconomicOutcomeState {
    #[sea_orm(string_value = "entry_not_triggered")]
    EntryNotTriggered,
    #[sea_orm(string_value = "entry_unfilled")]
    EntryUnfilled,
    #[sea_orm(string_value = "policy_exited")]
    PolicyExited,
    #[sea_orm(string_value = "horizon_liquidated")]
    HorizonLiquidated,
    #[sea_orm(string_value = "resolved_before_horizon")]
    ResolvedBeforeHorizon,
    #[sea_orm(string_value = "censored")]
    Censored,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "qp_route_economic_health_state"
)]
pub enum QpRouteEconomicHealthState {
    #[sea_orm(string_value = "insufficient_evidence")]
    InsufficientEvidence,
    #[sea_orm(string_value = "healthy")]
    Healthy,
    #[sea_orm(string_value = "degraded")]
    Degraded,
    #[sea_orm(string_value = "data_incomplete")]
    DataIncomplete,
}
