//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "seed_application")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub seed_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub seed_version: i32,
    #[sea_orm(column_type = "Text")]
    pub checksum: String,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub applied_at: DateTimeWithTimeZone,
    pub rows_affected: i64,
}

impl ActiveModelBehavior for ActiveModel {}
