//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpKillSwitchState;
use sea_orm::{entity::prelude::*, sea_query::Expr};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(schema_name = "public", table_name = "system_kill_switch")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(default_expr = "Expr::cust(\"'report_only_forced'::qp_kill_switch_state\")")]
    pub state: QpKillSwitchState,
    #[sea_orm(column_type = "Text")]
    #[sea_orm(default_expr = "Expr::cust(\"'bootstrap'::text\")")]
    pub changed_by: String,
    #[sea_orm(column_type = "Text")]
    #[sea_orm(
        default_expr = "Expr::cust(\"'bootstrap requires explicit operator activation'::text\")"
    )]
    pub reason: String,
    #[sea_orm(default_expr = "Expr::cust(\"true\")")]
    pub requires_operator_ack: bool,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub changed_at: DateTimeWithTimeZone,
    #[sea_orm(default_expr = "Expr::cust(\"statement_timestamp()\")")]
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
