//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::QpBootstrapPhase;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "system_bootstrap_transition")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub bootstrap_transition_id: Uuid,
    pub bootstrap_contract_version: i32,
    pub state_revision: i64,
    pub from_phase: QpBootstrapPhase,
    pub to_phase: QpBootstrapPhase,
    #[sea_orm(column_type = "Text")]
    pub actor: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub acting_role: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub report_only_forced_ack: bool,
    pub occurred_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
