//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0

use sea_orm::entity::prelude::*;

use super::sea_orm_active_enums::{QpKillSwitchState, QpQuantRuntimeMode, QpSettlementWritePolicy};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "system_runtime_control")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_type = r#"custom("qp_quant_runtime_mode")"#)]
    pub quant_runtime_mode: QpQuantRuntimeMode,
    pub settlement_write_policy: QpSettlementWritePolicy,
    pub kill_switch_state: QpKillSwitchState,
    pub kill_switch_requires_ack: bool,
    pub revision: i64,
    #[sea_orm(column_type = "Text")]
    pub changed_by: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub changed_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
