//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.43

use super::sea_orm_active_enums::QpUserStatus;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    #[sea_orm(column_type = "Text")]
    pub nickname: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    pub status: QpUserStatus,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub decision_policy_snapshots: HasMany<super::decision_policy_snapshot::Entity>,
    #[sea_orm(has_many)]
    pub policy_activations: HasMany<super::policy_activation::Entity>,
    #[sea_orm(has_many)]
    pub policy_approvals: HasMany<super::policy_approval::Entity>,
    #[sea_orm(has_many)]
    pub policy_revisions: HasMany<super::policy_revision::Entity>,
    #[sea_orm(has_many)]
    pub system_production_baselines: HasMany<super::system_production_baseline::Entity>,
    #[sea_orm(has_many, via = "user_role")]
    pub roles: HasMany<super::role::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
