use sea_orm::DeriveIden;

#[derive(DeriveIden)]
pub enum Position {
    Table,
    PositionId,
    TradeId,
    MarketId,
    TokenId,
    Side,
    Shares,
    AvgEntryPrice,
    TotalCostUsd,
    TotalFeesUsd,
    UnrealizedPnl,
    RealizedPnl,
    Status,
    OpenedAt,
    ClosedAt,
    SettledAt,
    WinningTokenId,
    SettlementPayoutUsd,
    RedeemTxHash,
    RedeemStatus,
    RedeemAttempts,
    OracleVerdict,
    SettlementTrigger,
    SettlementAccountingStatus,
    SettlementAccountingError,
    SettlementAccountedAt,
    RedeemTerminalReason,
}
