use sea_orm::DeriveIden;

#[derive(DeriveIden)]
pub enum RiskEngineState {
    Table,
    Id,
    BreakerState,
    BreakerLevel,
    IsHalted,
    HaltReason,
    ConsecutiveMisses,
    CooldownUntil,
    CooldownMultiplier,
    TotalExposure,
    HourlyLossUsd,
    HourlyFeeUsd,
    HourlyTradeCount,
    HourlySuccessCount,
    HourlyMissCount,
    HourlyWindowStart,
    DailyLossUsd,
    DailyFeeUsd,
    DailyPnl,
    DailyBudgetSpent,
    DailyTradeCount,
    DailySuccessCount,
    DailyMissCount,
    DailyWindowStart,
    WeeklyLossUsd,
    WeeklyTradeCount,
    WeeklyWindowStart,
    HwmEquity,
    LastEmergencyAt,
    LastEmergencyReason,
    UpdatedAt,
}
