use sea_orm_migration::prelude::*;

use super::{
    v1,
    v1::{ConstraintKind, ConstraintSpec},
};

pub const SOURCE: &[u8] = include_bytes!("relational_invariants.rs");
const CONSTRAINTS: &[ConstraintSpec] = &[
    ConstraintSpec {
        name: "catalog_event_object_schema_version_check",
        table: "catalog_event_object",
        kind: ConstraintKind::Check,
        definition: "CHECK ((schema_version > 0))",
    },
    ConstraintSpec {
        name: "catalog_market_object_schema_version_check",
        table: "catalog_market_object",
        kind: ConstraintKind::Check,
        definition: "CHECK ((schema_version > 0))",
    },
    ConstraintSpec {
        name: "catalog_sync_batch_check",
        table: "catalog_sync_batch",
        kind: ConstraintKind::Check,
        definition: "CHECK (((event_count >= 0) AND (market_count >= 0) AND (rejected_count >= 0) AND (((status = 'committed'::qp_catalog_sync_status) AND (fetched_at IS NOT NULL) AND (committed_at IS NOT NULL) AND (batch_hash IS NOT NULL) AND (failure_stage IS NULL) AND (failure_detail IS NULL)) OR ((status = 'failed'::qp_catalog_sync_status) AND (committed_at IS NULL) AND (failure_stage IS NOT NULL) AND (failure_detail IS NOT NULL) AND ((length(failure_detail) >= 1) AND (length(failure_detail) <= 2048))))))",
    },
    ConstraintSpec {
        name: "catalog_sync_rejection_detail_check",
        table: "catalog_sync_rejection",
        kind: ConstraintKind::Check,
        definition: "CHECK (((char_length(detail) >= 1) AND (char_length(detail) <= 2048)))",
    },
    ConstraintSpec {
        name: "market_check",
        table: "market",
        kind: ConstraintKind::Check,
        definition: "CHECK (((status <> 'active'::qp_market_status) OR (cardinality(filter_reasons) = 0)))",
    },
    ConstraintSpec {
        name: "market_check1",
        table: "market",
        kind: ConstraintKind::Check,
        definition: "CHECK (((status <> 'filtered'::qp_market_status) OR (cardinality(filter_reasons) > 0)))",
    },
    ConstraintSpec {
        name: "quant_factor_definition_definition_hash_check",
        table: "quant_factor_definition",
        kind: ConstraintKind::Check,
        definition: "CHECK ((definition_hash ~ '^blake3:[0-9a-f]{64}$'::text))",
    },
    ConstraintSpec {
        name: "quant_factor_definition_feature_contract_hash_check",
        table: "quant_factor_definition",
        kind: ConstraintKind::Check,
        definition: "CHECK ((feature_contract_hash ~ '^blake3:[0-9a-f]{64}$'::text))",
    },
    ConstraintSpec {
        name: "ck_quant_factor_definition_document",
        table: "quant_factor_definition",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(definition) = 'object'::text) AND ((definition ->> 'name'::text) = name) AND ((definition ->> 'family'::text) = (factor_family)::text) AND (jsonb_typeof((definition -> 'input_features'::text)) = 'array'::text) AND (jsonb_typeof((definition -> 'quality_gates'::text)) = 'array'::text) AND (jsonb_typeof((definition -> 'owner'::text)) = 'string'::text) AND (char_length(btrim((definition ->> 'owner'::text))) >= 1)))",
    },
    ConstraintSpec {
        name: "ck_quant_factor_value_explanation",
        table: "quant_factor_value",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(explanation) = 'object'::text) AND (jsonb_typeof((explanation -> 'headline'::text)) = 'string'::text) AND (char_length(btrim((explanation ->> 'headline'::text))) >= 1) AND (jsonb_typeof((explanation -> 'drivers'::text)) = 'array'::text)))",
    },
    ConstraintSpec {
        name: "ck_quant_feature_parity_candidate_ordinal",
        table: "quant_feature_parity_candidate",
        kind: ConstraintKind::Check,
        definition: "CHECK ((ordinal >= 0))",
    },
    ConstraintSpec {
        name: "ck_quant_calibration_artifact_payload_kind",
        table: "quant_calibration_artifact",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(payload) = 'object'::text) AND ((payload ->> 'kind'::text) = (kind)::text) AND (jsonb_typeof((payload -> 'payload'::text)) = 'object'::text)))",
    },
    ConstraintSpec {
        name: "uq_quant_feature_parity_candidate_subject_market",
        table: "quant_feature_parity_candidate",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (parity_subject_id, market_id)",
    },
    ConstraintSpec {
        name: "ck_quant_feature_parity_subject_identity",
        table: "quant_feature_parity_subject",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((subject_kind = 'model_run'::qp_parity_subject_kind) AND (model_run_id IS NOT NULL) AND (recommendation_report_id IS NULL) AND (model_version_id IS NULL) AND (training_dataset_id IS NULL) AND (market_selection_id IS NOT NULL) AND (decision_at IS NOT NULL) AND (selection_hash IS NOT NULL)) OR ((subject_kind = 'recommendation_report'::qp_parity_subject_kind) AND (model_run_id IS NULL) AND (recommendation_report_id IS NOT NULL) AND (model_version_id IS NULL) AND (training_dataset_id IS NULL) AND (market_selection_id IS NOT NULL) AND (decision_at IS NOT NULL) AND (selection_hash IS NOT NULL)) OR ((subject_kind = 'model_version'::qp_parity_subject_kind) AND (model_run_id IS NULL) AND (recommendation_report_id IS NULL) AND (model_version_id IS NOT NULL) AND (training_dataset_id IS NOT NULL) AND (market_selection_id IS NULL) AND (decision_at IS NULL) AND (selection_hash IS NULL))))",
    },
    ConstraintSpec {
        name: "ck_quant_feature_parity_run_semantic_codes",
        table: "quant_feature_parity_run",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((acting_role)::text ~ '^[a-z][a-z0-9_]{0,63}$'::text) AND ((failure_code IS NULL) OR ((failure_code)::text ~ '^[a-z][a-z0-9_]{0,127}$'::text))))",
    },
    ConstraintSpec {
        name: "ck_quant_feature_parity_state_acting_role",
        table: "quant_feature_parity_state",
        kind: ConstraintKind::Check,
        definition: "CHECK (((acting_role IS NULL) OR ((acting_role)::text ~ '^[a-z][a-z0-9_]{0,63}$'::text)))",
    },
    ConstraintSpec {
        name: "ck_quant_feature_vector_documents",
        table: "quant_feature_vector",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(decision_boundary) = 'object'::text) AND (jsonb_typeof(payload) = 'object'::text) AND (payload ? 'generic'::text) AND (payload ? 'domain'::text) AND (jsonb_typeof((payload -> 'generic'::text)) = 'object'::text) AND (jsonb_typeof((payload -> 'domain'::text)) = ANY (ARRAY['object'::text, 'null'::text])) AND (jsonb_typeof(source_refs) = 'array'::text) AND (jsonb_typeof(decision_capture) = 'object'::text) AND (jsonb_typeof((decision_capture -> 'snapshot'::text)) = 'object'::text) AND (decision_capture_hash ~ '^blake3:[0-9a-f]{64}$'::text)))",
    },
    ConstraintSpec {
        name: "ck_quant_market_linkage_outcome",
        table: "quant_market_linkage",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(outcome) = 'object'::text) AND ((((status = 'unresolved'::qp_linkage_status) AND ((outcome ->> 'status'::text) = 'unresolved'::text) AND (jsonb_typeof((outcome -> 'reason'::text)) = 'object'::text) AND ((outcome -> 'reason'::text) ? 'code'::text) AND ((outcome #>> '{reason,code}'::text[]) = ANY (ARRAY['no_deterministic_template'::text, 'candidate_rejected'::text]))) OR ((status = ANY (ARRAY['resolved'::qp_linkage_status, 'overridden'::qp_linkage_status])) AND ((outcome ->> 'status'::text) = 'resolved'::text) AND (jsonb_typeof((outcome -> 'subject'::text)) = 'object'::text) AND (jsonb_typeof((outcome -> 'source_bindings'::text)) = 'array'::text) AND (jsonb_typeof((outcome -> 'grounding'::text)) = 'object'::text))))))",
    },
    ConstraintSpec {
        name: "ck_operation_log_detail_document",
        table: "operation_log",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(detail) = 'object'::text) AND (pg_column_size(detail) <= 65536)))",
    },
    ConstraintSpec {
        name: "ck_quant_model_governance_audit_detail_action",
        table: "quant_model_governance_audit",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(detail) = 'object'::text) AND ((detail ->> 'action'::text) = (action)::text)))",
    },
    ConstraintSpec {
        name: "quant_model_spec_check",
        table: "quant_model_spec",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(input_contract) = 'object'::text) AND (jsonb_typeof((input_contract -> 'inputs'::text)) = 'array'::text) AND (jsonb_array_length((input_contract -> 'inputs'::text)) > 0) AND (jsonb_typeof(training_contract) = 'object'::text) AND (jsonb_typeof((training_contract -> 'target_label_name'::text)) = 'string'::text) AND ((length((training_contract ->> 'target_label_name'::text)) >= 1) AND (length((training_contract ->> 'target_label_name'::text)) <= 128)) AND ((((training_contract ->> 'validation_folds'::text))::integer >= 2) AND (((training_contract ->> 'validation_folds'::text))::integer <= 20)) AND (definition_hash ~ '^blake3:[0-9a-f]{64}$'::text)))",
    },
    ConstraintSpec {
        name: "ck_quant_model_spec_thesis",
        table: "quant_model_spec",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(thesis) = 'object'::text) AND (jsonb_typeof((thesis -> 'summary'::text)) = 'string'::text) AND (char_length(btrim((thesis ->> 'summary'::text))) BETWEEN 1 AND 512) AND ((thesis ->> 'summary'::text) = btrim((thesis ->> 'summary'::text))) AND (jsonb_typeof((thesis -> 'hypothesis'::text)) = 'string'::text) AND (char_length(btrim((thesis ->> 'hypothesis'::text))) BETWEEN 1 AND 2048) AND ((thesis ->> 'hypothesis'::text) = btrim((thesis ->> 'hypothesis'::text))) AND (jsonb_typeof((thesis -> 'limitations'::text)) = 'array'::text) AND (jsonb_array_length((thesis -> 'limitations'::text)) BETWEEN 1 AND 16)))",
    },
    ConstraintSpec {
        name: "ck_quant_model_spec_authoring_provenance",
        table: "quant_model_spec",
        kind: ConstraintKind::Check,
        definition: "CHECK (((char_length(btrim(created_by_label)) >= 1) AND (char_length(btrim(created_by_label)) <= 256) AND ((created_by_role IS NULL) OR ((char_length(btrim(created_by_role)) >= 1) AND (char_length(btrim(created_by_role)) <= 128))) AND (char_length(btrim(reason)) >= 1) AND (char_length(btrim(reason)) <= 2048)))",
    },
    ConstraintSpec {
        name: "ck_quant_model_version_quality_gate_report",
        table: "quant_model_version",
        kind: ConstraintKind::Check,
        definition: "CHECK (((quality_gate_report IS NULL) OR ((jsonb_typeof(quality_gate_report) = 'object'::text) AND (((quality_gate_report ->> 'format_version'::text))::integer = 1) AND ((quality_gate_report -> 'subject'::text) ->> 'kind'::text) = 'model_version'::text AND ((((quality_gate_report -> 'subject'::text) ->> 'id'::text))::uuid = model_version_id) AND (jsonb_typeof((quality_gate_report -> 'gates'::text)) = 'array'::text) AND (jsonb_typeof((quality_gate_report -> 'hard_failures'::text)) = 'array'::text) AND (jsonb_typeof((quality_gate_report -> 'soft_warnings'::text)) = 'array'::text) AND (jsonb_typeof((quality_gate_report -> 'passed'::text)) = 'boolean'::text) AND ((quality_gate_report ->> 'report_hash'::text) ~ '^blake3:[0-9a-f]{64}$'::text))))",
    },
    ConstraintSpec {
        name: "ck_quant_model_version_training_objective",
        table: "quant_model_version",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(training_objective) = 'object'::text) AND (((training_objective ->> 'format_version'::text))::integer = 1) AND (jsonb_typeof((training_objective -> 'definition'::text)) = 'object'::text) AND (((training_objective -> 'definition'::text) ->> 'kind'::text) = ANY (ARRAY['learning_to_rank'::text, 'classical_pointwise'::text, 'hand_authored'::text]))))",
    },
    ConstraintSpec {
        name: "ck_quant_model_version_metrics",
        table: "quant_model_version",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(metrics) = 'object'::text) AND ((metrics ->> 'format_version'::text) = '1'::text) AND (jsonb_typeof((metrics -> 'definition'::text)) = 'object'::text) AND ((((metrics -> 'definition'::text) ->> 'kind'::text) = 'learning_to_rank'::text AND ((training_objective -> 'definition'::text) ->> 'kind'::text) = 'learning_to_rank'::text AND (jsonb_typeof(((metrics -> 'definition'::text) -> 'in_sample'::text)) = 'object'::text) AND (jsonb_typeof(((metrics -> 'definition'::text) -> 'validation'::text)) = 'object'::text) AND (jsonb_typeof(((metrics -> 'definition'::text) -> 'artifact_lineage'::text)) = 'object'::text) AND ((((metrics -> 'definition'::text) -> 'artifact_lineage'::text) ->> 'kind'::text) = ANY (ARRAY['factor_native'::text, 'fitted_feature_matrix'::text]))) OR (((metrics -> 'definition'::text) ->> 'kind'::text) = 'classical_pointwise'::text AND ((training_objective -> 'definition'::text) ->> 'kind'::text) = 'classical_pointwise'::text AND (jsonb_typeof(((metrics -> 'definition'::text) -> 'in_sample'::text)) = 'object'::text) AND (jsonb_typeof(((metrics -> 'definition'::text) -> 'validation'::text)) = 'object'::text) AND (jsonb_typeof(((metrics -> 'definition'::text) -> 'feature_importances'::text)) = 'array'::text) AND (jsonb_typeof(((metrics -> 'definition'::text) -> 'artifact_lineage'::text)) = 'object'::text) AND ((((metrics -> 'definition'::text) -> 'artifact_lineage'::text) ->> 'kind'::text) = 'fitted_feature_matrix'::text)) OR (((metrics -> 'definition'::text) ->> 'kind'::text) = 'not_measured'::text AND ((training_objective -> 'definition'::text) ->> 'kind'::text) = 'hand_authored'::text AND (jsonb_typeof(((metrics -> 'definition'::text) -> 'rationale'::text)) = 'string'::text) AND (char_length(btrim(((metrics -> 'definition'::text) ->> 'rationale'::text))) BETWEEN 1 AND 2048)))))",
    },
    ConstraintSpec {
        name: "ck_quant_model_version_derivation",
        table: "quant_model_version",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((derivation_kind = 'training'::qp_model_version_derivation_kind) AND (parent_model_version_id IS NULL) AND (source_backtest_report_id IS NULL) AND (calibration_artifact_id IS NULL) AND (score_multiplier_calibration_report IS NULL) AND (derivation_evidence_hash IS NULL)) OR ((derivation_kind = 'score_multiplier_calibration'::qp_model_version_derivation_kind) AND (parent_model_version_id IS NOT NULL) AND (parent_model_version_id <> model_version_id) AND (source_backtest_report_id IS NOT NULL) AND (calibration_artifact_id IS NULL) AND (jsonb_typeof(score_multiplier_calibration_report) = 'object'::text) AND (((score_multiplier_calibration_report ->> 'methodology_version'::text))::integer = 1) AND (((score_multiplier_calibration_report ->> 'minimum_stratum_samples'::text))::bigint > 0) AND (((score_multiplier_calibration_report ->> 'total_samples'::text))::bigint > 0) AND (derivation_evidence_hash ~ '^blake3:[0-9a-f]{64}$'::text)) OR ((derivation_kind = 'return_calibration'::qp_model_version_derivation_kind) AND (parent_model_version_id IS NOT NULL) AND (parent_model_version_id <> model_version_id) AND (source_backtest_report_id IS NULL) AND (calibration_artifact_id IS NOT NULL) AND (score_multiplier_calibration_report IS NULL) AND (derivation_evidence_hash ~ '^blake3:[0-9a-f]{64}$'::text))))",
    },
    ConstraintSpec {
        name: "fk-quant_model_version-source_backtest_report_id",
        table: "quant_model_version",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (source_backtest_report_id) REFERENCES public.quant_backtest_report(backtest_report_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "uq_quant_recommendation_identity",
        table: "quant_recommendation",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (recommendation_id, market_id, token_id)",
    },
    ConstraintSpec {
        name: "uq_quant_order_intent_execution_outcome_lineage",
        table: "quant_order_intent",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (order_intent_id, recommendation_id, execution_account_id, runtime_mode)",
    },
    ConstraintSpec {
        name: "uq_quant_execution_order_execution_outcome_lineage",
        table: "quant_execution_order",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (execution_order_id, order_intent_id, market_id, token_id)",
    },
    ConstraintSpec {
        name: "uq_quant_reconciliation_execution_outcome_lineage",
        table: "quant_reconciliation",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (reconciliation_id, execution_order_id, order_intent_id)",
    },
    ConstraintSpec {
        name: "uq_quant_position_execution_outcome_lineage",
        table: "quant_position",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (position_id, order_intent_id, execution_account_id, market_id, token_id)",
    },
    ConstraintSpec {
        name: "uq_quant_recommendation_execution_outcome_intent",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (order_intent_id)",
    },
    ConstraintSpec {
        name: "uq_quant_recommendation_execution_outcome_entry_order",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (entry_execution_order_id)",
    },
    ConstraintSpec {
        name: "uq_quant_recommendation_execution_outcome_entry_reconciliation",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (entry_reconciliation_id)",
    },
    ConstraintSpec {
        name: "uq_quant_recommendation_execution_outcome_position",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (position_id)",
    },
    ConstraintSpec {
        name: "fk_quant_recommendation_execution_outcome_recommendation_identity",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (recommendation_id, market_id, token_id) REFERENCES public.quant_recommendation(recommendation_id, market_id, token_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "fk_quant_recommendation_execution_outcome_intent_lineage",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (order_intent_id, recommendation_id, execution_account_id, runtime_mode) REFERENCES public.quant_order_intent(order_intent_id, recommendation_id, execution_account_id, runtime_mode) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "fk_quant_recommendation_execution_outcome_entry_order_lineage",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (entry_execution_order_id, order_intent_id, market_id, token_id) REFERENCES public.quant_execution_order(execution_order_id, order_intent_id, market_id, token_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "fk_quant_recommendation_execution_outcome_entry_reconciliation_lineage",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (entry_reconciliation_id, entry_execution_order_id, order_intent_id) REFERENCES public.quant_reconciliation(reconciliation_id, execution_order_id, order_intent_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "fk_quant_recommendation_execution_outcome_position_lineage",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (position_id, order_intent_id, execution_account_id, market_id, token_id) REFERENCES public.quant_position(position_id, order_intent_id, execution_account_id, market_id, token_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "ck_quant_recommendation_execution_outcome_contract",
        table: "quant_recommendation_execution_outcome",
        kind: ConstraintKind::Check,
        definition: "CHECK (((char_length(market_id) > 0) AND (char_length(token_id) > 0) AND (runtime_mode = ANY (ARRAY['semi_auto'::qp_quant_runtime_mode, 'auto_execution'::qp_quant_runtime_mode])) AND (requested_shares > (0)::numeric) AND (filled_shares >= (0)::numeric) AND (filled_shares <= requested_shares) AND ((entry_avg_price IS NULL) OR ((entry_avg_price >= (0)::numeric) AND (entry_avg_price <= (1)::numeric))) AND ((exit_avg_price IS NULL) OR ((exit_avg_price >= (0)::numeric) AND (exit_avg_price <= (1)::numeric))) AND ((entry_fee_usd IS NULL) OR (entry_fee_usd >= (0)::numeric)) AND ((exit_fee_usd IS NULL) OR (exit_fee_usd >= (0)::numeric)) AND ((settlement_payout_usd IS NULL) OR (settlement_payout_usd >= (0)::numeric)) AND ((max_adverse_excursion_bps IS NULL) OR (max_adverse_excursion_bps <= (0)::numeric)) AND ((max_favorable_excursion_bps IS NULL) OR (max_favorable_excursion_bps >= (0)::numeric)) AND (terminal_at <= source_observed_at) AND (source_observed_at <= available_at) AND (available_at <= created_at) AND (execution_fact_schema_version > 0) AND (source_checkpoint_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND (execution_fact_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND (outcome_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND (((terminal_state = 'unfilled'::qp_recommendation_execution_terminal_state) AND (filled_shares = (0)::numeric) AND (no_fill_reason IS NOT NULL) AND (entry_order_state = ANY (ARRAY['cancelled'::qp_execution_order_state, 'failed'::qp_execution_order_state])) AND (position_id IS NULL) AND (entry_avg_price IS NULL) AND (entry_filled_at IS NULL) AND (position_terminal_state IS NULL) AND (exit_reason IS NULL) AND (exit_filled_shares IS NULL) AND (exit_avg_price IS NULL) AND (exit_fee_usd IS NULL) AND (exit_at IS NULL) AND (settlement_payout_usd IS NULL) AND (realized_pnl_usd IS NULL) AND (max_adverse_excursion_bps IS NULL) AND (max_favorable_excursion_bps IS NULL)) OR ((terminal_state = ANY (ARRAY['partially_filled'::qp_recommendation_execution_terminal_state, 'fully_filled'::qp_recommendation_execution_terminal_state])) AND (no_fill_reason IS NULL) AND (position_id IS NOT NULL) AND (entry_avg_price IS NOT NULL) AND (entry_filled_at IS NOT NULL) AND (entry_filled_at <= terminal_at) AND (position_terminal_state = ANY (ARRAY['closed'::qp_position_ledger_state, 'settled'::qp_position_ledger_state])) AND (realized_pnl_usd IS NOT NULL) AND (((terminal_state = 'partially_filled'::qp_recommendation_execution_terminal_state) AND (filled_shares > (0)::numeric) AND (filled_shares < requested_shares) AND (entry_order_state = 'partially_filled'::qp_execution_order_state)) OR ((terminal_state = 'fully_filled'::qp_recommendation_execution_terminal_state) AND (filled_shares = requested_shares) AND (entry_order_state = 'filled'::qp_execution_order_state))) AND (((position_terminal_state = 'closed'::qp_position_ledger_state) AND (exit_reason IS NOT NULL) AND (exit_reason <> 'resolution_redeem'::qp_exit_reason) AND (exit_filled_shares = filled_shares) AND (exit_avg_price IS NOT NULL) AND (exit_at = terminal_at) AND (settlement_payout_usd IS NULL)) OR ((position_terminal_state = 'settled'::qp_position_ledger_state) AND (exit_reason = 'resolution_redeem'::qp_exit_reason) AND (settlement_payout_usd IS NOT NULL) AND (((exit_filled_shares IS NULL) AND (exit_avg_price IS NULL) AND (exit_fee_usd IS NULL) AND (exit_at IS NULL)) OR ((exit_filled_shares > (0)::numeric) AND (exit_filled_shares < filled_shares) AND (exit_avg_price IS NOT NULL) AND (exit_at IS NOT NULL) AND (exit_at <= terminal_at)))))))))",
    },
    ConstraintSpec {
        name: "fk_quant_recommendation_resolution_outcome_identity",
        table: "quant_recommendation_resolution_outcome",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (recommendation_id, market_id, token_id) REFERENCES public.quant_recommendation(recommendation_id, market_id, token_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "ck_quant_recommendation_resolution_outcome_contract",
        table: "quant_recommendation_resolution_outcome",
        kind: ConstraintKind::Check,
        definition: "CHECK (((char_length(market_id) > 0) AND (char_length(token_id) > 0) AND (resolved_at <= source_observed_at) AND (source_observed_at <= available_at) AND (available_at <= created_at) AND (resolution_fact_log_index >= 0) AND (resolution_fact_schema_version > 0) AND (source_checkpoint_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND (resolution_fact_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND (outcome_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND (token_payout_ratio >= (0)::numeric) AND (token_payout_ratio <= (1)::numeric) AND (((resolution_kind = 'winner_take_all'::qp_recommendation_resolution_kind) AND (token_payout_ratio = ANY (ARRAY[(0)::numeric, (1)::numeric]))) OR ((resolution_kind = 'split_payout'::qp_recommendation_resolution_kind) AND (token_payout_ratio > (0)::numeric) AND (token_payout_ratio < (1)::numeric)))))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_capital_base_usd_check",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK ((capital_base_usd >= (0)::numeric))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check1",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK (((valid_until IS NULL) OR (valid_until > decision_at)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check10",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK (((published_at IS NULL) OR (published_at >= decision_at)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check11",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK (((superseded_at IS NULL) OR (superseded_at >= published_at)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check12",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK (((obsoleted_at IS NULL) OR (obsoleted_at >= decision_at)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check13",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK (((expired_at IS NULL) OR (expired_at >= published_at)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check14",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK (((revoked_at IS NULL) OR (revoked_at >= decision_at)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check2",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK (((successor_report_id IS NULL) OR (successor_report_id <> recommendation_report_id)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check3",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = ANY (ARRAY['prepared'::qp_recommendation_report_status, 'published'::qp_recommendation_report_status])) AND (status_reason IS NULL)) OR ((status <> ALL (ARRAY['prepared'::qp_recommendation_report_status, 'published'::qp_recommendation_report_status])) AND (status_reason IS NOT NULL))))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check4",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'prepared'::qp_recommendation_report_status) AND (published_at IS NULL) AND (successor_report_id IS NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NULL) AND (expired_at IS NULL)) OR (status <> 'prepared'::qp_recommendation_report_status)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check5",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'published'::qp_recommendation_report_status) AND (published_at IS NOT NULL) AND (successor_report_id IS NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NULL) AND (expired_at IS NULL)) OR (status <> 'published'::qp_recommendation_report_status)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check6",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'superseded'::qp_recommendation_report_status) AND (published_at IS NOT NULL) AND (successor_report_id IS NOT NULL) AND (superseded_at IS NOT NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NULL) AND (expired_at IS NULL)) OR (status <> 'superseded'::qp_recommendation_report_status)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check7",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'obsolete'::qp_recommendation_report_status) AND (published_at IS NULL) AND (successor_report_id IS NOT NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NOT NULL) AND (revoked_at IS NULL) AND (expired_at IS NULL)) OR (status <> 'obsolete'::qp_recommendation_report_status)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check8",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'revoked'::qp_recommendation_report_status) AND (successor_report_id IS NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NOT NULL) AND (expired_at IS NULL)) OR (status <> 'revoked'::qp_recommendation_report_status)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_check9",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'expired'::qp_recommendation_report_status) AND (published_at IS NOT NULL) AND (successor_report_id IS NULL) AND (superseded_at IS NULL) AND (obsoleted_at IS NULL) AND (revoked_at IS NULL) AND (expired_at IS NOT NULL)) OR (status <> 'expired'::qp_recommendation_report_status)))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_horizon_secs_check",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK ((horizon_secs > 0))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_status_reason_check",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK (((status_reason IS NULL) OR ((char_length(status_reason) >= 1) AND (char_length(status_reason) <= 4096))))",
    },
    ConstraintSpec {
        name: "quant_recommendation_report_top_n_check",
        table: "quant_recommendation_report",
        kind: ConstraintKind::Check,
        definition: "CHECK (((top_n > 0) AND (top_n <= 1000)))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_check",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK (((bundle_bytes > 0) AND (recommendation_row_count >= 0) AND (funnel_row_count >= 0) AND (attempt_count >= 0)))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_check1",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK (((claim_owner IS NULL) = (lease_expires_at IS NULL)))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_check2",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'pending'::qp_report_fact_delivery_status) AND (attempt_count = 0) AND (claim_owner IS NULL) AND (next_attempt_at IS NULL) AND (last_error IS NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'pending'::qp_report_fact_delivery_status)))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_check3",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'delivering'::qp_report_fact_delivery_status) AND (attempt_count > 0) AND (claim_owner IS NOT NULL) AND (next_attempt_at IS NULL) AND (last_error IS NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'delivering'::qp_report_fact_delivery_status)))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_check4",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'retrying'::qp_report_fact_delivery_status) AND (attempt_count > 0) AND (claim_owner IS NULL) AND (next_attempt_at IS NOT NULL) AND (last_error IS NOT NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'retrying'::qp_report_fact_delivery_status)))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_check5",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'failed'::qp_report_fact_delivery_status) AND (attempt_count > 0) AND (claim_owner IS NULL) AND (next_attempt_at IS NULL) AND (last_error IS NOT NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'failed'::qp_report_fact_delivery_status)))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_check6",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'verified'::qp_report_fact_delivery_status) AND (attempt_count > 0) AND (next_attempt_at IS NULL) AND (last_error IS NULL) AND (verified_at IS NOT NULL)) OR (status <> 'verified'::qp_report_fact_delivery_status)))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_check7",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'cancelled'::qp_report_fact_delivery_status) AND (claim_owner IS NULL) AND (next_attempt_at IS NULL) AND (verified_at IS NULL) AND (announced_at IS NULL)) OR (status <> 'cancelled'::qp_report_fact_delivery_status)))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_check8",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK (((announced_at IS NULL) OR ((status = 'verified'::qp_report_fact_delivery_status) AND (claim_owner IS NULL) AND (announced_at >= verified_at))))",
    },
    ConstraintSpec {
        name: "quant_report_fact_delivery_last_error_check",
        table: "quant_report_fact_delivery",
        kind: ConstraintKind::Check,
        definition: "CHECK (((last_error IS NULL) OR ((char_length(last_error) >= 1) AND (char_length(last_error) <= 4096))))",
    },
    ConstraintSpec {
        name: "quant_report_run_check",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((trigger_kind = 'scheduled'::qp_report_trigger_kind) AND (schedule_id IS NOT NULL) AND (request_id IS NULL) AND (scheduled_for IS NOT NULL)) OR ((trigger_kind = 'ad_hoc'::qp_report_trigger_kind) AND (schedule_id IS NULL) AND (request_id IS NOT NULL) AND (scheduled_for IS NULL))))",
    },
    ConstraintSpec {
        name: "quant_report_run_check1",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((status <> 'queued'::qp_report_run_status) OR (trigger_kind = 'ad_hoc'::qp_report_trigger_kind) OR ((top_n IS NULL) AND (knowledge_lag_secs IS NULL))))",
    },
    ConstraintSpec {
        name: "quant_report_run_check10",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'succeeded'::qp_report_run_status) AND (started_at IS NOT NULL) AND (decision_at IS NOT NULL) AND (heartbeat_at IS NOT NULL) AND (decision_policy_snapshot_id IS NOT NULL) AND (top_n IS NOT NULL) AND (knowledge_lag_secs IS NOT NULL) AND (terminal_reason IS NULL) AND (error_code IS NULL) AND (error_summary IS NULL)) OR (status <> 'succeeded'::qp_report_run_status)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check11",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'failed'::qp_report_run_status) AND (started_at IS NOT NULL) AND (decision_at IS NOT NULL) AND (heartbeat_at IS NOT NULL) AND (decision_policy_snapshot_id IS NOT NULL) AND (top_n IS NOT NULL) AND (knowledge_lag_secs IS NOT NULL) AND (terminal_reason = 'build_failed'::qp_report_run_terminal_reason) AND (error_code IS NOT NULL) AND (error_summary IS NOT NULL)) OR (status <> 'failed'::qp_report_run_status)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check12",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'abandoned'::qp_report_run_status) AND (started_at IS NOT NULL) AND (decision_at IS NOT NULL) AND (heartbeat_at IS NOT NULL) AND (decision_policy_snapshot_id IS NOT NULL) AND (top_n IS NOT NULL) AND (knowledge_lag_secs IS NOT NULL) AND (terminal_reason = 'lease_expired'::qp_report_run_terminal_reason) AND (error_code IS NULL) AND (error_summary IS NULL)) OR (status <> 'abandoned'::qp_report_run_status)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check13",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((terminal_reason <> 'queue_expired'::qp_report_run_terminal_reason) OR (trigger_kind = 'ad_hoc'::qp_report_trigger_kind)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check14",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((terminal_reason <> ALL (ARRAY['coalesced_by_newer_occurrence'::qp_report_run_terminal_reason, 'schedule_reconfigured'::qp_report_run_terminal_reason])) OR (trigger_kind = 'scheduled'::qp_report_trigger_kind)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check15",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((started_at IS NULL) OR ((decision_at = started_at) AND (requested_at <= started_at))))",
    },
    ConstraintSpec {
        name: "quant_report_run_check16",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((finished_at IS NULL) OR (started_at IS NULL) OR (finished_at >= started_at)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check17",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((lease_expires_at IS NULL) OR (lease_expires_at > heartbeat_at)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check2",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((char_length(trigger_key) >= 1) AND (char_length(trigger_key) <= 512) AND ((schedule_id IS NULL) OR ((char_length(schedule_id) >= 1) AND (char_length(schedule_id) <= 128))) AND ((request_id IS NULL) OR ((char_length(request_id) >= 1) AND (char_length(request_id) <= 256)))))",
    },
    ConstraintSpec {
        name: "quant_report_run_check3",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((retry_of_run_id IS NULL) OR (trigger_kind = 'ad_hoc'::qp_report_trigger_kind)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check4",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((scheduled_for IS NULL) OR (scheduled_for <= requested_at)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check5",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'succeeded'::qp_report_run_status) AND (output_report_id IS NOT NULL)) OR ((status <> 'succeeded'::qp_report_run_status) AND (output_report_id IS NULL))))",
    },
    ConstraintSpec {
        name: "quant_report_run_check6",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'running'::qp_report_run_status) AND (lease_owner IS NOT NULL) AND (started_at IS NOT NULL) AND (decision_at IS NOT NULL) AND (heartbeat_at IS NOT NULL) AND (lease_expires_at IS NOT NULL) AND (decision_policy_snapshot_id IS NOT NULL) AND (top_n IS NOT NULL) AND (knowledge_lag_secs IS NOT NULL) AND (finished_at IS NULL) AND (terminal_reason IS NULL)) OR ((status <> 'running'::qp_report_run_status) AND (lease_owner IS NULL) AND (lease_expires_at IS NULL))))",
    },
    ConstraintSpec {
        name: "quant_report_run_check7",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((status = ANY (ARRAY['succeeded'::qp_report_run_status, 'failed'::qp_report_run_status, 'skipped'::qp_report_run_status, 'abandoned'::qp_report_run_status])) = (finished_at IS NOT NULL)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check8",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'queued'::qp_report_run_status) AND (started_at IS NULL) AND (decision_at IS NULL) AND (heartbeat_at IS NULL) AND (finished_at IS NULL) AND (decision_policy_snapshot_id IS NULL) AND (output_report_id IS NULL) AND (terminal_reason IS NULL) AND (error_code IS NULL) AND (error_summary IS NULL)) OR (status <> 'queued'::qp_report_run_status)))",
    },
    ConstraintSpec {
        name: "quant_report_run_check9",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'skipped'::qp_report_run_status) AND (started_at IS NULL) AND (decision_at IS NULL) AND (heartbeat_at IS NULL) AND (decision_policy_snapshot_id IS NULL) AND (output_report_id IS NULL) AND (terminal_reason = ANY (ARRAY['coalesced_by_newer_occurrence'::qp_report_run_terminal_reason, 'schedule_reconfigured'::qp_report_run_terminal_reason, 'queue_expired'::qp_report_run_terminal_reason])) AND (error_code IS NULL) AND (error_summary IS NULL)) OR (status <> 'skipped'::qp_report_run_status)))",
    },
    ConstraintSpec {
        name: "quant_report_run_error_code_check",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((error_code IS NULL) OR ((error_code)::text ~ '^[a-z][a-z0-9_]{0,127}$'::text)))",
    },
    ConstraintSpec {
        name: "quant_report_run_error_summary_check",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((error_summary IS NULL) OR ((char_length(error_summary) >= 1) AND (char_length(error_summary) <= 4096))))",
    },
    ConstraintSpec {
        name: "ck_role_code_canonical",
        table: "role",
        kind: ConstraintKind::Check,
        definition: "CHECK (((code)::text ~ '^[a-z][a-z0-9_]{0,63}$'::text))",
    },
    ConstraintSpec {
        name: "ck_quant_report_run_trigger_key",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((length((trigger_key)::text) >= 1) AND (length((trigger_key)::text) <= 256) AND (octet_length((trigger_key)::text) = length((trigger_key)::text)) AND ((trigger_key)::text ~ '^[[:graph:]]+$'::text) AND (position(chr(92) in (trigger_key)::text) = 0) AND (position(chr(34) in (trigger_key)::text) = 0)))",
    },
    ConstraintSpec {
        name: "quant_report_run_knowledge_lag_secs_check",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((knowledge_lag_secs IS NULL) OR (knowledge_lag_secs >= 0)))",
    },
    ConstraintSpec {
        name: "quant_report_run_top_n_check",
        table: "quant_report_run",
        kind: ConstraintKind::Check,
        definition: "CHECK (((top_n IS NULL) OR ((top_n > 0) AND (top_n <= 1000))))",
    },
    ConstraintSpec {
        name: "quant_report_schedule_gap_check",
        table: "quant_report_schedule_gap",
        kind: ConstraintKind::Check,
        definition: "CHECK ((first_scheduled_for <= last_scheduled_for))",
    },
    ConstraintSpec {
        name: "quant_report_schedule_gap_detail_check",
        table: "quant_report_schedule_gap",
        kind: ConstraintKind::Check,
        definition: "CHECK (((detail IS NULL) OR ((char_length(detail) >= 1) AND (char_length(detail) <= 4096))))",
    },
    ConstraintSpec {
        name: "quant_report_schedule_gap_missed_count_check",
        table: "quant_report_schedule_gap",
        kind: ConstraintKind::Check,
        definition: "CHECK ((missed_count > 0))",
    },
    ConstraintSpec {
        name: "quant_research_readiness_evidence_check",
        table: "quant_research_readiness_evidence",
        kind: ConstraintKind::Check,
        definition: "CHECK (((window_start < window_end) AND (window_end <= observed_at) AND (observed_at < expires_at) AND (length((artifact_version)::text) BETWEEN 1 AND 256) AND (octet_length((artifact_version)::text) = length((artifact_version)::text)) AND ((artifact_version)::text ~ '^[[:graph:]]+$'::text) AND (position(chr(92) in (artifact_version)::text) = 0) AND (position(chr(34) in (artifact_version)::text) = 0) AND (length((attestation_key_id)::text) BETWEEN 1 AND 256) AND (octet_length((attestation_key_id)::text) = length((attestation_key_id)::text)) AND ((attestation_key_id)::text ~ '^[[:graph:]]+$'::text) AND (position(chr(92) in (attestation_key_id)::text) = 0) AND (position(chr(34) in (attestation_key_id)::text) = 0)))",
    },
    ConstraintSpec {
        name: "ck_quant_research_job_params_kind",
        table: "quant_research_job",
        kind: ConstraintKind::Check,
        definition: "CHECK (((jsonb_typeof(params_json) = 'object'::text) AND (jsonb_typeof((params_json -> 'params'::text)) = 'object'::text) AND ((params_json ->> 'kind'::text) = (kind)::text)))",
    },
    ConstraintSpec {
        name: "ck_quant_research_job_result_reference",
        table: "quant_research_job",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((result_kind IS NULL) = (result_ref IS NULL)) AND ((status = 'succeeded'::qp_research_job_status) OR ((result_kind IS NULL) AND (result_ref IS NULL))) AND ((result_kind IS NULL) OR ((kind = 'dataset_build'::qp_research_job_kind) AND (result_kind = 'training_dataset'::qp_research_job_result_kind)) OR ((kind = 'model_train'::qp_research_job_kind) AND (result_kind = 'model_version'::qp_research_job_result_kind)) OR ((kind = 'backtest'::qp_research_job_kind) AND (result_kind = 'backtest_report'::qp_research_job_result_kind)) OR ((kind = 'cpcv_backtest'::qp_research_job_kind) AND (result_kind = 'backtest_path_set'::qp_research_job_result_kind)) OR ((kind = ANY (ARRAY['bias_table_fit'::qp_research_job_kind, 'model_calibration_fit'::qp_research_job_kind])) AND (result_kind = 'calibration_artifact'::qp_research_job_result_kind)) OR ((kind = 'feature_parity'::qp_research_job_kind) AND (result_kind = 'feature_parity_run'::qp_research_job_result_kind)) OR ((kind = 'trade_policy_fit'::qp_research_job_kind) AND (result_kind = 'trade_policy_artifact'::qp_research_job_result_kind)) OR ((kind = 'trade_policy_validation'::qp_research_job_kind) AND (result_kind = 'trade_policy_validation_run'::qp_research_job_result_kind)))))",
    },
    ConstraintSpec {
        name: "ck_quant_research_job_acting_role",
        table: "quant_research_job",
        kind: ConstraintKind::Check,
        definition: "CHECK (((acting_role)::text ~ '^[a-z][a-z0-9_]{0,63}$'::text))",
    },
    ConstraintSpec {
        name: "quant_source_slice_check",
        table: "quant_source_slice",
        kind: ConstraintKind::Check,
        definition: "CHECK (((window_start < window_end) AND (window_end <= pit_cutoff) AND ((reader_contract_version)::text ~ '^[A-Za-z0-9_.@-]{1,64}$'::text) AND ((schema_contract_version)::text ~ '^[A-Za-z0-9_.@-]{1,64}$'::text) AND (((status = 'materializing'::qp_source_slice_status) AND (manifest_uri IS NULL) AND (manifest_hash IS NULL) AND (manifest_json IS NULL) AND (failure_detail IS NULL) AND (completed_at IS NULL)) OR ((status = 'ready'::qp_source_slice_status) AND (manifest_uri IS NOT NULL) AND (manifest_hash IS NOT NULL) AND (manifest_json IS NOT NULL) AND (failure_detail IS NULL) AND (completed_at IS NOT NULL)) OR ((status = 'failed'::qp_source_slice_status) AND (manifest_uri IS NULL) AND (manifest_hash IS NULL) AND (manifest_json IS NULL) AND (failure_detail IS NOT NULL) AND (completed_at IS NOT NULL)))))",
    },
    ConstraintSpec {
        name: "ck_quant_execution_account_identity",
        table: "quant_execution_account",
        kind: ConstraintKind::Check,
        definition: "CHECK (((chain_id > 0) AND (funder_address ~ '^0x[0-9a-f]{40}$'::text) AND (owner_address ~ '^0x[0-9a-f]{40}$'::text) AND (controller_address ~ '^0x[0-9a-f]{40}$'::text) AND ((wallet_factory_address IS NULL) OR (wallet_factory_address ~ '^0x[0-9a-f]{40}$'::text)) AND ((wallet_implementation_code_hash IS NULL) OR (wallet_implementation_code_hash ~ '^0x[0-9a-f]{64}$'::text)) AND ((wallet_factory_address IS NULL) = (wallet_implementation_code_hash IS NULL)) AND (identity_digest ~ '^blake3:[0-9a-f]{64}$'::text) AND (((wallet_kind = 'eoa'::qp_execution_wallet_kind) AND (funder_address = owner_address) AND (owner_address = controller_address) AND (wallet_factory_address IS NULL)) OR ((wallet_kind = 'deposit_wallet'::qp_execution_wallet_kind) AND (wallet_factory_address IS NOT NULL)) OR (wallet_kind = ANY (ARRAY['proxy'::qp_execution_wallet_kind, 'gnosis_safe'::qp_execution_wallet_kind])))))",
    },
    ConstraintSpec {
        name: "uq_quant_order_intent_account_identity",
        table: "quant_order_intent",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (order_intent_id, execution_account_id)",
    },
    ConstraintSpec {
        name: "uq_quant_position_inventory_lineage",
        table: "quant_position",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (position_id, order_intent_id, execution_account_id)",
    },
    ConstraintSpec {
        name: "fk_quant_position_intent_account",
        table: "quant_position",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (order_intent_id, execution_account_id) REFERENCES public.quant_order_intent(order_intent_id, execution_account_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "uq_quant_settlement_redeem_account_identity",
        table: "quant_settlement_redeem",
        kind: ConstraintKind::Unique,
        definition: "UNIQUE (settlement_redeem_id, execution_account_id)",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_redeem_evm_identity",
        table: "quant_settlement_redeem",
        kind: ConstraintKind::Check,
        definition: "CHECK (((yes_token_id ~ '^(0|[1-9][0-9]{0,77})$'::text) AND (no_token_id ~ '^(0|[1-9][0-9]{0,77})$'::text) AND (yes_token_id <> no_token_id) AND (resolution_content_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND (char_length(resolution_outcome) BETWEEN 1 AND 256) AND (resolution_outcome = btrim(resolution_outcome)) AND (resolved_at <= created_at) AND (inventory_digest ~ '^blake3:[0-9a-f]{64}$'::text) AND (contributor_lots_digest ~ '^blake3:[0-9a-f]{64}$'::text) AND ((target_adapter IS NULL) OR (target_adapter ~ '^0x[0-9a-f]{40}$'::text)) AND ((target_code_hash IS NULL) OR (target_code_hash ~ '^0x[0-9a-f]{64}$'::text)) AND ((verified_block_hash IS NULL) OR (verified_block_hash ~ '^0x[0-9a-f]{64}$'::text)) AND ((deployment_evidence_version IS NULL) OR (deployment_evidence_version ~ '^[A-Za-z0-9_.@-]{1,64}$'::text))))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_inventory_lot",
        table: "quant_settlement_inventory_lot",
        kind: ConstraintKind::Check,
        definition: "CHECK (((inventory_digest ~ '^blake3:[0-9a-f]{64}$'::text) AND (contributor_lots_digest ~ '^blake3:[0-9a-f]{64}$'::text) AND (shares > 0::numeric) AND (cost_basis_usd >= 0::numeric) AND (position_version_at <= created_at) AND (intent_version_at <= created_at)))",
    },
    ConstraintSpec {
        name: "fk_quant_settlement_inventory_case_account",
        table: "quant_settlement_inventory_lot",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (settlement_redeem_id, execution_account_id) REFERENCES public.quant_settlement_redeem(settlement_redeem_id, execution_account_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "fk_quant_settlement_inventory_position_lineage",
        table: "quant_settlement_inventory_lot",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (position_id, order_intent_id, execution_account_id) REFERENCES public.quant_position(position_id, order_intent_id, execution_account_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "fk_quant_settlement_inventory_intent_account",
        table: "quant_settlement_inventory_lot",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (order_intent_id, execution_account_id) REFERENCES public.quant_order_intent(order_intent_id, execution_account_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_redeem_readiness_capability",
        table: "quant_settlement_redeem",
        kind: ConstraintKind::Check,
        definition: "CHECK ((jsonb_typeof(readiness_evidence_json) = 'object'::text AND jsonb_typeof((readiness_evidence_json -> 'reasons'::text)) = 'array'::text AND jsonb_typeof((readiness_evidence_json -> 'advisories'::text)) = 'array'::text AND (((readiness_status = 'ready'::qp_settlement_readiness_status) AND (jsonb_array_length((readiness_evidence_json -> 'reasons'::text)) = 0) AND (target_adapter IS NOT NULL) AND (target_code_hash IS NOT NULL) AND (deployment_digest IS NOT NULL) AND (deployment_evidence_version IS NOT NULL) AND (verified_block_number > 0) AND (verified_block_hash IS NOT NULL)) OR ((readiness_status = 'blocked'::qp_settlement_readiness_status) AND (jsonb_array_length((readiness_evidence_json -> 'reasons'::text)) > 0) AND (target_adapter IS NULL) AND (target_code_hash IS NULL) AND (deployment_digest IS NULL) AND (deployment_evidence_version IS NULL) AND (verified_block_number IS NULL) AND (verified_block_hash IS NULL)) OR ((readiness_status = 'unchecked'::qp_settlement_readiness_status) AND (jsonb_array_length((readiness_evidence_json -> 'reasons'::text)) = 0) AND (target_adapter IS NULL) AND (target_code_hash IS NULL) AND (deployment_digest IS NULL) AND (deployment_evidence_version IS NULL) AND (verified_block_number IS NULL) AND (verified_block_hash IS NULL)))))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_redeem_current_target",
        table: "quant_settlement_redeem",
        kind: ConstraintKind::Check,
        definition: "CHECK (((target_adapter IS NULL) OR ((route = 'standard_v2'::qp_settlement_route) AND (target_adapter = '0xada100db00ca00073811820692005400218fce1f'::text) AND (target_code_hash = '0x93b965351d01c1a128821ac79fc98a18105daefb46bda0d1e5b52306d713aa4f'::text)) OR ((route = 'neg_risk_v2'::qp_settlement_route) AND (target_adapter = '0xada2005600dec949baf300f4c6120000bdb6eaab'::text) AND (target_code_hash = '0x3b892c7c2f80e7af69f28faf72a51c2d793f6b79b96011bdf0a1996319fcbe5b'::text))))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_authorization_lifecycle",
        table: "quant_settlement_authorization",
        kind: ConstraintKind::Check,
        definition: "CHECK (((attempt_ordinal > 0) AND (scope_digest ~ '^blake3:[0-9a-f]{64}$'::text) AND (expires_at > created_at) AND (state <> 'not_required'::qp_settlement_authorization_state) AND (((state = 'pending'::qp_settlement_authorization_state) AND (approved_by IS NULL) AND (approved_at IS NULL) AND (revoked_by IS NULL) AND (revoked_at IS NULL) AND (consumed_at IS NULL) AND (expired_at IS NULL)) OR ((state = 'approved'::qp_settlement_authorization_state) AND (approved_by IS NOT NULL) AND (approved_at IS NOT NULL) AND (revoked_by IS NULL) AND (revoked_at IS NULL) AND (consumed_at IS NULL) AND (expired_at IS NULL)) OR ((state = 'revoked'::qp_settlement_authorization_state) AND (approved_by IS NOT NULL) AND (approved_at IS NOT NULL) AND (revoked_by IS NOT NULL) AND (revoked_at IS NOT NULL) AND (consumed_at IS NULL) AND (expired_at IS NULL)) OR ((state = 'consumed'::qp_settlement_authorization_state) AND (approved_by IS NOT NULL) AND (approved_at IS NOT NULL) AND (revoked_by IS NULL) AND (revoked_at IS NULL) AND (consumed_at IS NOT NULL) AND (expired_at IS NULL)) OR ((state = 'expired'::qp_settlement_authorization_state) AND (revoked_by IS NULL) AND (revoked_at IS NULL) AND (consumed_at IS NULL) AND (expired_at IS NOT NULL) AND ((approved_by IS NULL) = (approved_at IS NULL))))))",
    },
    ConstraintSpec {
        name: "fk_quant_settlement_redeem_current_authorization",
        table: "quant_settlement_redeem",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (current_authorization_id) REFERENCES public.quant_settlement_authorization(settlement_authorization_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_redeem_lifecycle",
        table: "quant_settlement_redeem",
        kind: ConstraintKind::Check,
        definition: "CHECK (((attempt_count >= 0) AND (retry_count >= 0) AND ((claim_owner IS NULL) = (lease_expires_at IS NULL)) AND ((expected_payout_usd IS NULL) OR (expected_payout_usd >= 0::numeric)) AND ((actual_payout_usd IS NULL) OR (actual_payout_usd >= 0::numeric)) AND ((last_error IS NULL) OR (char_length(last_error) BETWEEN 1 AND 2048)) AND ((state <> 'prepared'::qp_settlement_case_state) OR ((readiness_status = 'ready'::qp_settlement_readiness_status) AND (balance_before_json IS NOT NULL) AND (expected_payout_usd IS NOT NULL) AND (prepared_at IS NOT NULL))) AND ((state <> 'submitted'::qp_settlement_case_state) OR (submitted_at IS NOT NULL)) AND ((state <> 'retry_scheduled'::qp_settlement_case_state) OR ((failure_code IS NOT NULL) AND (next_attempt_at IS NOT NULL))) AND ((state <> 'reconciliation_required'::qp_settlement_case_state) OR ((failure_code IS NOT NULL) AND (reconciliation_state <> 'not_required'::qp_settlement_reconciliation_state))) AND ((state <> 'manual_required'::qp_settlement_case_state) OR (failure_code IS NOT NULL)) AND ((state <> 'confirmed'::qp_settlement_case_state) OR ((confirmed_at IS NOT NULL) AND (actual_payout_usd IS NOT NULL) AND (balance_after_json IS NOT NULL) AND (claim_owner IS NULL) AND (lease_expires_at IS NULL)))))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_governed_action_scope",
        table: "quant_settlement_governed_action",
        kind: ConstraintKind::Check,
        definition: "CHECK (((scope_digest ~ '^blake3:[0-9a-f]{64}$'::text) AND (char_length(idempotency_key) >= 1) AND (char_length(idempotency_key) <= 128) AND (char_length(authorization_reason) >= 1) AND (char_length(authorization_reason) <= 500) AND (authorization_reason = btrim(authorization_reason)) AND ((revocation_reason IS NULL) OR ((char_length(revocation_reason) >= 1) AND (char_length(revocation_reason) <= 500) AND (revocation_reason = btrim(revocation_reason)))) AND ((revocation_reason IS NULL) = (revoked_by IS NULL)) AND (expires_at > authorized_at) AND (retry_count >= 0) AND ((target_adapter IS NULL) OR (target_adapter ~ '^0x[0-9a-f]{40}$'::text)) AND ((deployment_digest IS NULL) OR (deployment_digest ~ '^blake3:[0-9a-f]{64}$'::text)) AND ((authorization_digest IS NULL) OR (authorization_digest ~ '^blake3:[0-9a-f]{64}$'::text)) AND ((deployment_evidence_version IS NULL) OR (deployment_evidence_version ~ '^[A-Za-z0-9_.@-]{1,64}$'::text)) AND ((verified_block_hash IS NULL) OR (verified_block_hash ~ '^0x[0-9a-f]{64}$'::text)) AND ((verified_block_number IS NULL) = (verified_block_hash IS NULL)) AND ((claim_owner IS NULL) = (lease_expires_at IS NULL)) AND ((last_error IS NULL) OR ((char_length(last_error) >= 1) AND (char_length(last_error) <= 2048))) AND (((kind = 'outcome_token_approval'::qp_settlement_governed_action_kind) AND (settlement_redeem_id IS NULL) AND (route IS NOT NULL) AND (target_adapter IS NOT NULL) AND (deployment_digest IS NOT NULL) AND (deployment_evidence_version IS NOT NULL) AND (verified_block_number > 0) AND (desired_approval IS TRUE) AND (authorization_digest IS NULL) AND (payout_ceiling_usd IS NULL)) OR ((kind = 'outcome_token_revocation'::qp_settlement_governed_action_kind) AND (settlement_redeem_id IS NULL) AND (route IS NOT NULL) AND (target_adapter IS NOT NULL) AND (deployment_digest IS NOT NULL) AND (deployment_evidence_version IS NOT NULL) AND (verified_block_number > 0) AND (desired_approval IS FALSE) AND (authorization_digest IS NULL) AND (payout_ceiling_usd IS NULL)) OR ((kind = 'canary_grant'::qp_settlement_governed_action_kind) AND (settlement_redeem_id IS NOT NULL) AND (route IS NOT NULL) AND (target_adapter IS NOT NULL) AND (deployment_digest IS NOT NULL) AND (deployment_evidence_version IS NOT NULL) AND (verified_block_number > 0) AND (desired_approval IS NULL) AND (authorization_digest IS NOT NULL) AND (payout_ceiling_usd > 0::numeric)))))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_governed_action_lifecycle",
        table: "quant_settlement_governed_action",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((state = 'authorized'::qp_settlement_governed_action_state) AND (consumed_at IS NULL) AND (revoked_by IS NULL) AND (revoked_at IS NULL) AND (failure_code IS NULL) AND (next_attempt_at IS NOT NULL)) OR ((state = 'retry_scheduled'::qp_settlement_governed_action_state) AND (consumed_at IS NULL) AND (revoked_by IS NULL) AND (revoked_at IS NULL) AND (failure_code IS NOT NULL) AND (next_attempt_at IS NOT NULL)) OR ((state = 'consumed'::qp_settlement_governed_action_state) AND (consumed_at IS NOT NULL) AND (revoked_by IS NULL) AND (revoked_at IS NULL) AND (claim_owner IS NULL) AND (lease_expires_at IS NULL) AND (next_attempt_at IS NULL)) OR ((state = 'revoked'::qp_settlement_governed_action_state) AND (consumed_at IS NULL) AND (revoked_by IS NOT NULL) AND (revoked_at IS NOT NULL) AND (claim_owner IS NULL) AND (lease_expires_at IS NULL) AND (next_attempt_at IS NULL)) OR ((state = 'expired'::qp_settlement_governed_action_state) AND (consumed_at IS NULL) AND (revoked_by IS NULL) AND (revoked_at IS NULL) AND (claim_owner IS NULL) AND (lease_expires_at IS NULL) AND (next_attempt_at IS NULL)) OR ((state = ANY (ARRAY['reconciliation_required'::qp_settlement_governed_action_state, 'failed'::qp_settlement_governed_action_state])) AND (consumed_at IS NULL) AND (failure_code IS NOT NULL) AND (last_error IS NOT NULL) AND (claim_owner IS NULL) AND (lease_expires_at IS NULL) AND (next_attempt_at IS NULL))))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_external_cursor_identity",
        table: "quant_settlement_external_cursor",
        kind: ConstraintKind::Check,
        definition: "CHECK (((chain_id > 0) AND (target_adapter ~ '^0x[0-9a-f]{40}$'::text) AND (target_code_hash ~ '^0x[0-9a-f]{64}$'::text) AND (deployment_digest ~ '^blake3:[0-9a-f]{64}$'::text) AND (deployment_evidence_version ~ '^[A-Za-z0-9_.@-]{1,64}$'::text) AND (next_block_number >= 0) AND ((last_observed_block_number IS NULL) = (last_observed_block_hash IS NULL)) AND ((last_observed_block_number IS NULL) OR ((last_observed_block_number >= 0) AND (last_observed_block_hash ~ '^0x[0-9a-f]{64}$'::text) AND (next_block_number = (last_observed_block_number + 1))))))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_chain_submission_identity",
        table: "quant_settlement_chain_submission",
        kind: ConstraintKind::Check,
        definition: "CHECK (((target_adapter ~ '^0x[0-9a-f]{40}$'::text) AND (target_code_hash ~ '^0x[0-9a-f]{64}$'::text) AND (conditional_tokens = '0x4d97dcd97ec945f40cf65f87097ace5ea0476045'::text) AND (collateral_token = '0xc011a7e12a19f7b1f670d46f03b03f3342e82dfb'::text) AND (usdce = '0x2791bca1f2de4661ed88a30c99a7a9449aa84174'::text) AND (call_target ~ '^0x[0-9a-f]{40}$'::text) AND (verified_block_number > 0) AND (verified_block_hash ~ '^0x[0-9a-f]{64}$'::text) AND ((prepared_block_number IS NULL) = (prepared_block_hash IS NULL)) AND ((prepared_block_number IS NULL) OR ((prepared_block_number > 0) AND (prepared_block_hash ~ '^0x[0-9a-f]{64}$'::text))) AND (calldata_hash ~ '^0x[0-9a-f]{64}$'::text) AND (octet_length(calldata) > 0) AND ((signed_envelope IS NULL) = (signed_envelope_hash IS NULL)) AND ((signed_envelope IS NULL) = (prepared_nonce IS NULL)) AND ((signed_envelope IS NULL) OR ((octet_length(signed_envelope) > 0) AND (signed_envelope_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND (prepared_nonce ~ '^(0|[1-9][0-9]{0,77})$'::text) AND ((char_length(prepared_nonce) < 78) OR (prepared_nonce <= '115792089237316195423570985008687907853269984665640564039457584007913129639935'::text)) AND ((gas_limit IS NULL) OR ((gas_limit ~ '^(0|[1-9][0-9]{0,77})$'::text) AND ((char_length(gas_limit) < 78) OR (gas_limit <= '115792089237316195423570985008687907853269984665640564039457584007913129639935'::text)))))) AND ((transaction_hash IS NULL) OR (transaction_hash ~ '^0x[0-9a-f]{64}$'::text)) AND (deployment_evidence_version ~ '^[A-Za-z0-9_.@-]{1,64}$'::text) AND (attempt_ordinal > 0) AND ((last_error IS NULL) OR (char_length(last_error) BETWEEN 1 AND 2048)) AND (jsonb_typeof(failure_history_json) = 'object'::text) AND (jsonb_typeof((failure_history_json -> 'entries'::text)) = 'array'::text)))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_chain_submission_parent",
        table: "quant_settlement_chain_submission",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((settlement_redeem_id IS NOT NULL)::integer + (settlement_governed_action_id IS NOT NULL)::integer) = 1 AND (((purpose = 'redeem'::qp_settlement_submission_purpose) AND (settlement_redeem_id IS NOT NULL) AND (settlement_governed_action_id IS NULL)) OR ((purpose = ANY (ARRAY['outcome_token_approval'::qp_settlement_submission_purpose, 'outcome_token_revocation'::qp_settlement_submission_purpose])) AND (settlement_redeem_id IS NULL) AND (settlement_governed_action_id IS NOT NULL))) AND ((canary_action_id IS NULL) OR ((purpose = 'redeem'::qp_settlement_submission_purpose) AND (settlement_redeem_id IS NOT NULL)))))",
    },
    ConstraintSpec {
        name: "fk_quant_settlement_chain_submission_canary_action",
        table: "quant_settlement_chain_submission",
        kind: ConstraintKind::ForeignKey,
        definition: "FOREIGN KEY (canary_action_id) REFERENCES public.quant_settlement_governed_action(settlement_governed_action_id) ON UPDATE NO ACTION ON DELETE NO ACTION",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_chain_submission_scope",
        table: "quant_settlement_chain_submission",
        kind: ConstraintKind::Check,
        definition: "CHECK (((((route = 'standard_v2'::qp_settlement_route) AND (target_adapter = '0xada100db00ca00073811820692005400218fce1f'::text) AND (target_code_hash = '0x93b965351d01c1a128821ac79fc98a18105daefb46bda0d1e5b52306d713aa4f'::text)) OR ((route = 'neg_risk_v2'::qp_settlement_route) AND (target_adapter = '0xada2005600dec949baf300f4c6120000bdb6eaab'::text) AND (target_code_hash = '0x3b892c7c2f80e7af69f28faf72a51c2d793f6b79b96011bdf0a1996319fcbe5b'::text))) AND ((kind <> 'externally_observed'::qp_settlement_submission_kind) OR (state = ANY (ARRAY['awaiting_finality'::qp_settlement_submission_state, 'confirmed'::qp_settlement_submission_state, 'failed'::qp_settlement_submission_state])))))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_chain_submission_state_identity",
        table: "quant_settlement_chain_submission",
        kind: ConstraintKind::Check,
        definition: "CHECK (((state NOT IN ('prepared'::qp_settlement_submission_state, 'dispatching'::qp_settlement_submission_state)) OR ((kind <> 'externally_observed'::qp_settlement_submission_kind) AND (prepared_block_number IS NOT NULL))) AND ((state <> 'awaiting_chain_hash'::qp_settlement_submission_state) OR ((kind = 'relayer'::qp_settlement_submission_kind) AND (relayer_transaction_id IS NOT NULL) AND (transaction_hash IS NULL))) AND ((state NOT IN ('awaiting_finality'::qp_settlement_submission_state, 'confirmed'::qp_settlement_submission_state)) OR ((transaction_hash IS NOT NULL) AND ((kind <> 'relayer'::qp_settlement_submission_kind) OR (relayer_transaction_id IS NOT NULL)))) AND ((kind <> 'direct_eoa'::qp_settlement_submission_kind) OR ((relayer_transaction_id IS NULL) AND (signed_envelope IS NOT NULL) AND (signed_envelope_hash IS NOT NULL) AND (prepared_nonce IS NOT NULL) AND (gas_limit IS NOT NULL) AND (transaction_hash IS NOT NULL))) AND ((kind <> 'relayer'::qp_settlement_submission_kind) OR ((signed_envelope IS NOT NULL) AND (signed_envelope_hash IS NOT NULL) AND (prepared_nonce IS NOT NULL))) AND ((kind <> 'externally_observed'::qp_settlement_submission_kind) OR ((signed_envelope IS NULL) AND (signed_envelope_hash IS NULL) AND (prepared_nonce IS NULL) AND (gas_limit IS NULL) AND (relayer_transaction_id IS NULL) AND (transaction_hash IS NOT NULL))) AND ((state <> 'confirmed'::qp_settlement_submission_state) OR ((confirmed_at IS NOT NULL) AND (receipt_evidence_json IS NOT NULL))) AND ((receipt_evidence_json IS NULL) OR (jsonb_typeof(receipt_evidence_json) = 'object'::text)))",
    },
    ConstraintSpec {
        name: "ck_quant_settlement_chain_submission_purpose_target",
        table: "quant_settlement_chain_submission",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((purpose = 'redeem'::qp_settlement_submission_purpose) AND (call_target = target_adapter)) OR ((purpose = ANY (ARRAY['outcome_token_approval'::qp_settlement_submission_purpose, 'outcome_token_revocation'::qp_settlement_submission_purpose])) AND (kind <> 'externally_observed'::qp_settlement_submission_kind) AND (call_target = conditional_tokens))))",
    },
    ConstraintSpec {
        name: "ck_quant_execution_trade_ref_identity",
        table: "quant_execution_trade_ref",
        kind: ConstraintKind::Check,
        definition: "CHECK (((char_length(venue_trade_id) >= 1) AND (char_length(venue_trade_id) <= 256) AND ((transaction_hash IS NULL) OR (transaction_hash ~ '^0x[0-9a-f]{64}$'::text)) AND ((trade_status IS NULL) OR (trade_status NOT IN ('mined'::qp_venue_trade_status, 'confirmed'::qp_venue_trade_status)) OR (transaction_hash IS NOT NULL))))",
    },
    ConstraintSpec {
        name: "ck_quant_execution_transaction_ref_hash",
        table: "quant_execution_transaction_ref",
        kind: ConstraintKind::Check,
        definition: "CHECK ((transaction_hash ~ '^0x[0-9a-f]{64}$'::text))",
    },
    ConstraintSpec {
        name: "ck_quant_trade_tape_block_cursor_contract_address",
        table: "quant_trade_tape_block_cursor",
        kind: ConstraintKind::Check,
        definition: "CHECK (((contract_address)::text ~ '^0x[0-9a-f]{40}$'::text))",
    },
    ConstraintSpec {
        name: "quant_trade_policy_trial_attempt_check",
        table: "quant_trade_policy_trial_attempt",
        kind: ConstraintKind::Check,
        definition: "CHECK (((attempt_ordinal >= 0) AND (length((candidate_id)::text) BETWEEN 1 AND 128) AND (octet_length((candidate_id)::text) = length((candidate_id)::text)) AND ((candidate_id)::text ~ '^[[:graph:]]+$'::text) AND (position(chr(92) in (candidate_id)::text) = 0) AND (position(chr(34) in (candidate_id)::text) = 0) AND ((fold_index IS NULL) OR (fold_index >= 0)) AND ((path_index IS NULL) OR (path_index >= 0)) AND ((evidence_row_count IS NULL) OR (evidence_row_count >= 0))))",
    },
    ConstraintSpec {
        name: "quant_trade_policy_trial_attempt_check1",
        table: "quant_trade_policy_trial_attempt",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((scope = ANY (ARRAY['candidate'::qp_trade_policy_trial_scope, 'latency_stress'::qp_trade_policy_trial_scope])) AND (fold_index IS NULL) AND (path_index IS NULL)) OR ((scope = 'fold'::qp_trade_policy_trial_scope) AND (fold_index IS NOT NULL) AND (path_index IS NULL)) OR ((scope = 'path'::qp_trade_policy_trial_scope) AND (fold_index IS NULL) AND (path_index IS NOT NULL))))",
    },
    ConstraintSpec {
        name: "quant_trade_policy_trial_attempt_check2",
        table: "quant_trade_policy_trial_attempt",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status = 'succeeded'::qp_trade_policy_trial_status) AND (metrics_json IS NOT NULL) AND (failure_detail IS NULL) AND (evidence_uri IS NOT NULL) AND (evidence_hash IS NOT NULL) AND (evidence_row_count IS NOT NULL)) OR ((status = ANY (ARRAY['failed'::qp_trade_policy_trial_status, 'cancelled'::qp_trade_policy_trial_status])) AND (metrics_json IS NULL) AND ((length(btrim(failure_detail)) >= 1) AND (length(btrim(failure_detail)) <= 8192)))))",
    },
    ConstraintSpec {
        name: "quant_trade_policy_trial_attempt_check3",
        table: "quant_trade_policy_trial_attempt",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((evidence_uri IS NULL) AND (evidence_hash IS NULL) AND (evidence_row_count IS NULL)) OR ((evidence_uri IS NOT NULL) AND (evidence_hash IS NOT NULL) AND (evidence_row_count IS NOT NULL))))",
    },
    ConstraintSpec {
        name: "quant_trade_policy_validation_check",
        table: "quant_trade_policy_validation",
        kind: ConstraintKind::Check,
        definition: "CHECK (((total_rows >= 0) AND (passed_rows >= 0) AND (failed_rows >= 0) AND ((passed_rows + failed_rows) <= total_rows) AND ((length(btrim(reason)) >= 1) AND (length(btrim(reason)) <= 512)) AND (((status = 'running'::qp_trade_policy_validation_status) AND (validation_hash IS NULL) AND (failure_detail IS NULL) AND (completed_at IS NULL)) OR ((status = 'succeeded'::qp_trade_policy_validation_status) AND (validation_hash IS NOT NULL) AND (failure_detail IS NULL) AND (completed_at IS NOT NULL) AND (failed_rows = 0) AND (passed_rows = total_rows) AND (total_rows > 0)) OR ((status = ANY (ARRAY['failed'::qp_trade_policy_validation_status, 'cancelled'::qp_trade_policy_validation_status])) AND (validation_hash IS NOT NULL) AND (failure_detail IS NOT NULL) AND (completed_at IS NOT NULL)))))",
    },
    ConstraintSpec {
        name: "quant_trade_policy_validation_row_check",
        table: "quant_trade_policy_validation_row",
        kind: ConstraintKind::Check,
        definition: "CHECK (((row_ordinal >= 0) AND (record_key <> ''::text) AND ((evidence_kind)::text = ANY (ARRAY[('observation_eligibility'::character varying)::text, ('fills'::character varying)::text, ('candidate_trials'::character varying)::text, ('cohort_trials'::character varying)::text, ('cpcv_paths'::character varying)::text, ('coverage_gaps'::character varying)::text, ('statistical_summaries'::character varying)::text])) AND ((expected_row_hash IS NOT NULL) OR (actual_row_hash IS NOT NULL)) AND ((diagnostic_kind IS NULL) OR ((diagnostic_kind)::text ~ '^[a-z][a-z0-9_]{0,127}$'::text)) AND ((passed AND (expected_row_hash = actual_row_hash) AND (diagnostic_kind IS NULL) AND (detail IS NULL)) OR ((NOT passed) AND (diagnostic_kind IS NOT NULL) AND (detail IS NOT NULL)))))",
    },
    ConstraintSpec {
        name: "quant_training_dataset_check",
        table: "quant_training_dataset",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((status <> ALL (ARRAY['planned'::qp_training_dataset_status, 'building'::qp_training_dataset_status])) OR ((feature_schema_version IS NOT NULL) AND (sample_sources IS NOT NULL) AND (feature_schema_hash IS NULL) AND (factor_schema_hash IS NULL) AND (label_schema_hash IS NULL) AND (dataset_hash IS NULL) AND (manifest_hash IS NULL) AND (manifest_json IS NULL) AND (artifact_bytes_hash IS NULL) AND (parquet_uri IS NULL) AND (sample_count IS NULL) AND (coverage_json IS NULL) AND (completed_at IS NULL))) AND ((status <> ALL (ARRAY['ready'::qp_training_dataset_status, 'insufficient_labels'::qp_training_dataset_status])) OR ((feature_schema_version IS NOT NULL) AND (sample_sources IS NOT NULL) AND (feature_schema_hash IS NOT NULL) AND (factor_schema_hash IS NOT NULL) AND (label_schema_hash IS NOT NULL) AND (dataset_hash IS NOT NULL) AND (manifest_hash IS NOT NULL) AND (manifest_json IS NOT NULL) AND (artifact_bytes_hash IS NOT NULL) AND (parquet_uri IS NOT NULL) AND (sample_count IS NOT NULL) AND (sample_count >= 0) AND (coverage_json IS NOT NULL) AND (completed_at IS NOT NULL))) AND ((status <> 'failed'::qp_training_dataset_status) OR (completed_at IS NOT NULL))))",
    },
    ConstraintSpec {
        name: "ck_policy_approval_expiry",
        table: "policy_approval",
        kind: ConstraintKind::Check,
        definition: "CHECK (((expires_at IS NULL) OR (expires_at > decided_at)))",
    },
    ConstraintSpec {
        name: "ck_policy_approval_reason",
        table: "policy_approval",
        kind: ConstraintKind::Check,
        definition: "CHECK (((length(reason) >= 1) AND (length(reason) <= 2048)))",
    },
    ConstraintSpec {
        name: "ck_policy_approval_validation_subject",
        table: "policy_approval",
        kind: ConstraintKind::Check,
        definition: "CHECK ((((decision <> 'approved'::qp_policy_approval_decision) OR (validation_subject IS NOT NULL)) AND ((validation_subject IS NULL) OR ((jsonb_typeof(validation_subject) = 'object'::text) AND (validation_subject ?& ARRAY['base_generation'::text, 'base_revision_vector'::text, 'candidate_bundle_hash'::text])))))",
    },
    ConstraintSpec {
        name: "ck_schema_migration_audit_algorithm",
        table: "schema_migration_audit",
        kind: ConstraintKind::Check,
        definition: "CHECK (((checksum_algorithm)::text = 'blake3-256'::text))",
    },
    ConstraintSpec {
        name: "ck_schema_migration_audit_artifact_length",
        table: "schema_migration_audit",
        kind: ConstraintKind::Check,
        definition: "CHECK ((artifact_length > 0))",
    },
    ConstraintSpec {
        name: "ck_schema_migration_audit_checksum",
        table: "schema_migration_audit",
        kind: ConstraintKind::Check,
        definition: "CHECK ((checksum ~ '^[0-9a-f]{64}$'::text))",
    },
    ConstraintSpec {
        name: "ck_policy_profile_artifact_identity",
        table: "policy_profile_artifact",
        kind: ConstraintKind::Check,
        definition: "CHECK (((schema_version = 1) AND (content_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND ((document ->> 'profile_kind'::text) = (kind)::text)))",
    },
    ConstraintSpec {
        name: "ck_research_profile_artifact_identity",
        table: "research_profile_artifact",
        kind: ConstraintKind::Check,
        definition: "CHECK (((version > 0) AND (research_profile_id ~ '^[a-z0-9_]+$'::text) AND (content_hash ~ '^blake3:[0-9a-f]{64}$'::text) AND (research_profile_artifact_id = (((('rpa:'::text || research_profile_id) || ':'::text) || version::text) || ':'::text) || content_hash)))",
    },
    ConstraintSpec {
        name: "ck_system_runtime_control_singleton",
        table: "system_runtime_control",
        kind: ConstraintKind::Check,
        definition: "CHECK ((id = 1))",
    },
    ConstraintSpec {
        name: "ck_system_runtime_control_revision",
        table: "system_runtime_control",
        kind: ConstraintKind::Check,
        definition: "CHECK ((revision >= 0))",
    },
    ConstraintSpec {
        name: "ck_system_runtime_control_transition_revision",
        table: "system_runtime_control_transition",
        kind: ConstraintKind::Check,
        definition: "CHECK (((from_revision >= 0) AND (to_revision = (from_revision + 1))))",
    },
];

pub async fn apply(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    for spec in CONSTRAINTS {
        v1::create_constraint(manager, *spec)
            .await
            .map_err(|error| {
                DbErr::Custom(format!(
                    "constraint `{}` on `{}` failed: {error}",
                    spec.name, spec.table
                ))
            })?;
    }
    Ok(())
}
