//! Quant-pivot Postgres repository implementations.
mod account_chain_execution;
mod account_pause;
mod account_recovery;
mod account_snapshot;
mod attribution_artifact;
mod backtest_path_set;
mod backtest_report;
mod basis_alert;
mod calibration_artifact;
mod capital_allocation;
mod comparison_report;
pub(crate) mod condition_wake;
mod dataset;
mod domain_projection;
mod domain_source_cursor;
mod domain_source_expectation;
mod entry_condition;
mod equity_snapshot;
mod exchange_history;
mod execution_account;
mod execution_attempt_outcome;
mod execution_order;
mod execution_submission;
mod factor;
mod feature;
mod feature_parity;
mod feedback_cohort;
mod feedback_cycle;
mod feedback_recipe;
mod feedback_scheduler;
mod fresh_boot;
mod governance_audit;
mod integrity;
mod market_linkage;
mod market_selection;
mod model_candidate_manifest;
mod model_registry;
mod model_route_bootstrap;
mod model_route_promotion;
mod model_route_shadow_binding;
mod model_run;
mod order_intent;
mod portfolio_plan;
mod promotion_permit;
mod recommendation;
mod recommendation_execution_rollup;
mod recommendation_report;
mod recommendation_resolution_outcome;
mod reconciliation;
mod report_run;
mod report_scope;
mod research_job;
mod research_profile;
mod research_readiness;
mod reserved_capital;
mod resolution_observation;
mod runtime_activity;
pub mod settlement_governance;
pub mod settlement_redeem;
mod shadow_comparison;
mod source_slice;
mod strategy_position_lot;
mod trade_policy;
mod venue_incentive;

pub use account_chain_execution::PgAccountChainExecutionRepository;
pub use account_pause::PgAccountPauseRepository;
pub use account_recovery::PgAccountRecoveryRepository;
pub use account_snapshot::PgAccountSnapshotRepository;
pub use attribution_artifact::PgAttributionArtifactRepository;
pub use backtest_path_set::PgBacktestPathSetRepository;
pub use backtest_report::PgBacktestReportRepository;
pub use basis_alert::PgBasisAlertRepository;
pub use calibration_artifact::PgCalibrationArtifactRepository;
pub use capital_allocation::PgCapitalAllocationRepository;
pub use comparison_report::PgModelComparisonReportRepository;
pub use dataset::PgTrainingDatasetRepository;
pub use domain_projection::PgDomainProjectionRepository;
pub use domain_source_cursor::PgDomainSourceCursorRepository;
pub use domain_source_expectation::PgDomainSourceExpectationRepository;
pub use entry_condition::PgEntryConditionRepository;
pub use equity_snapshot::PgEquitySnapshotRepository;
pub use exchange_history::PgExchangeHistoryRepository;
pub use execution_account::PgExecutionAccountRepository;
pub use execution_attempt_outcome::PgExecutionAttemptOutcomeRepository;
pub use execution_order::PgExecutionOrderRepository;
pub use execution_submission::PgExecutionSubmissionRepository;
pub use factor::PgFactorRepository;
pub use feature::PgFeatureRepository;
pub use feature_parity::PgFeatureParityRepository;
pub use feedback_cohort::PgFeedbackCohortRepository;
pub use feedback_cycle::PgFeedbackCycleRepository;
pub use feedback_recipe::PgFeedbackRecipeTemplateRepository;
pub use feedback_scheduler::PgFeedbackSchedulerRepository;
pub use fresh_boot::PgFreshBootRepository;
pub use governance_audit::PgModelGovernanceAuditRepository;
pub use market_linkage::PgMarketLinkageRepository;
pub use market_selection::PgMarketSelectionRepository;
pub use model_candidate_manifest::PgModelCandidateManifestRepository;
pub use model_registry::PgModelRegistryRepository;
pub use model_route_bootstrap::PgModelRouteBootstrapRepository;
pub use model_route_promotion::PgModelRoutePromotionRepository;
pub use model_route_shadow_binding::PgModelRouteShadowBindingRepository;
pub use model_run::PgModelRunRepository;
pub use order_intent::PgOrderIntentRepository;
pub use portfolio_plan::PgPortfolioPlanRepository;
pub use promotion_permit::PgPromotionPermitRepository;
pub use recommendation::PgRecommendationRepository;
pub use recommendation_execution_rollup::PgRecommendationExecutionRollupRepository;
pub use recommendation_report::PgRecommendationReportRepository;
pub use recommendation_resolution_outcome::PgRecommendationResolutionOutcomeRepository;
pub use reconciliation::PgReconciliationRepository;
pub use report_run::PgReportRunRepository;
pub use research_job::PgResearchJobRepository;
pub use research_readiness::PgResearchReadinessEvidenceRepository;
pub use reserved_capital::PgReservedCapitalRepository;
pub use resolution_observation::PgResolutionObservationRepository;
pub use runtime_activity::PgRuntimeActivityRepository;
pub use shadow_comparison::PgShadowComparisonRepository;
pub use source_slice::PgSourceSliceRepository;
pub use strategy_position_lot::PgStrategyPositionLotRepository;
pub use trade_policy::PgTradePolicyRepository;
pub use venue_incentive::PgVenueIncentiveRepository;
