//! Quant-pivot Postgres repository implementations.
mod account_snapshot;
mod attribution;
mod backtest_path_set;
mod backtest_report;
mod basis_alert;
mod calibration_artifact;
mod capital_allocation;
mod comparison_report;
pub(crate) mod condition_wake;
mod dataset;
mod domain_projection;
mod domain_source_cursor;
mod domain_source_expectation;
mod entry_condition;
mod equity_snapshot;
mod execution_account;
mod execution_order;
mod execution_submission;
mod factor;
mod feature;
mod feature_parity;
mod governance_audit;
mod market_linkage;
mod market_selection;
mod model_registry;
mod model_run;
mod order_intent;
mod portfolio_plan;
mod position;
mod recommendation;
mod recommendation_report;
mod reconciliation;
mod report_run;
mod report_scope;
mod research_job;
pub(crate) mod research_profile;
mod research_readiness;
mod reserved_capital;
pub mod settlement_governance;
pub mod settlement_redeem;
mod shadow_comparison;
mod source_slice;
mod trade_policy;
mod trade_tape_block_cursor;

pub use account_snapshot::PgAccountSnapshotRepository;
pub use attribution::PgAttributionRepository;
pub use backtest_path_set::PgBacktestPathSetRepository;
pub use backtest_report::PgBacktestReportRepository;
pub use basis_alert::PgBasisAlertRepository;
pub use calibration_artifact::PgCalibrationArtifactRepository;
pub use capital_allocation::PgCapitalAllocationRepository;
pub use comparison_report::PgModelComparisonReportRepository;
pub use dataset::PgTrainingDatasetRepository;
pub use domain_projection::PgDomainProjectionRepository;
pub use domain_source_cursor::PgDomainSourceCursorRepository;
pub use domain_source_expectation::PgDomainSourceExpectationRepository;
pub use entry_condition::PgEntryConditionRepository;
pub use equity_snapshot::PgEquitySnapshotRepository;
pub use execution_account::PgExecutionAccountRepository;
pub use execution_order::PgExecutionOrderRepository;
pub use execution_submission::PgExecutionSubmissionRepository;
pub use factor::PgFactorRepository;
pub use feature::PgFeatureRepository;
pub use feature_parity::PgFeatureParityRepository;
pub use governance_audit::PgModelGovernanceAuditRepository;
pub use market_linkage::PgMarketLinkageRepository;
pub use market_selection::PgMarketSelectionRepository;
pub use model_registry::PgModelRegistryRepository;
pub use model_run::PgModelRunRepository;
pub use order_intent::PgOrderIntentRepository;
pub use portfolio_plan::PgPortfolioPlanRepository;
pub use position::PgPositionRepository;
pub use recommendation::PgRecommendationRepository;
pub use recommendation_report::PgRecommendationReportRepository;
pub use reconciliation::PgReconciliationRepository;
pub use report_run::PgReportRunRepository;
pub use research_job::PgResearchJobRepository;
pub use research_readiness::PgResearchReadinessEvidenceRepository;
pub use reserved_capital::PgReservedCapitalRepository;
pub use shadow_comparison::PgShadowComparisonRepository;
pub use source_slice::PgSourceSliceRepository;
pub use trade_policy::PgTradePolicyRepository;
pub use trade_tape_block_cursor::PgTradeTapeBlockCursorRepository;
