//! Seed framework — type-safe, idempotent bootstrap data management.
//!
//! Strict separation from DDL migrations: schema migrations never write data,
//! bootstrap migrations never create tables. Seeds are registered via
//! `#[derive(SeedUnit)]` and executed by the `SeedRunner` in the storage layer.
//!
//! Idempotency is handled at the SQL level by each seed's `ON CONFLICT` clause.
//! `SeaORM`'s migration table tracks whether the bootstrap migration has been applied.

pub mod context;
pub mod plans;
pub mod policy;
pub mod risk_engine_state;
pub mod runtime_config;

pub use context::SeedContext;
pub use policy::SeedConflictPolicy;

/// A unit of seed data that can be applied during a bootstrap migration.
///
/// Implementations are generated by `#[derive(SeedUnit)]`; the `execute` body
/// delegates to a hand-written loader function that uses typed `SeaORM` APIs.
#[async_trait::async_trait]
pub trait SeedUnit: Send + Sync {
    /// Globally unique identifier, e.g. `"trading.risk_engine_state"`.
    fn id(&self) -> &'static str;

    /// Execution order within a `SeedPlan` (lower runs first).
    fn order(&self) -> i32;

    /// Conflict resolution strategy applied during insertion.
    fn policy(&self) -> SeedConflictPolicy;

    /// Load seed data and insert it into the database.
    ///
    /// Called within the migration transaction. Returns the number of rows affected.
    async fn execute(
        &self,
        db: &dyn sea_orm::ConnectionTrait,
        ctx: &mut SeedContext,
    ) -> Result<u64, sea_orm::DbErr>;
}

/// An ordered collection of seeds to apply in a single bootstrap migration.
pub struct SeedPlan {
    pub name: &'static str,
    seeds: Vec<Box<dyn SeedUnit>>,
}

impl SeedPlan {
    pub fn new(name: &'static str, mut seeds: Vec<Box<dyn SeedUnit>>) -> Self {
        seeds.sort_by_key(|s| s.order());
        Self { name, seeds }
    }

    pub fn seeds(&self) -> &[Box<dyn SeedUnit>] {
        &self.seeds
    }
}
